### ISSUE TITLE
non ascii chars as axis labels

### ISSUE THREAD

**Issue by gdkrmr** [JuliaPlots/Plots.jl#860] opened 2017-05-23 14:36 UTC
this happens with the GR backend, plotlyjs works fine:
```julia
julia> plot(1:10, 1:10, xlab = "α̂")
Error showing value of type Plots.Plot{Plots.GRBackend}:
ERROR: BoundsError: attempt to access 2-element Array{UInt8,1} at index [3]
 in setindex!(::Array{UInt8,1}, ::Int64, ::Int64) at ./array.jl:415
 in latin1(::String) at /home/gkraemer/.julia/v0.5/GR/src/GR.jl:456
 in text at /home/gkraemer/.julia/v0.5/GR/src/GR.jl:488 [inlined]
 in gr_text(::Float64, ::Float64, ::String) at /home/gkraemer/.julia/v0.5/Plots/src/backends/gr.jl:195
 in gr_display(::Plots.Subplot{Plots.GRBackend}, ::Measures.Length{:mm,Float64}, ::Measures.Length{:mm,Float64}, ::Array{Float64,1}) at /home/gkraemer/.julia/v0.5/Plots/src/backends/gr.jl:723
 in gr_display(::Plots.Plot{Plots.GRBackend}) at /home/gkraemer/.julia/v0.5/Plots/src/backends/gr.jl:500
 in _display(::Plots.Plot{Plots.GRBackend}) at /home/gkraemer/.julia/v0.5/Plots/src/backends/gr.jl:1121
 in display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::MIME{Symbol("text/plain")}, ::Plots.Plot{Plots.GRBackend}) at /home/gkraemer/.julia/v0.5/Plots/src/output.jl:138
 in display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::Plots.Plot{Plots.GRBackend}) at ./REPL.jl:135
 in display(::Plots.Plot{Plots.GRBackend}) at ./multimedia.jl:143
 in print_response(::Base.Terminals.TTYTerminal, ::Any, ::Void, ::Bool, ::Bool, ::Void) at ./REPL.jl:154
 in print_response(::Base.REPL.LineEditREPL, ::Any, ::Void, ::Bool, ::Bool) at ./REPL.jl:139
 in (::Base.REPL.##22#23{Bool,Base.REPL.##33#42{Base.REPL.LineEditREPL,Base.REPL.REPLHistoryProvider},Base.REPL.LineEditREPL,Base.LineEdit.Prompt})(::Base.LineEdit.MIState, ::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Bool) at ./REPL.jl:652
 in run_interface(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface) at ./LineEdit.jl:1579
 in run_frontend(::Base.REPL.LineEditREPL, ::Base.REPL.REPLBackendRef) at ./REPL.jl:903
 in run_repl(::Base.REPL.LineEditREPL, ::Base.##950#951) at ./REPL.jl:188
 in _start() at ./client.jl:363
```
happens also if `xlab = "α"`, and then plotting with `xlab` property is broken until I call plot without `xlab`.

**Comment by daschw** [comment] 2017-05-23 14:52
This is a duplicate of #791.
As a workaround you can do
```julia
using Plots, LaTeXStrings; gr()
plot(1:10, 1:10, xlab = L"\alpha")
```

**Closed** 2017-05-23 14:56 UTC
