### ISSUE TITLE
Plot Animation: How to have FPS less than 1

### ISSUE THREAD

**Issue by evveric** [JuliaPlots/Plots.jl#1981] opened 2019-04-03 08:08 UTC
e.g I have 5 Plots, and want to create a GIF to show one plot per 5 second, then move to show the next graph. 
So I need a FPS = 0.2

However, currently:
```
anim = @animate for i=1:5
    plot(...)
end
gif(anim, "/tmp/anim.gif", fps = 15)
```

fps is only integer..

How to solve that? thank you

**Comment by mkborregaard** [comment] 2019-04-03 08:28
Duplicate of #1546

**Closed by mkborregaard** 2019-04-03 08:28 UTC
