### ISSUE TITLE
Accuracy of ticks

### ISSUE THREAD

**Issue by ranocha** [JuliaPlots/Plots.jl#1792] opened 2018-10-16 07:15 UTC
The accuracy of the ticks can be annoying sometimes:
```julia
using Plots
plot(1.25e-12 .* range(0., stop=1., length=100))
```
Using GR, this yields
![screenshot_20181016_090952](https://user-images.githubusercontent.com/12693098/46998729-b4ab8400-d123-11e8-85a4-580c89dce4fa.png)
The behaviour for PyPlot and Plotly is similar.

I would prefer `6.0` instead of `6.000....001`. This might be related to #749.

I'm using `[91a5bcdd] Plots v0.20.6` on Julia `Version 1.0.2-pre.0 (2018-09-30)`.

**Comment by michakraus** [comment] 2020-02-11 08:33
This problem still persists (Plots v0.29.1 #master of 10.02.2020 and Julia 1.3.1). Interestingly, manually calling `optimize_ticks()` as suggested in https://discourse.julialang.org/t/more-ticks-in-plots-jl/5575 seems to work around the problem.

Calling
```
x = 1.25e-12 .* range(0., stop=1., length=100)
optimize_ticks(extrema(x)...)
```
gives
```
([0.0, 2.5e-13, 5.0e-13, 7.5e-13, 1.0e-12, 1.25e-12], 0.0, 1.25e-12)
```
Thus, 
```
plot(x; yticks=optimize_ticks(extrema(x)...)[1])
```
results in
![ticks_issue](https://user-images.githubusercontent.com/21168502/74221046-78554d00-4cb1-11ea-8d4e-72b667894ee8.png)

**Comment by michakraus** [comment] 2020-02-11 12:46
It seems possible to work around the GR issues, however I do not fully understand what is happening and if this is intended behaviour. It seems manually set ticks are not properly processed in the GR backend. Consider the following example:

```
using Plots
using Plots: convert_sci_unicode
using Showoff

x = 1.25e-12 .* range(0., stop=1., length=100)
yticks = optimize_ticks(extrema(x)...)[1]
```
First Plotly,
```
plotlyjs()
plot(x; yticks=(yticks, Showoff.showoff(yticks, :scientific)))
```
![ticks_issue_plotly_optimize](https://user-images.githubusercontent.com/21168502/74237493-f9bdd700-4cd3-11ea-9056-a5c4aa90969c.png)

Then GR,
```
gr()
plot(x; yticks=(yticks, Showoff.showoff(yticks, :scientific)))
```
![ticks_issue_gr_optimize](https://user-images.githubusercontent.com/21168502/74237500-fde9f480-4cd3-11ea-83e9-81fe7846ddb1.png)

In the GR backend, the function `convert_sci_unicode` is called on the ticks labels. It seems, this is not happening here, i.e., if ticks are set manually. Adding it by hand leads to the desired result,
```
gr()
plot(x; yticks=(yticks, convert_sci_unicode.(Showoff.showoff(yticks, :scientific))))
```
![ticks_issue_gr_optimize_sci](https://user-images.githubusercontent.com/21168502/74237585-2e319300-4cd4-11ea-85de-8514f52e7a22.png)

That however does not work well with Plotly,
```
plotlyjs()
plot(x; yticks=(yticks, convert_sci_unicode.(Showoff.showoff(yticks, :scientific))))
```
![ticks_issue_plotly_optimize_sci](https://user-images.githubusercontent.com/21168502/74237609-3c7faf00-4cd4-11ea-9f4e-5d33f5c2867b.png)

which is probably not a surprise.

**Comment by mkborregaard** [comment] 2020-02-11 12:57
Great detective work! I wonder why that is bypassed for the ticks?

**Comment by michakraus** [comment] 2020-02-11 13:05
I actually do believe that this is not limited to the ticks, see e.g. the following example:
```
gr()
plot(x, xlab="x₁")
```
![label_issue_gr](https://user-images.githubusercontent.com/21168502/74239140-874ef600-4cd7-11ea-85d0-d944f0e61b82.png)
It seems like the label should be passed as well but is not.

**Comment by michakraus** [comment] 2020-02-11 13:10
Btw, the aforementioned workaround of calling `optimize_ticks` manually solves the problem in some cases but not always.

**Comment by daschw** [comment] 2020-02-11 13:23
Putting
```julia
# enable utf8 encoding for GR
ENV["GKS_ENCODING"] = "utf-8"
```
in your julia startup file could help with the unicode support for GR, not sure, if it helps here.

**Comment by michakraus** [comment] 2020-02-11 13:26
Indeed, that solves the problem with both, the ticks and the labels. Thank you!

**Comment by daschw** [comment] 2020-02-11 13:30
> Btw, the aforementioned workaround of calling optimize_ticks manually solves the problem in some cases but not always.

Another possibility instead of manually calling `optimize_ticks` could be e.g.
```
plot(x, widen=false)
```
This calls optimize_ticks with slightly different axes limits and might lead to different results for the ticks. Does not work always, but in the example above.

However, Plots should ensure that tick_labels like 5.999999999999999999 are always rounded. Maybe, there is still an issue in Showoff.jl

**Comment by daschw** [comment] 2020-02-11 13:31
We should probably add `ENV["GKS_ENCODING"] = "utf-8"` to the documentation.

**Comment by mkborregaard** [comment] 2020-02-11 14:14
Can we not set it from Plots?

**Comment by michakraus** [comment] 2020-02-11 14:17
> Another possibility instead of manually calling `optimize_ticks` could be e.g.
> 
> ```
> plot(x, widen=false)
> ```

That as well solves some of my issues, but not all of them. I just tried, in a very brute force way, to call
```
ticks = optimize_ticks(extrema(ΔH)...; k_min=4)[1]
labels = format_fixed_scientific.(ticks, 2, false)
```
but not even that works... so yes, there seems to be a problem in Showoff.

**Comment by daschw** [comment] 2020-02-11 14:41
> Can we not set it from Plots?

Maybe. @jheinen can there be any undesired effects if we set `ENV["GKS_ENCODING"] = "utf-8"` in Plots?

**Comment by jheinen** [comment] 2020-02-11 16:46
The alignment might be inexact - but this will be fixed in the near future. I'm working on a module to draw glyphs using outlines, especially for the CM Serif-Roman Font (which is used by LaTeX). With those changes, the alignment will be exact (on all GR output devices).

**Comment by michakraus** [comment] 2020-02-12 16:07
> However, Plots should ensure that tick_labels like 5.999999999999999999 are always rounded. Maybe, there is still an issue in Showoff.jl

This is in fact the case. In all of my examples, Plots (e.g. via optimize_ticks()) produces nice numbers like
```
[0.0, 2.0e-15, 4.0e-15, 6.0e-15]
```
but Showoff turns this into
```
["0", "2.0×10⁻¹⁵", "4.0×10⁻¹⁵", "5.99999999999999911×10⁻¹⁵"]
```
The problem seems to be the division of `x` by `10^mag` in [Showoff.jl, Line 215](https://github.com/JuliaGraphics/Showoff.jl/blob/8502c2ec11f93c4f50c609ff4168aab31154b39d/src/Showoff.jl#L215).
 Consider the following
```
> x = 6.0e-15
6.0e-15
> mag = floor(Int, log10(abs(x)))
-15
> x / 10.0 ^ mag
5.999999999999999
```
This together with the issue described [here](https://github.com/JuliaGraphics/Showoff.jl/issues/18#issuecomment-584736912) seems to be the root of all evil.

**Comment by isentropic** [comment] 2021-02-16 02:14
@michakraus do you want to check out https://github.com/JuliaGraphics/Showoff.jl/pull/31

I think the PR won't get merged for some while, but if someone could help out with testing perhaps we can close this issue then. This issue has been a major annoyance for me too. The fork requires 1.5 or above or Ryu in the base installed. Now that grisu would be removed from base, perhaps it is time for some testing with Ryu. Maybe it would make things better.

**Comment by isentropic** [comment] 2021-02-16 02:15
In order to test this fork, you'd need to start `dev`ing Plots and change the Showoff dependency to this modified Showoff

**Comment by isentropic** [comment] 2021-03-12 09:02
Feel free to reopen if persists

**Comment by ranocha** [comment] 2021-03-15 04:30
I still get the same bad result on Julia v1.6.0-rc1 and Plots v1.10.6, but I can't re-open this issue.

**Comment by michakraus** [comment] 2021-03-18 10:20
It seems Plots restricts the Showoff version to v0.3.1, but the patch to this issue came with Showoff v1.0.0.

**Comment by isentropic** [comment] 2021-03-18 10:37
Yeah the proper release is soon to follow, perhaps you could help out by pinning Showoff#master branch and seeing if it works (You'd also want to have julia > 1.4)

**Comment by michakraus** [comment] 2021-03-18 10:39
Just did, works fine:

```
plot(1.25e-12 .* range(0., stop=1., length=100))
```

![plots_precision_issue](https://user-images.githubusercontent.com/21168502/111613201-8cd21600-87de-11eb-95a1-f721bfcfec84.png)

**Comment by isentropic** [comment] 2021-03-18 10:42
It should be Showoff#master too, and perhaps give it a go for a few days and see if it is strictly better. We can't afford to break everyone's plots 😄

**Comment by isentropic** [comment] 2021-03-18 10:43
You'd need to stard dev'ing plots, and pinning Showoff#master

**Comment by isentropic** [comment] 2021-03-18 10:44
There is a questionable bug that needs resolving https://github.com/JuliaGraphics/Showoff.jl/issues/39

**Comment by michakraus** [comment] 2021-03-18 10:49
I am on #master on both Plots and Showoff and everything looks fine, including the example from JuliaGraphics/Showoff.jl#39

**Comment by isentropic** [comment] 2021-03-23 03:09
@michakraus feel free to reopen if it persists with just Plots#master or the latest release. I think it is done

**Closed by isentropic** 2021-03-23 03:09 UTC
