### ISSUE TITLE
[BUG] Distorted log-scale heatmap and 2d-hist plots with GR

### ISSUE THREAD

**Issue by oschulz** [JuliaPlots/Plots.jl#3643] opened 2021-07-15 08:13 UTC
With the GR backend (Plots v1.19.1), heatmaps (and so 2D histograms too) are distorted if the axis range spans several decades:

```julia
using Plots; gr()

z = rand(Bool, 50, 50)
plot(
    heatmap(z),
    heatmap(10 .^ range(-2, 0, length=50), 10 .^ range-2, 0, length=50), z, scale = :log10),
    heatmap(10 .^ range(-5, 0, length=50), 10 .^ range(-5, 0, length=50), z, scale = :log10),
    heatmap(10 .^ range(0, 5, length=50), 10 .^ range(-5, 0, length=50), z, scale = :log10)
)
```

results in this plot:

![log-heatmaps-gr](https://user-images.githubusercontent.com/546147/125753070-25e5890a-7a3e-4cd3-9610-605d2417e965.png)

all four sub-plots should look the same (except for the axis scales), but the lower two (with axes spanning 5 decades) are very distorted.

With pyplot

```julia
pyplot()

plot(
    heatmap(z),
    heatmap(10 .^ range(-2, 0, length=50), 10 .^ range(-2, 0, length=50), z, scale = :log10),
    heatmap(10 .^ range(-5, 0, length=50), 10 .^ range(-5, 0, length=50), z, scale = :log10),
    heatmap(10 .^ range(0, 5, length=50), 10 .^ range(-5, 0, length=50), z, scale = :log10)
)
```

everything looks fine:

![log-heatmaps-pyplot](https://user-images.githubusercontent.com/546147/125753112-701dd799-f190-4002-8e46-9f3746357813.png)

I'm not sure if this is a Plots or GR bug (CC @jheinen ).

**Comment by t-bltg** [comment] 2021-07-15 10:26
In GR, the un-distorted plots are plotted using the first branch of https://github.com/JuliaPlots/Plots.jl/blob/c046e6461f0ea7b8499d18c28ccc98021f9e239a/src/backends/gr.jl#L1911
whereas the distorted are plotted using the second branch.

**Comment by t-bltg** [comment] 2021-07-15 11:07
Reproducible reduced case (there is also a transpose issue with pyplot):

```julia
using Plots; gr()
using Random; Random.seed!(1234)

main() = begin
  m, n = 4, 8
  z = transpose(rand(Bool, m, n))
  plot(
    heatmap((10.).^range(-2, 0, length=m), (10.).^range(-2, 0, length=n), z, scale=:log10),
    heatmap((10.).^range(-5, 0, length=m), (10.).^range(-5, 0, length=n), z, scale=:log10),
    layout=(2, 1)
  )
  png("hm")
  return
end

main()
```

Pyplot
---
![hm-pp](https://user-images.githubusercontent.com/13423344/125778333-376eb802-244e-4442-bb3e-370fcafeb233.png)

Gr
---
![hm-gr](https://user-images.githubusercontent.com/13423344/125778340-257ce9fa-1328-4250-b585-22539941cc18.png)

**Comment by jheinen** [comment] 2021-11-19 09:12
The problem is fixed in the development branch of GR (see [this](https://github.com/sciapp/gr/commit/43fdc9ba50011df1897b4894ad0daf238c5b21fe) commit)- a new release will be tagged soon.
<img width="712" alt="Screen Shot 2021-11-19 at 10 07 37" src="https://user-images.githubusercontent.com/5718244/142596090-7c962fd8-a00c-44a2-973c-b623c7ee81fc.png">
<img width="712" alt="Screen Shot 2021-11-19 at 10 11 38" src="https://user-images.githubusercontent.com/5718244/142596657-ff3b6e43-2e65-4683-af83-6e7d2a06207b.png">

**Comment by oschulz** [comment] 2021-11-19 10:38
Thanks a lot @jheinen !

**Comment by t-bltg** [comment] 2022-11-20 12:38
This issue seems fixed.

**Closed by t-bltg** 2022-11-20 12:38 UTC
Labels: bug, GR
