### ISSUE TITLE
[BUG] Markers are at wrong places in 3d plot when `xflip = true`

### ISSUE THREAD

**Issue by bowenszhu** [JuliaPlots/Plots.jl#4355] opened 2022-09-16 22:06 UTC
## Details

```julia
using Plots
plot([1, 2, 3], [2, 3, 1], [3, 1, 2], markershape = :circle, xflip = true)
```

![plt](https://user-images.githubusercontent.com/45696147/190809825-6bb62201-c9af-4adb-a756-dccf4682a41b.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  `x`   |     |
pyplot       |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
unicodeplots |     |     |
inspectdr    |     |     |
gaston       |     |     |

### Versions

Plots.jl version: v1.33.0
Backend  version (`]st -m <backend(s)>`): v0.66.2
Output of `versioninfo()`:
```julia
Julia Version 1.8.1
Commit afb6c60d69a (2022-09-06 15:09 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 6 on 12 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 6
```

**Comment by songhanzhang** [comment] 2022-09-17 02:20
I tried to remove "xflip = true" and it becomes fine. I think the issue is caused by the "xflip".

**Comment by t-bltg** [comment] 2022-09-17 10:13
Axis ticks position is fixed thanks to https://github.com/JuliaPlots/Plots.jl/pull/4356, but markers not yet.

**Comment by t-bltg** [comment] 2023-02-14 10:03
Fixed in latest GR version.

**Closed by t-bltg** 2023-02-14 10:03 UTC
Labels: bug, GR
