### ISSUE TITLE
Embedding of 16mb plotly in Jupyter notebooks (when using GR!)

### ISSUE THREAD

**Issue by jlperla** [JuliaPlots/Plots.jl#1780] opened 2018-10-05 04:07 UTC
cc: @arnavs @sglyon 

Unless we are missing something, as soon as you do `using Plots` in a Jupyter notebook, it is embedding the entire https://cdn.plot.ly/plotly-latest.min.js inside of a cell.... even when you have no intention of using the plotly backend.

Replicating this is easy:
- Get the latest `Plots`
- Create a jupyter notebook and execute a single cell with `using Plots` in it... which presumaly uses the `GR` backend.  Alternatively, call `gr()` after
- Save the notebook.  No actual graphs required
- Check the filesize:  16493KB on my system

We traced this down to https://github.com/JuliaPlots/Plots.jl/blob/80151ac1a30c498592ac94ee03d5a7af6d2df8de/src/backends/plotly.jl#L94 which splices all of `plotly-latest.min.js` into string and spits it into the notebook if `isijulia()`

Besides the massive file sizes, we are pretty sure this is causing other grief in using Plots.jl in a jupyter environment.  They could be related to the fact that `<script>` is not immediately trust

**Comment by jlperla** [comment] 2018-10-05 04:11
I think there are two parts to a solution:
1. Is there any way to not have the `src/backends/plotly.jl` automatically execute, or at least that section of code which creates a 16MB string and embeds it, if the user is not actually using the plotly backend?  Maybe call that setup code only if they call `plotly()`, for example
2. If someone does use plotly, then there is a better way to deal with the issue.  @sglyon  had some thoughts about that and using `WebIO` instead of the current solution.

For me, though, I have no intention of using the `plotly` backend, and am perfectly content with a patch so that this code just doesn't execute.

**Comment by mkborregaard** [comment] 2018-10-05 06:06
This is a duplicate of https://github.com/JuliaPlots/Plots.jl/issues/1724 , so I'm closing this in favour of that issue. See also https://github.com/JuliaPlots/Plots.jl/pull/1777

**Closed by mkborregaard** 2018-10-05 06:06 UTC
