### ISSUE TITLE
[FR]: Horizontal outerbottom legends

### ISSUE THREAD

**Issue by yordiak** [JuliaPlots/Plots.jl#2803] opened 2020-06-20 13:20 UTC
hello, here is a small example

```julia
using Plots, LaTeXStrings

gr()

θ(ρ)=ρ
g(θ)=θ/(1-θ)
g_hat(θ)=1.5

plot([g, g_hat], 0,0.8, legend=:outerbottom, grid=false, xaxis=L"$\rho$", yaxis=L"$g,\hat{g}$")
```

It would be nice if the was an option (something like `outerbottomh`) that sets the legends horizontally, instead of vertically.

**Comment by BeastyBlacksmith** [comment] 2020-06-22 08:42
duplicate of https://github.com/JuliaPlots/Plots.jl/issues/2206

**Closed** 2022-11-05 11:49 UTC
Labels: duplicate
