### ISSUE TITLE
Misalign dot with Courier font in GR [BUG]

### ISSUE THREAD

**Issue by Ezequiel92** [JuliaPlots/Plots.jl#3216] opened 2021-01-07 16:15 UTC
## Details

The dot separating decimals is misalign when using the Courier font in GR. I don´t know at which level this is happening, Plots, GR or the font itself. 

The MWE 

```julia
using Plots

data_linear = rand(10) * 1.5

plot(data_linear, title="1.0 Myr", titlefont="Courier", ytickfontsize=20, ytickfont="Courier")
annotate!(5, 0.75, Plots.text("1.0 Myr", "Courier", 25, :center))
```

produces

![annotate_gr_courier](https://user-images.githubusercontent.com/76693950/103913623-84c36f00-50e7-11eb-9fc4-96bc92796d65.png)

While the default font

```julia
plot(data_linear, title="1.0 Myr", ytickfontsize=20)
annotate!(5, 0.75, Plots.text("1.0 Myr", 25, :center))
```

produces

![annotate_gr_default](https://user-images.githubusercontent.com/76693950/103913733-a290d400-50e7-11eb-95a2-bc761090e3d4.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |     |     |x
plotly       |     |     |x
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
inspectdr    |     |     |x

## Versions

From `julia> versioninfo()` 

``` 
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
``` 

From `(@v1.5) pkg> status` 

``` 
[91a5bcdd] Plots v1.10.1
``` 

From `(@v1.5) pkg> st -m`

```
[28b8d3ca] GR v0.53.0
[d2c73de3] GR_jll v0.53.0+0
```

**Comment by daschw** [comment] 2021-01-09 18:36
I suppose this is rather a GR problem, right @jheinen?

**Comment by jheinen** [comment] 2021-01-10 04:52
I will have to check it on Windows. Probably related to `GR_jll`. On macOS 11 I get:
<img width="712" alt="Screen Shot 2021-01-10 at 05 42 00" src="https://user-images.githubusercontent.com/5718244/104114651-1b21ab80-5307-11eb-803e-0469a8ac9f62.png">
<img width="712" alt="Screen Shot 2021-01-10 at 05 44 25" src="https://user-images.githubusercontent.com/5718244/104114657-27a60400-5307-11eb-8e46-fd7b0230d7d5.png">

**Comment by jheinen** [comment] 2021-01-10 05:07
Hmm - can't reproduce:
```julia
(v1.5) pkg> st
Status `\\Mac\S\lib\julia\environments\v1.5\Project.toml`
  [28b8d3ca] GR v0.53.0 `https://github.com/jheinen/GR.jl.git#master`
  [7073ff75] IJulia v1.23.1
  [b964fa9f] LaTeXStrings v1.2.0
  [91a5bcdd] Plots v1.10.1 `https://github.com/JuliaPlots/Plots.jl.git#master`
  [d330b81b] PyPlot v2.9.0
  [992d4aef] Showoff v0.3.2 `https://github.com/JuliaGraphics/Showoff.jl.git#master`
```

<img width="294" alt="Screen Shot 2021-01-10 at 06 04 00" src="https://user-images.githubusercontent.com/5718244/104114902-c0d61a00-5309-11eb-8af9-5529cf2a29df.png">

**Comment by Ezequiel92** [comment] 2021-01-10 19:12
I just check it out, and my result is using `savefig()`, sorry for the misleading MWE, I thought that they would be the same, but apparently part of the bug is that they are not! 

So, the situation is like this, with 

```julia 
using Plots 

plot(rand(10) * 1.5, title="1.0 Myr", titlefont="Courier", ytickfontsize=20, ytickfont="Courier") 
annotate!(5, 0.75, Plots.text("1.0 Myr", "Courier", 25, :center)) 
``` 

I get the same as you 

![vscode_panel](https://user-images.githubusercontent.com/76693950/104131024-b12ef380-5352-11eb-9cc2-e590b66270cd.png) 

while with 

```julia 
using Plots 

plot(rand(10) * 1.5, title="1.0 Myr", titlefont="Courier", ytickfontsize=20, ytickfont="Courier") 
annotate!(5, 0.75, Plots.text("1.0 Myr", "Courier", 25, :center)) 
savefig("saved_img.png") 
``` 

I get the misalign one 

![saved_img](https://user-images.githubusercontent.com/76693950/104132647-7a120f80-535d-11eb-815d-d5a1fdbeeda0.png) 

Another weird difference, is that the saved one is render with gray characters, while the one shown in a window in vscode is black, as one would expect. 

I hope that clarifies the situation.

**Comment by jheinen** [comment] 2021-01-12 12:40
The problem is fixed [here](https://github.com/sciapp/gr/commit/586e0c568f814e300404f90b65b33d193f1bd557). We will tag a new release soon.


![saved_img](https://user-images.githubusercontent.com/5718244/104315481-4e1c9880-54db-11eb-885f-8076104b9e97.png)

**Comment by daschw** [comment] 2021-01-12 12:52
Closing, as this will be fixed by the next GR release.

**Closed by daschw** 2021-01-12 12:52 UTC
Labels: GR, bug
