### ISSUE TITLE
[FR] accept AbstractVector for `label` keyword argument

### ISSUE THREAD

**Issue by st--** [JuliaPlots/Plots.jl#4199] opened 2022-05-06 11:57 UTC
I discovered #4198 when trying to plot multiple columns with their own labels in one `plot` call, and not realizing that I would need a _row_ vector such as `["A" "B" ...]` and instead passed `["A", "B", ...]` which GR then converts into a single long string. Would it be possible for Plots.jl to simply support `AbstractVector`s for the `label` keyword argument (as there should not be any ambiguity)?

In my use case I have the labels as a variable `vec_of_labels = ["A", "B", ...]`, so it's particularly annoying that I can't simply have `plot(...; label=vec_of_labels')` because `'` isn't defined for vectors of strings. So instead requires `plot(...; label=reshape(vec_of_labels, 1, :))` which seems needlessly verbose to me.

**Comment by BeastyBlacksmith** [comment] 2022-05-06 13:05
I think it is fairly well documented that [columns are series](https://docs.juliaplots.org/dev/input_data/#columns-are-series).

In the case of series attributes the question that might arise is: "What are rows then?"
And, while in this case not implemented in the GR backend, the philosophy is: rows are segments.

So for example using the pgfplotsx-backend one can do the following:
```julia
using Plots
pgfplotsx()
scatter(1:2, color=[:red, :blue], label=["a", "b"])
```

So the only advice, I can give is to use `permutedims` instead of `reshape`, since that only requires one argument.

Related: https://github.com/JuliaPlots/Plots.jl/pull/2680
Duplicate of #901

**Closed** 2022-11-24 19:57 UTC
Labels: duplicate, wontfix
