### ISSUE TITLE
reduce the size of Plots.jl (for JuliaBox)?

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaPlots/Plots.jl#1008] opened 2017-08-14 19:17 UTC
Dear Plots.jl maintainers,

I want to use JuliaBox for a Julia course (MSc level, finance) and Plots.jl plays a key role. However, installing Plots.jl seems to take up a lot of disk space (almost 200MB?), which is a problem since each user is only allocated 500MB. Is there any chance of reducing that?

/Paul Söderlind

**Comment by joshday** [comment] 2017-08-14 20:11
This is a dup of https://github.com/JuliaPlots/Plots.jl/issues/264

There are some old gifs and Jupyter notebooks hanging around in the git history, so there's nothing Plots can do without erasing history, which is sketchy.  Julia's package manager will sometime be changed to https://github.com/StefanKarpinski/Pkg3.jl, which will solve this, but if you're working on a course for this fall, you may be out of luck.

**Comment by mkborregaard** [comment] 2017-08-15 09:25
Sorry about this, what @joshday says is correct. This is the main reason that Plots does not exist on JuliaPro. It is an artefact of the Pkg2 package manager cloning the entire git history, and will thus be solved by Pkg3.

**Comment by mkborregaard** [comment] 2017-08-15 09:26
I'm closing this because it's a duplicate of the previous discussion.

**Closed by mkborregaard** 2017-08-15 09:26 UTC

**Comment by PaulSoderlind** [comment] 2017-08-15 09:45
Just a follow up question, would this work?
(1) clone Plots.jl
(2) slim it down by deleting the git history
(3) install this slimmed version on JuliaBox?

Is this reasonably easy to do myself? (Am I allowed to?)

/Paul S

**Comment by mkborregaard** [comment] 2017-08-15 09:58
I'm guessing that would work if you fork it to your own profile first. Even though it's not ideal I can see it functioning as a workaround for a specific course, if you can't install Plots through the package manager.
