### ISSUE TITLE
[BUG] GKS: Rectangle definition is invalid in routine SET_VIEWPORT

### ISSUE THREAD

**Issue by darsnack** [JuliaPlots/Plots.jl#2804] opened 2020-06-20 23:43 UTC
Other issues have a similar error messages, but none appear related to the context leading to my error. As far as I can tell from previous issues, this error message is fairly generic and not representative of the core problem.

## Details

The following code (previously working for many versions of Plots.jl over the past year or so) produces an error.

```julia
# plot raster plot
inspikes = round.(∂t .* spikes; digits = 6)
outspikes = round.(∂t .* output; digits = 6)
scatter(inspikes, fill(1, length(spikes)), label = "Input",
        xlabel = "Time (sec)", ylabel = "", yticks = :none, title = "Raster Plot (\\alpha response)")
raster_plot = scatter!(outspikes, fill(2, length(output)), label = "Output")
```

The error:
```
GKS: Rectangle definition is invalid in routine SET_VIEWPORT
```

The value of the data just to show I am not plotting stuff with crazy precisions.
```
julia> inspikes
18-element Array{Float64,1}:
  0.7
  1.1
  1.19
  2.34
  4.17
  5.21
  6.3
  7.65
  8.2
  8.63
  9.15
  9.31
 10.36
 10.45
 11.25
 11.77
 11.78
 14.97

julia> outspikes
6-element Array{Float64,1}:
  1.77
  3.66
  6.14
  9.97
 12.64
 14.41
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x  |     |
pyplot       |     |  x  | 
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: `[91a5bcdd] Plots v1.4.3`
Backend  version (`]st -m`): `[28b8d3ca] GR v0.50.1`
Output of `versioninfo()`:
```
julia> versioninfo()
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

**Comment by nfernandez-arias** [comment] 2020-07-03 22:32
Hello,

I am having the same error. I make a bunch of plots and then arrange them into a subplot. This has worked with no issues until today when I tried it (using exactly the same data in the plots). I also know for sure that the data is not requiring some absurd degree of precision. They are normal looking plots, and I have literally seen them before in exactly the form I want them in previous version of Plots.jl.

Now it gives me a bunch of GKS: Rectangle definition is invalid in routine SET_WINDOW errors, and then at the end when I call

plot(p1,p2,p3,p4)

To arrange them into a subplot, it just plots them all on top of each other.

Why would this start happening all of a sudden? Was there an update to Plots.jl or Measures.jl?

**Comment by daschw** [comment] 2020-07-04 19:58
The issue in the original code is `title = "Raster Plot (\\alpha response)"` replacing this with e.g. `title = "Raster Plot (α response)"` works. This seems somehow related to https://github.com/JuliaPlots/Plots.jl/issues/1842 and https://github.com/JuliaPlots/Plots.jl/issues/2715.

**Comment by daschw** [comment] 2020-07-04 20:11
@jheinen the root of this issue seems to be:
```julia
julia> GR.jlgr.inqtext(0, 0, "Raster Plot (\\alpha response)")
([NaN, NaN, NaN, NaN], [NaN, NaN, NaN, NaN])
```
(Plots has a similar logic like jlgr to decide between `GR.inqmathtex`, `GR.inqtextext` and `GR.inqtext`)

**Comment by darsnack** [comment] 2020-07-04 23:11
Makes sense. The working “X” for pyplot also switched the \\ notation. I’ll try without that for GR and report back.

**Comment by nfernandez-arias** [comment] 2020-07-05 15:43
Removing the `\\` notation fixes the problem in my case too

Does this mean that the only way to have LaTeX in the plots at this point is to use the LaTeXStrings package?

**Comment by jheinen** [comment] 2020-07-05 17:03
I will check this and try to allow both notations ...

**Comment by nfernandez-arias** [comment] 2020-07-05 17:27
There is one thing I can't get to work like before.

I have some plots that look like this

`p = bar(xAxisLabels,grad, title = "\$ \\nabla_p \\log (\\textrm{CEV Welfare chg. \\%}) \$")`

Before this bug, these worked fine. Now, it gives me an error and renders the stuff inside \\textrm{} in math mode, and puts a "?" right before this where the \t is. This is also the case now when I do this with LaTeXStrings. Could this be related?

**Comment by nfernandez-arias** [comment] 2020-07-05 18:00
There are still some issues that I am having trouble fixing. Previously I had a some code 

```
xAxisLabels = ["r"; "g"; "OI"; "E"; "S"; "RD"; "\$ \\Large \\theta \$"; "\$ \\Large  \\beta \$"; "\$ \\Large  \\psi \$"]
p = bar(xAxisLabels, transpose(invjac) * grad, title = "\$ \\nabla_m \\log (\\textrm{CEV Welfare chg. \\%}) \$")
```

which seemed to work. Now, it does not recognize the \\Large. And more importantly, it does not recognize the \\textrm{} anymore.

But the most confusing part is that it gives me no errors when I run it line by line. But when I run a script containing these lines, I get the same GKS: Rectangle definition is invalid in routine SET_VIEWPORT error, and it jumbles up the whole plot.

Apologies if this description of the pathology is not 100% clear. It is difficult to succinctly describe how this is failing. I have spent the last hour trying to figure out what the pattern is the best I can.

**Comment by jheinen** [comment] 2020-07-05 18:18
The "internal" `mathtex` renderer only supports a LaTeX subset. I could add a flag to force the use of the old one (based on "external" `dvipng` command as part of a LaTeX installation) or (you could) use workarounds like `L"\nabla_p \log\ (CEV\ Welfare\ chg. \%)"`.

**Comment by nfernandez-arias** [comment] 2020-07-05 19:13
Just to make sure I understand your suggestion, it only adds spaces, but does not render the text in normal text mode, correct?  This is probably fine for now and I really appreciate your help. Will this feature be added at some point? Often it is useful to be able to combine math and non-math expressions in the title or labels of a plot.

**Comment by darsnack** [comment] 2020-07-06 13:26
I can confirm that the same type of change `\\alpha` -> `⍺` works for me.

**Comment by jheinen** [comment] 2020-07-06 13:39
The `textrm` problem is fixed in [gr#develop](https://github.com/sciapp/gr/commit/547781f5907d25d4b685866c4300fad0d562cc36). `plot(randn(10), title = "\$ \\nabla_p \\log (\\textrm{CEV Welfare chg. %}) \$")` :
![Screenshot 2020-07-06 at 15 36 51](https://user-images.githubusercontent.com/5718244/86599175-8b3d2680-bf9e-11ea-8435-a3088204a722.png)

**Comment by codekomali** [comment] 2021-01-24 15:30
I can confirm that the same type of change \\sigma -> σ worked for me. 
New to julia and I just installed everything. I found this bug while following along the youtube tutorial "Intro to Flux"

**Closed** 2021-09-25 09:29 UTC
Labels: bug, GR

**Comment by jheinen** [comment] 2022-09-21 13:59
Could you please provide a MWE with minimal requirements?

**Comment by vuolleko** [comment] 2022-09-22 12:08
Here's a quick one that stops working with over 128 subplots (no special characters involved):

`using Turing, StatsPlots
@model mwe(x) = begin
    n = size(x, 2)
    p = Vector{Float64}(undef, n)
    for i = 1:n
        p[i] ~ Beta(1, 1)
        x[:, i] ~ Bernoulli(p[i])
    end
end
n = 65
p = rand(n)
x = reduce(hcat, [rand(Bernoulli(p[i]), 10) for i in 1:n])
m = mwe(x)
ch = sample(m, NUTS(), 1000)
plot(ch)`

I.e. the plot still works with `n = 64` (though the scaling is useless). For what it's worth, this many subplots are useful in MCMC context.

I have Julia 1.8.1, Plots v1.33.0, StatsPlots v0.15.3 and lot's of other stuff just `Pkg.updated`.

**Comment by t-bltg** [comment] 2022-09-23 12:41
> plot(1, layout=(10, 2))

Fixed on `master`.
