### ISSUE TITLE
Problem with GR bar chart - does not display all x labels

### ISSUE THREAD

**Issue by eosfor** [JuliaPlots/Plots.jl#3854] opened 2021-09-28 23:42 UTC
Hello colleagues,

For some reason, GR backend does not show all labels on the x-axis. Is there any way to fix it?

![image](https://user-images.githubusercontent.com/9363027/135179597-481d00f3-d189-4b99-8965-eb752b5cbd9a.png)

### Versions

Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

(@v1.6) pkg> st GR
      Status `~/.julia/environments/v1.6/Project.toml`
  [28b8d3ca] GR v0.59.0

**Comment by BeastyBlacksmith** [comment] 2021-09-29 07:15
duplicate of https://github.com/JuliaPlots/Plots.jl/issues/1018.
Use `xticks = :all`.

**Closed by BeastyBlacksmith** 2021-09-29 07:15 UTC
Labels: bug
