### ISSUE TITLE
MethodError: no method matching py_color(::ColorGradient, ::Nothing)

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#1876] opened 2019-01-02 00:06 UTC
Something has been broken:

```julia
using Plots
pyplot()

θs = 0.0:0.06346651825433926:6.283185307179586
rs = [0.845692, 0.500665, 0.764702, 0.851246, 0.757517, 1.63206, 1.5355, 1.22237, 0.96965, 1.03994, 0.96533, 0.671565, 0.703021, 0.833558, 0.780069, 0.863198, 0.794035, 0.596641, 0.566495, 0.553401, 0.675192, 1.95, 1.36911, 0.537583, 1.3791, 1.18953, 1.06021, 0.666625, 0.714839, 0.758672, 1.01693, 1.45931, 1.78294, 1.71191, 1.57319, 1.16309, 1.13252, 0.900187, 1.51493, 1.39752, 1.38462, 1.93691, 1.00486, 0.906562, 0.891647, 0.843715, 0.795713, 0.66663, 0.805081, 0.845692]

plot(θs, rs)
```
```
MethodError: no method matching py_color(::ColorGradient, ::Nothing)
Closest candidates are:
  py_color(::ColorGradient) at /home/juliohm/.julia/packages/Plots/cDXot/src/backends/pyplot.jl:62
  py_color(!Matched::Colorant, ::Any) at /home/juliohm/.julia/packages/Plots/cDXot/src/backends/pyplot.jl:63
  py_color(::Any) at /home/juliohm/.julia/packages/Plots/cDXot/src/backends/pyplot.jl:59

Stacktrace:
 [1] py_add_series(::Plots.Plot{Plots.PyPlotBackend}, ::Plots.Series) at /home/juliohm/.julia/packages/Plots/cDXot/src/backends/pyplot.jl:443
 [2] _before_layout_calcs(::Plots.Plot{Plots.PyPlotBackend}) at /home/juliohm/.julia/packages/Plots/cDXot/src/backends/pyplot.jl:889
 [3] prepare_output(::Plots.Plot{Plots.PyPlotBackend}) at /home/juliohm/.julia/packages/Plots/cDXot/src/plot.jl:254
 [4] show(::Base64.Base64EncodePipe, ::MIME{Symbol("image/png")}, ::Plots.Plot{Plots.PyPlotBackend}) at /home/juliohm/.julia/packages/Plots/cDXot/src/output.jl:199
 [5] #base64encode#3(::Nothing, ::Function, ::Function, ::MIME{Symbol("image/png")}, ::Vararg{Any,N} where N) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Base64/src/encode.jl:206
 [6] base64encode(::Function, ::MIME{Symbol("image/png")}, ::Vararg{Any,N} where N) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Base64/src/encode.jl:203
 [7] display_dict(::Plots.Plot{Plots.PyPlotBackend}) at /home/juliohm/.julia/packages/Plots/cDXot/src/init.jl:72
 [8] #invokelatest#1 at ./essentials.jl:686 [inlined]
 [9] invokelatest at ./essentials.jl:685 [inlined]
 [10] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /home/juliohm/.julia/packages/IJulia/DL02A/src/execute_request.jl:97
 [11] #invokelatest#1 at ./essentials.jl:686 [inlined]
 [12] invokelatest at ./essentials.jl:685 [inlined]
 [13] eventloop(::ZMQ.Socket) at /home/juliohm/.julia/packages/IJulia/DL02A/src/eventloop.jl:8
 [14] (::getfield(IJulia, Symbol("##12#15")))() at ./task.jl:259

```

**Comment by juliohm** [comment] 2019-01-05 20:43
Sorry, the code that is actually breaking is the following:

```julia
using Plots
gr(c=:bluesreds)
pyplot()

θs = 0.0:0.06346651825433926:6.283185307179586
rs = [0.845692, 0.500665, 0.764702, 0.851246, 0.757517, 1.63206, 1.5355, 1.22237, 0.96965, 1.03994, 0.96533, 0.671565, 0.703021, 0.833558, 0.780069, 0.863198, 0.794035, 0.596641, 0.566495, 0.553401, 0.675192, 1.95, 1.36911, 0.537583, 1.3791, 1.18953, 1.06021, 0.666625, 0.714839, 0.758672, 1.01693, 1.45931, 1.78294, 1.71191, 1.57319, 1.16309, 1.13252, 0.900187, 1.51493, 1.39752, 1.38462, 1.93691, 1.00486, 0.906562, 0.891647, 0.843715, 0.795713, 0.66663, 0.805081, 0.845692]

plot(θs, rs)
```

**Comment by mkborregaard** [comment] 2019-01-06 07:10
That's so weird.

**Comment by mkborregaard** [comment] 2019-01-06 07:11
What about
```
using Plots
gr()
pyplot(c=:bluesreds)
```
?

**Comment by mkborregaard** [comment] 2019-04-04 06:32
This is a duplicate of #1834 . Closing in favour

**Closed by mkborregaard** 2019-04-04 06:32 UTC
