### ISSUE TITLE
Plots v1.34.1 - Cannot Precompile in new project environment

### ISSUE THREAD

**Issue by paschermayr** [JuliaPlots/Plots.jl#4375] opened 2022-09-26 14:49 UTC
Hi there, 

1. I am unable to precompile Plots.jl on Windows-Julia 1.7.3 in a new project environment with only Plots.jl installed.

```
      Status `XXXX\projects\TestProject\Project.toml`
  [91a5bcdd] Plots v1.34.1
```

Error Message when trying to use Plots.jl:

```
GKS: cairoplugin.dll: can't load library, error 126 (0x7e)
ERROR: LoadError: SystemError: opening file "XXXX\\AppData\\Local\\Temp\\jl_g5Ue4As5MP.png": No such file or directory
Stacktrace:
  [1] systemerror(p::String, errno::Int32; extrainfo::Nothing)
```

I tried to solve this via `Pkg.build("GR")` from previous suggestions, but it did not help either.

2. Actually, I wanted to submit another issue for Plots `v1.34.0`, where the ylabel could no longer be chosen as a symbol, but the package was updated so fast I did not manage to submit. Would this work in Plots `v1.34.1`?:

```
using Plots
plot(1,2; ylabel = :test)
```

Best regards, 
Patrick

**Comment by t-bltg** [comment] 2022-09-26 16:02
@jheinen, even though `GR@master` suite is green for `windows`, this does sound related to the GR changes we did in `0.68 - 0.69`.

Since I'm not a windows user, do you have a hint ?

**Comment by paschermayr** [comment] 2022-09-27 06:38
> No, do you know which Plots version supported this, if any ?

Yes, 1.33.0 and below should support this. I do not know when this was introduced, but I used symbols as labels in my code for at least a year now.

> @paschermayr, does pinning Plots@1.34.0 work ?

Yes, then I can use Plots again. However, using a symbol for labels does not work here anymore as before (version 1.33.0 and below). In a fresh environment:

```
Pkg.pin(name="Plots", version="1.34.0")
using Plots

plot(1,2) #working
plot(1,2; ylabel = :testing) #not working

MethodError: no method matching iterate(::Symbol)
Closest candidates are:
  iterate(!Matched::Union{LinRange, StepRangeLen}) at C:\Users\Pasch\AppData\Local\Programs\Julia-1.7.3\share\julia\base\range.jl:826
  iterate(!Matched::Union{LinRange, StepRangeLen}, !Matched::Integer) at C:\Users\Pasch\AppData\Local\Programs\Julia-1.7.3\share\julia\base\range.jl:826
  iterate(!Matched::T) where T<:Union{Base.KeySet{<:Any, <:Dict}, Base.ValueIterator{<:Dict}} at C:\Users\Pasch\AppData\Local\Programs\Julia-1.7.3\share\julia\base\dict.jl:695
  ...
```

**Comment by t-bltg** [comment] 2022-09-27 07:24
Thanks for narrowing the version. @paschermayr, I've remember having introduced this in a recent PR. This is fixed by https://github.com/JuliaPlots/Plots.jl/pull/4383/files and now covered in tests.

**Comment by jheinen** [comment] 2022-09-27 07:25
[f981497](https://github.com/jheinen/GR.jl/commit/f981497f5c5bc5d641ff427d5adb0b472dd05a97) should fix this problem.

**Comment by t-bltg** [comment] 2022-09-27 08:27
The offending version is blacklisted (`] rm Plots` and `] add Plots` should install `1.34.0` instead of `1.34.1`), and the `label` issue is fixed, so I'm closing this (a new `Plots` version should be released soon).

**Comment by ElOceanografo** [comment] 2022-09-27 21:43
I just ran into a similar problem after adding Plots (v1.34.3) to a fresh environment on Windows 10, with Julia 1.8.1. Getting 

```
GKS: svgplugin.dll: can't load library, error 126 (0x7e)
Error showing value of type Plots.Plot{Plots.GRBackend}:
[...]
```
This only happens when trying to plot in VSCode...plots from a plain Julia REPL show up fine. 

Plotting works again after downgrading to v1.34.2.

**Comment by t-bltg** [comment] 2022-09-27 21:59
Ping @jheinen.

**Comment by jheinen** [comment] 2022-09-28 01:28
> I just ran into a similar problem after adding Plots (v1.34.3) to a fresh environment on Windows 10, with Julia 1.8.1. Getting

@ElOceanografo : Could you please try whether `GR#master` fixes the problem?

**Comment by jheinen** [comment] 2022-09-28 02:29
@t-bltg : I improved the initialisation stuff in https://github.com/jheinen/GR.jl/commit/2aad3c1b8a1e988bde00d90bd26899dd92eb5f7a to ensure, that the library paths are **always** set and modified only **once**. If this works on Windows (for @ElOceanografo) using `VSCode` (or in a browser), I'd tag a new version.

**Comment by t-bltg** [comment] 2022-09-28 09:08
Thanks for working on this. I've ran the Plots test suite locally, with `GR@master` and there is no regression on `linux`. I've opened up a dummy PR in https://github.com/JuliaPlots/Plots.jl/pull/4389 to check if there are regressions on `windows` by dev'ing `GR@master` in CI.

> I'd tag a new version.

`0.69.2` would be great so we don't have to tag a new `Plots` version.

**Comment by t-bltg** [comment] 2022-09-28 09:30
@jheinen, it is still broken on `windows` (see https://github.com/JuliaPlots/Plots.jl/actions/runs/3142231116/jobs/5105587393).

For testing, I'd suggest to make GR changes in master and re-run CI here by clicking (maybe `Cancel workflow` first) `Re-run jobs` -> `Re-run failed jobs` in the top right corner in https://github.com/JuliaPlots/Plots.jl/actions/runs/3142231116, since you have write access on this repo.

**Comment by jheinen** [comment] 2022-09-28 11:53
We only test our own (self-contained) binaries, and they all work as expected (include visual regression tests).

@ElOceanografo : Die you have a chance to test GR#master using VSCode? I can't understand why it should not work.

>The PATH modification approach in the main process seems very brittle, ...

Yes, I don't like such constructs either. But, since BinaryBuilder provides each dependency in its own directory structure, I don't know how to get around that. Under Windows required DLLs have to be in the search path.

@t-bltg : can make more tests tomorrow.

**Comment by t-bltg** [comment] 2022-09-28 12:22
The `macOS` error was unrelated to GR and was fixed by https://github.com/JuliaPackaging/Yggdrasil/pull/5590 (see https://github.com/JuliaPlots/Plots.jl/issues/4390).

**Comment by ElOceanografo** [comment] 2022-09-29 00:45
I have not had a chance to check with GR#master, and unfortunately won't for a few days. Will try it next week if you haven't confirmed the fix works by then!

**Comment by simonbyrne** [comment] 2022-09-29 05:02
I'm getting a similar error when precompiling using the Julia Windows buildkite agents. You can see the full log here:
https://buildkite.com/julialang/buildkiteutils-dot-jl/builds/47#0183878e-d967-4772-bdfe-b774c0586051/145-463

**Comment by simonbyrne** [comment] 2022-09-29 05:04
If you want to test something out, feel free to open a PR on the repo: https://github.com/JuliaCI/BuildkiteUtils.jl

**Comment by t-bltg** [comment] 2022-09-29 09:55
The log reported by @simonbyrne shows that even without `vscode`, `GR@0.69` affects `win` users :cry:.

@jheinen is trying hard to fix this asap, sorry for the inconvenience.

**Comment by t-bltg** [comment] 2022-09-29 12:00
@jheinen, I'm going to revert to `GR@0.68`.
This affects lots of users https://discourse.julialang.org/t/vs-code-1-7-1-2-and-plots-jl-not-working/87960.

**Comment by t-bltg** [comment] 2022-09-29 12:21
> All the code around loading libraries is way too complicated

I concur.

> Anyway, on my virtual Windows desktop everything looks OK now.

I've rerun the checks in https://github.com/JuliaPlots/Plots.jl/pull/4389.
I won't release a new `Plots` version unless anyone on `windows` + `vscode` can confirm that `GR#master` works flawlessly.

**Comment by BeastyBlacksmith** [comment] 2022-09-29 14:53
I can check on a windows machine, but not before Tuesday

**Comment by jheinen** [comment] 2022-09-29 17:18
As GR now seems to work fine in a Windows REPL environment (including `savefig` output), I tried to install `VSCode Insiders` in my Parallels Windows VM - unfortunately `VSCode` crashes directly after startup due to missing GPU hardware. I have no access to any bare-metal Windows hardware and can't help with VSCode testing.

**Comment by t-bltg** [comment] 2022-09-29 17:23
> unfortunately VSCode crashes directly after startup due to missing GPU hardware

I use `$ code --disable-gpu` on linux (well known that vscode has issues with gpu acceleration).

**Comment by jheinen** [comment] 2022-09-30 07:39
I can confirm that `Plots` with `GR#master` work on Windows + VSCode. The plot is correctly displayed and `savefig` produces valid SVG, PNG and PDF files.

Will tag a new GR version soon.

**Comment by t-bltg** [comment] 2022-09-30 07:42
Awesome, I will then tag Plots `1.35.0` so we have a fallback version to `1.34.4` on `GR@0.68`.

**Comment by t-bltg** [comment] 2022-09-30 08:25
@jheinen, unfortunately the run against `GR@0.69.2` fails again on windows: https://github.com/JuliaPlots/Plots.jl/actions/runs/3157129500/jobs/5137787762, with similar error messages.

**Comment by jheinen** [comment] 2022-09-30 08:59
I just ran the tests on a Windows 10 system (Parallels VM) using Julia 1.8.1, Plots v1.34.3 and GR v0.69.2 : only 1 `GR - reference images` test failed (Test 50: 3D surface with axis guides, diff ~ 1.38e-5).

I have no idea, why it fails in the CI system.

**Comment by t-bltg** [comment] 2022-09-30 09:01
Thanks. I prefer to delay a new Plots release until we know further.
If it fails once in ci in can happen again, and users will complain.

**Comment by jheinen** [comment] 2022-09-30 09:29
BTW: According to discussions in user forums there seems to be a limit for the maximum length of the `PATH` (4095 bytes) on Windows. I could imagine using the BinaryBuilder `libpath` exceeds this limit.

**Comment by t-bltg** [comment] 2022-09-30 10:50
@jheinen, is there any environment variable I can set to debug (increase verbosity of) low level `sciapp/gr` ?

**Comment by t-bltg** [comment] 2022-09-30 11:30
https://github.com/JuliaLang/julia/issues/46989

**Comment by jheinen** [comment] 2022-09-30 13:24
> @jheinen, is there any environment variable I can set to debug (increase verbosity of) low level `sciapp/gr` ?

Unfortunately no. But I put it on my TODO list, because with low-level debug output (both in GR and GKS) the analysis of the problems with the BinaryBuilder artifacts would certainly become easier.

**Closed** 2022-10-01 08:26 UTC
Labels: bug, load / precompilation, regression, windows

**Comment by t-bltg** [comment] 2022-10-01 08:28
I'm going to release `1.35.0` with `GR@0.69` and drop a message in the discourse recent issues on `windoze`.
