### ISSUE TITLE
[BUG] Making sure label display is predictable

### ISSUE THREAD

**Issue by bkamins** [JuliaPlots/Plots.jl#4514] opened 2022-11-13 10:39 UTC
It would be great to achieve two goals when passing `xlabel`, `title`, etc. kwargs:
* that all backends display the passed values in the same way
* if this is not possible to be able to signal to treat the passed value "verbatim" (without any post-processing on plotting backend side e.g. interpreting it as LaTeX or pseudo-LaTeX)

For example to set `$` as `xaxis` you need to do with GR backend `plot(1:10, xlabel="\$\$")`, but this is GR specific.

x-ref https://github.com/JuliaPlots/Plots.jl/issues/3991 for a specific case
x-ref https://github.com/JuliaPlots/Plots.jl/issues/3122

---

Why does it start to matter currently. The reason is that with addition of metadata support to tables I (and maybe other people) start to generate things like `xlabel`, `title` etc. programmatically (getting the required strings from metadata and this metadata is read-in along with the data to be displayed e.g. from a Parquet file) and then automatically generate e.g. a report. In such pipelines the string to be displayed does not even show up in the source code. The problem is that you need to be sure that what you try to display actually gets displayed.

**Comment by t-bltg** [comment] 2022-11-13 10:45
My opinion on this is that we need unification of preprocessing strings so that this cannot error out.
After all, you should be able to switch backends without modifying your input data / commands.

This seems to be `GR` specific, so maybe just a `GR` setting to toggle:

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x  |     |
pyplot       |     |  x  |
plotlyjs     |     |  x  |
pgfplotsx    |     |  x  |
unicodeplots |     |  x  |
inspectdr    |     |  x  |
gaston       |     |  x  |

cc @jheinen.

**Comment by t-bltg** [comment] 2022-11-13 10:59
In https://github.com/JuliaPlots/Plots.jl/blob/master/src/backends/gr.jl#L257-L263:
```
julia> GR.textext(..., "\$")  # produces a '$' char, but also "ERROR: syntax error"
julia> GR.text(..., "\$")  # no character appears, and "ERROR: syntax error" shown
```

**Comment by t-bltg** [comment] 2022-11-13 12:12
I don't understand https://github.com/JuliaPlots/Plots.jl/commit/19b70c06ff49e5cc3470679ab2acd8da5c669961: shouldn't `match(...) === nothing` be negated ?

**Comment by bkamins** [comment] 2022-11-13 14:22
I think the intention is to return `false` if `$` is present there (as then it is math not normal), but @jheinen will know best (I do not know the logic of this code at all)

**Comment by t-bltg** [comment] 2022-11-13 14:30
This is a bit obscure, a bit more clearer in https://github.com/JuliaPlots/Plots.jl/pull/4515.

But @jheinen comments on this are welcome.

**Comment by BeastyBlacksmith** [comment] 2022-11-14 08:40
They way I think this should work (and that is how it is implemented in the pgfplotsx-backend) is that if you pass a plain string, you should get the characters displayed that are in the string and if you want LaTeX-like strings you need to pass `LaTeXString`s.

So the processing in the gr-backend would need to substitute every `$` with `\$\$` in order to achieve that. The issue is, that we can't do that (unconditionally) prior to 2.0 because that would break everyones code that currently  uses e.g. `xlabel = "a $\LaTeX$ variable"`.

**Comment by t-bltg** [comment] 2022-11-14 08:52
Can't at least `GR` do something like trivial count the numbers of `$`, and not choke if they're odd ?

Why are people keeping up with the archaic `$ ... $` `TeX` syntax and not moving with the `\(x = 1\)` `LaTeX` syntax ?

At least that would be easy to parse and more error proof.

**Comment by jheinen** [comment] 2022-11-14 09:15
The "archaic" `$ ... $` has its origin in LaTeX. So you prefer `\( ... \)`? To be honest, this is the first time I've seen this syntax.

**Comment by t-bltg** [comment] 2022-11-14 09:37
According to https://tex.stackexchange.com/a/513/75098, no.

And no it's pretty common: https://fr.overleaf.com/learn/latex/Mathematical_expressions (`LaTeX` is 30 years old).

In our context where parsing occurs (and obviously because it chokes on a singleton `$`), and also because `$` denotes interpolation syntax in `julia`, it would in my opinion make sense to use `\(...\)` instead of `$...$`.

Side note: I'm not talking about display math mode `\[...\]` vs `$$...$$`, which makes no sense in this context.

**Comment by jheinen** [comment] 2022-11-15 04:22
Thanks for the clarification. I will have to change things in the GR tun-time, too. It's not just about `GR.jl`.

**Comment by jheinen** [comment] 2022-11-16 08:34
The above mentioned problems are fixed in the GR run-time development tree. A new release is expected soon.

It's now possible to use the LaTeX math text syntax (`\(...\)`) and the old TeX Syntax (`$..$`). I could not remove the latter as it would break things for C/C++ and Python users. But the parser now does the trivial Python check (odd number of `$`).

However, in `Plots.jl` we could conditionally use the `GR.textx()` and `GR.inqtextx()` functions which provide a bit mask argument to explicitly set text options:

- TEXT_USE_WC - interpret the text position as world coordinates
- TEXT_ENABLE_INLINE_MATH - enable inline math text

**Comment by t-bltg** [comment] 2022-11-27 11:57
Fixed by https://github.com/sciapp/gr/commit/f37dfaaf67ce7512a2ceb2d8d88c64465c4fca35.

**Closed by t-bltg** 2022-11-27 11:57 UTC
Labels: bug, GR
