### ISSUE TITLE
Replace Formatting.jl by Format.jl[FR]

### ISSUE THREAD

**Issue by caesquerre** [JuliaPlots/Plots.jl#4896] opened 2024-02-27 13:24 UTC
I got a deprecation notice for Formatting.jl suggesting to change to Format.jl.
 
┌ Formatting
│  ┌ Warning: DEPRECATION NOTICE
│  │ 
│  │ Formatting.jl has been unmaintained for a while, with some serious
│  │ correctness bugs compromising the original purpose of the package. As a result,
│  │ it has been deprecated - consider using an alternative, such as
│  │ `Format.jl` (https://github.com/JuliaString/Format.jl) or the `Printf` stdlib directly.
│  │ 
│  │ If you are not using Formatting.jl as a direct dependency, please consider
│  │ opening an issue on any packages you are using that do use it as a dependency.
│  │ From Julia 1.9 onwards, you can query `]why Formatting` to figure out which
│  │ package originally brings it in as a dependency.
│  └ @ Formatting C:\Users\carlos.esquerre\.julia\packages\Formatting\3VxOt\src\Formatting.jl:12
└

(Julia) pkg> why Formatting
  Plots → Latexify → Formatting
  Plots → UnitfulLatexify → Latexify → Formatting

**Comment by t-bltg** [comment] 2024-02-27 13:45
Duplicate of https://github.com/korsbo/Latexify.jl/issues/283.

**Closed** 2024-02-27 13:45 UTC
