### ISSUE TITLE
animation problem in glvisualize

### ISSUE THREAD

**Issue by philschrad** [JuliaPlots/Plots.jl#1097] opened 2017-09-20 00:24 UTC
I'm trying to animate a 3d plot of a spiral in a Jupyter notebook
```
using Plots, ImageMagick
ts=linspace(0,4π,100)
x=map(sin,ts)
y=map(cos,ts)
z=ts/10

@gif for i=2:100
    plot(x[1:i],y[1:i],z[1:i],w=4, xlim=(-3,3),ylims=(-3,3),zlims=(-3,3))
end every 10
```

but getting an error:

```
WARNING: Tried to create gif using convert (ImageMagick), but got error: could not spawn `convert -delay 5 -loop 0 '/var/folders/_m/mj2wmfys5hq16vwy3pv6c3ym0000gn/T/tmpiS1rW6/*.png' -alpha off '/Users/phil/Dropbox/teaching/summer school/MATH1011/tmp.gif'`: no such file or directory (ENOENT)
ImageMagick can be installed by executing `Pkg.add("ImageMagick")`.
You may also need to install the imagemagick c++ library through your operating system.
Will try ffmpeg, but it's lower quality...)
could not spawn `ffmpeg -v 0 -framerate 20 -loop 0 -i /var/folders/_m/mj2wmfys5hq16vwy3pv6c3ym0000gn/T/tmpiS1rW6/%06d.png -y '/Users/phil/Dropbox/teaching/summer school/MATH1011/tmp.gif'`: no such file or directory (ENOENT)
```

any ideas?

**Comment by philschrad** [comment] 2017-09-22 03:31
fixed using the OSX troubleshooting in the [ImageMagick readme](https://github.com/JuliaIO/ImageMagick.jl/blob/master/README.md):
```
using Homebrew
Homebrew.rm("imagemagick@6")
Homebrew.brew(`prune`)
Pkg.build("ImageMagick")
```

**Comment by daschw** [comment] 2017-09-22 09:28
Great!

**Comment by philschrad** [comment] 2017-09-26 02:16
Unfortunately the problem returns after changing backend to glvisualise:
```
WARNING: ColorTypes.U8 is deprecated, use FixedPointNumbers.Normed{UInt8, 8} instead.
  likely near In[5]:6
WARNING: ColorTypes.U8 is deprecated, use FixedPointNumbers.Normed{UInt8, 8} instead.
  likely near In[5]:6
convert: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/509.
convert: no images defined `/Users/phil/Dropbox/teaching/summer_school/MATH1011/helix.gif' @ error/convert.c/ConvertImageCommand/3275.
WARNING: Tried to create gif using convert (ImageMagick), but got error: ErrorException("failed process: Process(`convert -delay 5 -loop 0 '/var/folders/_m/mj2wmfys5hq16vwy3pv6c3ym0000gn/T/tmpwDhiLP/*.png' -alpha off /Users/phil/Dropbox/teaching/summer_school/MATH1011/helix.gif`, ProcessExited(1)) [1]")
ImageMagick can be installed by executing `Pkg.add("ImageMagick")`.
You may also need to install the imagemagick c++ library through your operating system.
Will try ffmpeg, but it's lower quality...)
could not spawn `ffmpeg -v 0 -framerate 20 -loop 0 -i /var/folders/_m/mj2wmfys5hq16vwy3pv6c3ym0000gn/T/tmpwDhiLP/%06d.png -y /Users/phil/Dropbox/teaching/summer_school/MATH1011/helix.gif`: no such file or directory (ENOENT)
```
Can be fixed by the previous method, but it would be nice to be able to use glvisualise!

**Comment by mkborregaard** [comment] 2017-09-26 04:24
Yeah, I don't think animations work in GLVisualize, nor is that on the immediate horizon.

**Comment by SimonDanisch** [comment] 2017-09-26 08:07
>Yeah, I don't think animations work in GLVisualize, nor is that on the immediate horizon.

I don't know what you mean, it should just work like with the other backends.
The error seems to be completely unrelated to glvisualize, no?

**Comment by mkborregaard** [comment] 2017-09-26 09:02
Oh, sorry :flushed:. I think we never had the animations working on the tests, but I should have tried to reproduce.

**Comment by mkborregaard** [comment] 2017-09-26 09:03
This seems in fact to be the infamous Mac-ImageMagick issue.

**Comment by daschw** [comment] 2019-07-10 07:51
Closing as GLVisualize is no longer supported.

**Closed by daschw** 2019-07-10 07:51 UTC
Labels: GLVisualize, enhancement
