### ISSUE TITLE
Differences in canvas size using Plots vs. PlotlyJS

### ISSUE THREAD

**Issue by kylecarbon** [JuliaPlots/Plots.jl#1722] opened 2018-09-05 06:40 UTC
Hi again! Not sure where this issue actually falls but figured I'd start here. Plotting with `PlotlyJS`, my entire window/canvas is taken up by default. I can re-size the window and it resizes the plot. When I call `using Plots; plotlyjs()`, regardless of the window/canvas size, the plot itself always stays the same size. Any ideas what's going on here?

`using PlotlyJS`
![image](https://user-images.githubusercontent.com/24921149/45075254-62466480-b09b-11e8-9c2c-18dbe0ed06a0.png)

`using Plots; plotlyjs()`
![image](https://user-images.githubusercontent.com/24921149/45075217-3dea8800-b09b-11e8-9fa7-1aa8214033b6.png)

**Comment by kylecarbon** [comment] 2018-09-05 07:00
Per https://github.com/JuliaPlots/Plots.jl/issues/1721#issuecomment-418618770, I will check back after @daschw's PR is merged.

**Comment by mkborregaard** [comment] 2018-09-05 07:13
This is most likely a duplicate of https://github.com/JuliaPlots/Plots.jl/issues/1074

**Comment by mkborregaard** [comment] 2018-09-05 07:15
@kylecarbon could you post on that issue instead to let us keep things together?

**Closed by mkborregaard** 2018-09-05 07:15 UTC

**Comment by kylecarbon** [comment] 2018-09-05 13:48
Yes, absolutely! Just wasn't sure if you preferred issues grouped together or separate so that you could close them out 1-by-1. I suppose in the future, I'll lump all my issues together, then based on what you find, you can break things down? But yes, agreed, a duplicate of #1074.

**Comment by mkborregaard** [comment] 2018-09-06 06:09
We tend to prefer them separate :-) It's just that I think it might be the same issue.
