### ISSUE TITLE
[BUG]`markerstrokealpha` not work in `scatter` with `GR` backend

### ISSUE THREAD

**Issue by lihua-cat** [JuliaPlots/Plots.jl#3658] opened 2021-07-21 13:25 UTC
## Details
```juliadoc
julia> using Plots
julia> scatter(rand(10, 2), markerstrokealpha=[1 0], label=["1" "0"], legendtitle = "stroke alpha")
```
![image](https://user-images.githubusercontent.com/42488653/126495239-b52317c6-785a-4051-8e23-9277bf508abd.png)
switch to `plotly` backend, it seems ok
![newplot](https://user-images.githubusercontent.com/42488653/126495523-ded60e16-50fa-4f45-b8e9-fab91f44503c.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x  |     |
pyplot       |     |     |
plotly       |     |  x  |
plotlyjs     |     |     |
pgfplotsx    |     |     |
inspectdr    |     |     |

### Versions

Plots.jl version: v1.19.3
Backend  version (`]st -m <backend(s)>`): v0.58.0
Output of `versioninfo()`:
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

**Comment by BeastyBlacksmith** [comment] 2021-07-21 14:46
duplicate of https://github.com/JuliaPlots/Plots.jl/issues/2494

**Comment by t-bltg** [comment] 2021-07-29 13:42
What about using:

```julia
using Plots

scatter(rand(10, 2), markerstrokewidth=[1 0], label=["1" "0"], legendtitle="stroke alpha")
png("foo")
```
?

![mks](https://user-images.githubusercontent.com/13423344/127502605-04c22186-2565-4c44-91e7-6554a13f3bd7.png)

**Closed** 2022-11-20 14:50 UTC
Labels: bug, duplicate, GR
