### ISSUE TITLE
Problem with Color Bar and Bar Plot [BUG]

### ISSUE THREAD

**Issue by Dsantra92** [JuliaPlots/Plots.jl#2887] opened 2020-08-03 14:55 UTC
## Details
I would like to mention 2 bugs.

1.**Using `bar()` trims out  the first and the last characters of the label string.**
```julia
x = ["car", "bike", "bus", "truck", "bicycle"]
y = [10, 5, 8, 4, 2]
bar(x, y,leg =false) 
```
The label outputs are trimmed as "a", "ik","u" and so on.

2.**Colorbar in `heatmap()`,`surface()`,`contour()` etc**
```julia
X = [(1/(x+y)) for x in 1:5 ,y in 1:7]
heatmap(X,colorbar = :true)
```

The values along color-bar values are cropped out.Sometimes it shows just a decimal or a number after the decimal not the full number

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     |
pyplot       |     |     |
plotly       |  x   |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
inspectdr    |     |     |

### Versions

Plots.jl version: 1.5.7

Backend  version (`]st -m`): 2.9.0

Output of `versioninfo()`:

Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, znver1)

Environment : Jupyter Notebook and Google Colab ,IJulia version 1.21.2

**Comment by daschw** [comment] 2020-08-03 16:42
I can't reproduce with plotly:
```julia
x = ["car", "bike", "bus", "truck", "bicycle"]
y = [10, 5, 8, 4, 2]
bar(x, y,leg =false) 
```
![plotly_bar](https://user-images.githubusercontent.com/16589944/89206067-ff2c1800-d5b8-11ea-99ac-a4c22308acf9.png)

```julia
X = [(1/(x+y)) for x in 1:5 ,y in 1:7]
heatmap(X,colorbar = :true)
```
![plotly_heatmap](https://user-images.githubusercontent.com/16589944/89206084-0521f900-d5b9-11ea-8972-59753f08d677.png)

**Comment by Dsantra92** [comment] 2020-08-03 18:13
I thought it might be a problem with my own machine so I confirmed it using Julia 1.4.2 on Colab. But results are similar to my local machine.Any thoughts?
![color_bar](https://user-images.githubusercontent.com/55111154/89213710-1e3f9f80-d5e3-11ea-85a6-7707665c7464.png)

**Comment by BeastyBlacksmith** [comment] 2020-08-03 19:38
@daschw did you run in a notebook?

**Comment by daschw** [comment] 2020-08-03 21:03
Yes, I also checked in a notebook.

**Comment by daschw** [comment] 2020-08-03 21:03
I tested on Julia 1.5 though.

**Comment by daschw** [comment] 2020-08-04 09:50
No, sorry, my mistake, I tried to test on IJulia, but my set-up was messed up. I tested it now and can confirm the issue @Dsantra92 describes.

**Closed** 2021-12-01 12:45 UTC
Labels: bug, Plotly, IJulia
