### ISSUE TITLE
deprecation warning from matplotlib

### ISSUE THREAD

**Issue by lewisl** [JuliaPlots/Plots.jl#2954] opened 2020-09-04 19:25 UTC
## Details
The following deprecation warnings are generated when plotting with plots to matplotlib:

```
sys:1: MatplotlibDeprecationWarning: Passing the fontdict parameter of _set_ticklabels() positionally is deprecated since Matplotlib 3.3; the parameter will become keyword-only two minor releases later.
sys:1: UserWarning: FixedFormatter should only be used together with FixedLocator
sys:1: MatplotlibDeprecationWarning: Case-insensitive properties were deprecated in 3.3 and support will be removed two minor releases later
```

Whatever is passed to matplotlib, whether via PyPlot or through plots code, is hidden from me. The question is whether I can use arguments in my plots commands to fix this or if this must be changed in an update of Plots.

for now, the plots look as they ought.

Thanks,
Lewis

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     |
pyplot       | x    |     |
plotly       |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
inspectdr    |     |     |

### Versions

Plots.jl version: 1.6.3
Backend  version (`]st -m`): matplotlib 3.3.1
Output of `versioninfo()`:
```Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)```

**Comment by jolars** [comment] 2020-09-07 09:36
Seems to be a duplicate of https://github.com/JuliaPlots/Plots.jl/issues/2874.

**Closed** 2020-09-09 02:43 UTC
Labels: bug
