### ISSUE TITLE
[BUG] documentation link broken?

### ISSUE THREAD

**Issue by jamblejoe** [JuliaPlots/Plots.jl#4038] opened 2022-01-14 21:18 UTC
Is the documentation link broken? I get 404 errors on https://docs.juliaplots.org/stable/.

**Comment by t-bltg** [comment] 2022-01-17 12:41
Duplicate of https://github.com/JuliaPlots/PlotDocs.jl/issues/267, which was fixed by @BeastyBlacksmith (docs are up again).

**Closed by t-bltg** 2022-01-17 12:41 UTC
Labels: bug
