### ISSUE TITLE
warning GKS: invalid bitmap size  on heatmap when @animate

### ISSUE THREAD

**Issue by atthom** [JuliaPlots/Plots.jl#2066] opened 2019-06-16 22:19 UTC
Hi, 
I'm fairly new to Plots.jl
I needed to animate a heatmap and found a very straight forward way of doing it, thanks to the documentation.
```
anim = @animate for i=1:100
     heatmap(rand(50, 50))
end
```

However, when running this code it keeps returning with this warning:
```
GKS: invalid bitmap size
```
But still, it builds the animation.
I don't have this warning if I run only the plotting part:
```
heatmap(rand(50, 50))
```

What should I do to avoid this warning?
Does it affect the performance of the plotting?

**Comment by daschw** [comment] 2019-06-30 11:21
@jheinen is this the same issue you discussed with Júlio Hoffimann on slack? Is this fixed with the latest version of GR?

**Comment by jheinen** [comment] 2019-07-01 07:25
No, that's sth different. The pure GR code works:

```julia
using GR
ENV["GKSwstype"]="mov"
for i=1:100
     heatmap(rand(50, 50))
end
```

**Comment by daschw** [comment] 2019-07-01 10:55
I also get this with `heatmap(rand(50, 50))` without `@animate`

**Comment by jheinen** [comment] 2019-07-01 11:16
The problem is fixed [here](https://github.com/sciapp/gr/commit/dd4fc59de3b45b7a8302ff4444f15181b30c285c).

.

**Comment by daschw** [comment] 2019-07-01 11:16
Awesome!

**Closed** 2021-09-25 19:25 UTC
