### ISSUE TITLE
Atom + PlotlyJS, resize first plot in plot pane

### ISSUE THREAD

**Issue by rveltz** [JuliaPlots/Plots.jl#1226] opened 2017-11-06 08:24 UTC
Dear great developpers,

I am using PlotlyJS through Plots for the interactivity. On MacOS, the first plot in Atom-Juno with `plotlyjs` backend is not at the size of the plot pane. Only then, when using the mouse, you modify the dimension of the plot pane and the (plotlyjs) plot re-adjust to the correct size.

Is there a way to get it right for the first plot directly?

Thank you a lot for your help,

Best regards

**Comment by mkborregaard** [comment] 2017-11-06 08:47
This is a current bug - there's already an open issue for it at https://github.com/JuliaPlots/Plots.jl/issues/1074, so I'll close this if that's OK.

**Closed by mkborregaard** 2017-11-06 08:47 UTC

**Comment by mkborregaard** [comment] 2017-11-06 08:49
The problem is that the Plot's `size` attribute overrides the size of the window at the first plot. The fix will be to make Plotly ignore the size attribute when there's already an open window.
