### ISSUE TITLE
GR: legend text out of legend box bounds if legend placed in an "outer" position

### ISSUE THREAD

**Issue by nbsmokee** [JuliaPlots/Plots.jl#2658] opened 2020-05-01 13:50 UTC
## Details
I noticed that, using the GR backend, whenever i place the legend in the outer area of the figure (i.e. :outertopright, outerbottomright etc.) AND at the same time have my axes labelled, the font size of the legend text is larger than normal without the legend box size being porperly adjusted, causing the legend text to stick out of the box.
all good without axes labels:
`scatter(rand(100), label = "some label", legend = :outertopright)`
but after adding axes labels (notice larger legend font size):
`scatter(rand(100), xlabel = "x", ylabel = "y", label = "some label", legend = :outertopright)`
interestingly, after moving the legend inside the plot area:
`scatter(rand(100), xlabel = "x", ylabel = "y", label = "some label", legend = :topright)`

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |  x   |
plotly       |     |  x   |
plotlyjs     |     |  x   |
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: 1.2.0
Backend  version: 0.48.0
Output of `versioninfo()`:
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "D:\Program Files\Work\atom\app-1.45.0\atom.exe"  -a
  JULIA_NUM_THREADS = 4

**Comment by AhmedSalih3d** [comment] 2020-10-03 18:48
Did it happen again?

![image](https://user-images.githubusercontent.com/36305327/94999459-d96fbf00-05b9-11eb-8cf2-76a917a8bde9.png)

**Comment by daschw** [comment] 2020-10-03 21:35
@AhmedSalih3d thanks for reporting! Could you provide the code to reproduce the issue?

**Comment by AhmedSalih3d** [comment] 2020-10-03 21:43
Hello!

It was quite a peculiar problem since it would only occure in some cases. Say I used the same strings as I just showed you but did "plot(rand(50))" I was not able to reproduce the problem. Here is the code I used:

`
using Plots
gr()
p1 = plot(legend=:outerbottom,foreground_color_legend = nothing,background_color_legend = nothing)
    plot!(x,label="Kinetic Energy Left of Plate")
    plot!(y,label="Kinetic Energy Right of Plate")
    xlabel!("Time [s]")
    ylabel!("Energy [W]")
    title!("Kinetic Energy")`

**Comment by AhmedSalih3d** [comment] 2020-10-03 21:47
Woops, my formatting is wrong and of course remove "foreground_color_legend" and same for background option. 

Example here
![image](https://user-images.githubusercontent.com/36305327/95002320-c3222d00-05d2-11eb-8572-72050c20596f.png)

**Comment by daschw** [comment] 2020-10-03 21:50
Thanks!

**Comment by t-bltg** [comment] 2022-11-20 12:14
Fixed by https://github.com/JuliaPlots/Plots.jl/pull/4496.

**Closed by t-bltg** 2022-11-20 12:14 UTC
Labels: bug, GR

**Comment by AhmedSalih3d** [comment] 2022-11-20 12:28
> Fixed by #4496.

I had forgotten everything about this bug! Nice to see stuff getting fixed, thank you for your work everyone :)

Just wanted to spread a little bit of positivity.

**Comment by t-bltg** [comment] 2022-11-20 12:32
Thanks for your kind words.
Maintaining is a hard task, but eventually things a getting addressed.
