### ISSUE TITLE
[BUG] tiny plots in Pluto notebooks

### ISSUE THREAD

**Issue by hofmannmartin** [JuliaPlots/Plots.jl#3525] opened 2021-06-01 12:52 UTC
## Details

This bug has appeared in the `Pluto` issues https://github.com/fonsp/Pluto.jl/issues/1207, but is likely not caused by Pluto.

If I start a `Pluto` `v0.14.7` notebook with a fresh package environment. I.e. with a single cell of the following content
```julia
begin
	import Pkg
	Pkg.activate(mktempdir())	
	Pkg.add("Plots")
	using Plots
end
```
any plot (e.g. `plot(rand(10))`) will appear extremely small.

In the issue linked above it was found that in this instance an extremely old version `v0.52.0` of `GR` is used. If one installs `GR` directly alongside `Plots`
```julia
begin
	import Pkg
	Pkg.activate(mktempdir())
	
	Pkg.add(["Plots","GR"])
	using Plots
end
```
`GR` version `v0.57.5` is used and all plots appear in normal size.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |     | x
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: `v1.15.2`
Backend  version (`]st -m`): `v0.52.0`
Output of `versioninfo()`: 
```
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

**Comment by BeastyBlacksmith** [comment] 2021-06-01 16:47
duplicate of https://github.com/JuliaPlots/Plots.jl/issues/3198

**Closed** 2021-06-02 06:24 UTC
Labels: GR, bug, duplicate

**Comment by fonsp** [comment] 2021-06-02 22:56
@BeastyBlacksmith I think https://github.com/JuliaPlots/Plots.jl/issues/3192 is also related to plot sizing issues
