### ISSUE TITLE
spy() produces empty plot on pyplot

### ISSUE THREAD

**Issue by AzamatB** [JuliaPlots/Plots.jl#1513] opened 2018-05-09 06:27 UTC
``` Julia
using Plots, LinearAlgebra
gr()
spy(Matrix{Int}(I, 10, 10))
```
produces wrong output, namely image is not aligned with the axes. For comparison run this with `plotly()` backend, which plots this correctly.

Furthermore
``` Julia
using Plots
pyplot()
spy(Matrix{Int}(I, 10, 10))
```
simply plots zero matrix.

**Comment by AzamatB** [comment] 2018-05-09 06:30
``` Julia
julia> versioninfo()
Julia Version 0.6.2
Commit d386e40* (2017-12-13 18:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libmkl_rt
  LAPACK: libmkl_rt
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

julia> Pkg.status("Plots")
 - Plots                         0.17.0

julia> Pkg.status("GR")
 - GR                            0.31.0

julia> Pkg.status("PyPlot")
 - PyPlot                        2.3.2
```

**Comment by mkborregaard** [comment] 2018-05-09 12:59
Here's what I get:
gr:
![skaermbillede 2018-05-09 kl 14 48 13](https://user-images.githubusercontent.com/8429802/39815386-1ab53192-5398-11e8-9b67-2b871a62f9e3.png)

plotly:
![skaermbillede 2018-05-09 kl 14 48 18](https://user-images.githubusercontent.com/8429802/39815390-211f6ab6-5398-11e8-9feb-ca5118e5d769.png)

pyplot:
![skaermbillede 2018-05-09 kl 14 48 26](https://user-images.githubusercontent.com/8429802/39815399-27d9e0f2-5398-11e8-8e59-48a1f1c893c9.png)

So something is clearly amiss with pyplot - I don't see the GR problem though.

**Comment by AzamatB** [comment] 2018-05-09 13:06
@mkborregaard what version of GR are you running? With 0.31 on Atom I get the following:
<img width="365" alt="screen shot 2018-05-09 at 9 03 01 am" src="https://user-images.githubusercontent.com/3909074/39816072-258101da-5368-11e8-91f6-520c705054a5.png">

**Comment by mkborregaard** [comment] 2018-05-09 13:09
Yeah, we've had that before - `yflip` working on GR on most machines but not all. Sometimes different behaviour on the same operating system and version! What's your OS and version?

The GR issue is thus a duplicate of https://github.com/JuliaPlots/Plots.jl/issues/1491

**Comment by AzamatB** [comment] 2018-05-09 13:14
macOS X version 10.13.4

**Comment by mkborregaard** [comment] 2018-05-09 13:52
So am I lol.

**Comment by Paethon** [comment] 2018-06-15 12:48
This issue has been solved in `GR.jl` now with https://github.com/jheinen/GR.jl/commit/b16a5da6fd7bca3855156a3e25a5e7556fd2b91c
(at least for me)
Not sure what has to be done so this fix is also used in `Plots.jl`

**Closed** 2022-11-24 21:09 UTC
Labels: bug, PyPlot
