### ISSUE TITLE
Juno pyplot doesn’t fit ‘Plots’ window

### ISSUE THREAD

**Issue by sergii-bond** [JuliaPlots/Plots.jl#2312] opened 2019-12-07 00:33 UTC
Please see this screenshot. The plot doesn't fit.

![image](https://user-images.githubusercontent.com/19783366/70365155-dfcfc600-1844-11ea-888b-8fe0e406a385.png)

It doesn’t happen if I remove  `pyplot()`  line or replace it with  `plotly()` .
It is not critical now after I learned to use backends other than pyplot. 
However I'd like to point out that the code I used is from the official Juno documentation [here](http://docs.junolab.org/latest/man/basic_usage/#The-Plots.jl-Ecosystem-1).

Atom version 1.41.0 x64 running on MacOS Mojave 10.14.6.

@pfitzseb thank you for your reply about this issue [on discourse](https://discourse.julialang.org/t/juno-pyplot-doesnt-fit-plots-window/31938).
You guess is correct, it has to do with the MacOS scaling. 
![image](https://user-images.githubusercontent.com/19783366/70365374-ed398000-1845-11ea-8ca9-f2da8fe70c12.png)

If I set scale to match the resolution of the monitor (the first choice in the scale list below), the plot fits the window.
![image](https://user-images.githubusercontent.com/19783366/70365384-fb879c00-1845-11ea-9726-f182ebecdd1a.png)

**Comment by daschw** [comment] 2019-12-07 10:23
Duplicate of https://github.com/JuliaPlots/Plots.jl/issues/2297

**Closed by daschw** 2019-12-07 10:23 UTC
