### ISSUE TITLE
GR backend missing GKSTerm.app on macOS Sonoma Version 14.3 (23D56)

### ISSUE THREAD

**Issue by varnerlab** [JuliaPlots/Plots.jl#4879] opened 2024-01-27 16:53 UTC
## Details

1. I installed the Plots package (v1.40.0) into a local project with the package manager from the REPL and closed the REPL.
2. I Started Julia using the --project=. flag and then issued the `using Plots` command. I tried to plot some random numbers using `plot(rand(100))`.
3. It crashed, but sometimes it also just hangs the REPL. The error message says it can't find the GSKTerm app. I'm assuming AAPL moved stuff during the update to 14.3, but I'm not sure. Help? 
4. Other backends, e.g., Pythonplot, work okay (but it's the only one I tested).

See the screenshot for crash details:
<img width="1348" alt="Screenshot 2024-01-27 at 11 33 06 AM" src="https://github.com/JuliaPlots/Plots.jl/assets/14302599/b7474f19-28ac-4b46-b5a8-b597537d46d6">

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pythonplot   |     |   x  |
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
unicodeplots |     |     | x
inspectdr    |     |     | x
gaston       |     |     | x

### Versions

Plots.jl version:
Backend  version (`]st -m <backend(s)>`): GR v0.73.1
Output of `versioninfo()`: 
Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores

**Comment by juliasloan25** [comment] 2024-01-30 02:12
I'm also seeing this on MacOS v12.7.2. I don't get the error when using Plots v1.39.0, so maybe this was introduced in v1.40.0

**Comment by BeastyBlacksmith** [comment] 2024-01-30 08:48
CC @jheinen

**Comment by jheinen** [comment] 2024-01-31 14:40
The problem is fixed in GR 0.73.2

**Closed** 2024-02-02 12:52 UTC
Labels: bug, GR, upstream
