### ISSUE TITLE
Plotly backend: surface(X,Y,Z) has x-axis in wrong direction

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaPlots/Plots.jl#872] opened 2017-05-28 23:36 UTC
```julia
pyplot()
X=linspace(0.,1.,40).*ones(40)'
T=ones(40)*linspace(0.,1.,40)'
Y=T.*(1.-X)
Z = X
surface(X,Y,Z)
```
looks fine, while 
```julia
plotly()
surface(X,Y,Z)
```
has the x-axis in the wrong direction, see attachment.

[Untitled2.pdf](https://github.com/JuliaPlots/Plots.jl/files/1034603/Untitled2.pdf)

**Comment by mkborregaard** [comment] 2017-05-29 05:56
The input args X and Y in Plots are not mesh-grids / matrices; just Vectors. Do you mean something like
```
 X=linspace(0.,1.,40)
Y = X .* (1-X)
Z = X .* ones(40)'
surface(X, Y, Z)
```
?

**Comment by dlfivefifty** [comment] 2017-05-29 05:58
No since the plotting grid is a triangle.

It works fine in PyPlot, as seen in the attachment, so it's clearly not the case that they have to be vectors

**Comment by mkborregaard** [comment] 2017-05-29 06:19
Interesting. AFAIK this is undefined behaviour that just happens to work in pyplot, @tbreloff most likely knows this. If it's a small fix to get it working in plotly too that's definitely worth looking into.

**Comment by dlfivefifty** [comment] 2017-05-29 06:21
@tbreloff added this behaviour after I requested it: https://github.com/JuliaPlots/Plots.jl/issues/96

**Comment by mkborregaard** [comment] 2017-05-29 06:26
Ah! Thanks for pointer, and this "It will likely only work with PyPlot" also explains the current issue. I'll add it to the list of desirable enhancements for the other backends as well.

**Comment by dlfivefifty** [comment] 2017-05-29 06:29
Except it does work in Plotly almost perfectly, which suggests it was added at some point

**Comment by mkborregaard** [comment] 2017-05-29 07:11
Perhaps, I'm not sure. The pyplot functionality was added in https://github.com/JuliaPlots/Plots.jl/commit/ed7cc9b89e6b90c19c187dea108f8c5722804ef8 , it doesn't look awfully complicated.

**Comment by mkborregaard** [comment] 2017-05-29 08:43
Looks like it was added in response to https://github.com/JuliaPlots/Plots.jl/issues/479 , there is a nice example of plotting on a sphere. I guess on a sphere noone'd notice if the x axis was off. I wonder if this is the cause of this issue as well: https://github.com/JuliaPlots/Plots.jl/issues/643

**Comment by mkborregaard** [comment] 2017-05-29 09:11
This turned out to be a very long goose chase. You're just not viewing the planes from the same angle. Using your code:

Your first screenshot
![skaermbillede 2017-05-29 kl 10 53 49](https://cloud.githubusercontent.com/assets/8429802/26543242/7693451c-445d-11e7-8793-7d93751d7fbe.png)
![skaermbillede 2017-05-29 kl 10 53 57](https://cloud.githubusercontent.com/assets/8429802/26543246/7aa6a4e6-445d-11e7-80d9-a466fc78bb4a.png)

Your second screenshot
![skaermbillede 2017-05-29 kl 10 52 59](https://cloud.githubusercontent.com/assets/8429802/26543260/8364d2d8-445d-11e7-8ee9-201104fb2780.png)
![skaermbillede 2017-05-29 kl 10 53 08](https://cloud.githubusercontent.com/assets/8429802/26543267/86e9c2b0-445d-11e7-91d2-2e395446fcea.png)

I've had it with Plots issues for a few days now.

**Comment by mkborregaard** [comment] 2017-05-30 18:43
I have opened a new issue with an appropriate name and am closing this https://github.com/JuliaPlots/Plots.jl/issues/875.

**Closed by mkborregaard** 2017-05-30 18:43 UTC
Labels: enhancement, GR, PGFPlots

**Comment by dlfivefifty** [comment] 2017-06-08 22:50
OK, I think there is an issue here but it's not what I said: it's the plotly is putting the y-coordinate axis in the "wrong" direction:
```julia
x = linspace(-3.,3.,100)
y = linspace(0,3.,101)
surface(x,y,x' .+ y)  # axes are not consistent with gr()
```

**Comment by dlfivefifty** [comment] 2017-06-08 23:08
Ah I'm being stupid: it's just a different vantage point, like you said.
