### ISSUE TITLE
Clipping of plots in GR

### ISSUE THREAD

**Issue by improbable22** [JuliaPlots/Plots.jl#1101] opened 2017-09-21 15:03 UTC
In Jupyter / IJulia, subsequent plots seem to get partially clipped based on the size of the first plot. Here is one demonstration: 
```
using Plots 
plot(rand(20,2), layout=2)  # displays normally 

plot(rand(20)) # right-hand half of line is missing 
```
Here is another:
```
using Plots 
plot(rand(20), size=(200,200)) # displays normally

plot(rand(50)) # line, axes & legend all missing outside 200,200 box
```
(This was split off from #1090 )

**Comment by daschw** [comment] 2017-09-21 15:07
Great, thanks @improbable22!
@jheinen do you have an idea what could be causing this / how this can be fixed?

**Comment by jheinen** [comment] 2017-09-21 17:25
That's what I get - what would you expect?
![screen shot 2017-09-21 at 19 23 12](https://user-images.githubusercontent.com/5718244/30709459-8e1146ee-9f02-11e7-86be-c11fbc15d3fc.png)

**Comment by improbable22** [comment] 2017-09-21 17:40
That's what I'd like, but what I get is this: 

![screen shot 2017-09-21 at 7 37 48 pm](https://user-images.githubusercontent.com/29553230/30710061-99bef6d8-9f04-11e7-9855-6cb28edd36f5.JPG)

**Comment by improbable22** [comment] 2017-09-21 17:53
And this: 

![screen shot 2017-09-21 at 7 48 24 pm](https://user-images.githubusercontent.com/29553230/30710458-ec0855fa-9f05-11e7-9bca-dd1a585f4058.JPG)

**Comment by improbable22** [comment] 2017-09-21 17:59
I just tried these in Safari and don't see the issue there. I also didn't see any problem when I tried this in "nteract". So perhaps the bug is only in Chrome? 

Were @daschw & @juliohm also using Chrome? And also on a mac?

**Comment by juliohm** [comment] 2017-09-21 18:17
I am on Chromium in Linux.

**Comment by mkborregaard** [comment] 2017-09-21 18:47
I have the problem as well, Firefox 55.0.3 on a Mac, MacOS 10.12.6. 
```
julia> Pkg.status.(["Plots", "GR", "IJulia"])
versioninfo()
 - Plots                         0.12.4+            master
 - GR                            0.23.0+            master
 - IJulia                        1.6.1
3-element Array{Void,1}:
 nothing
 nothing
 nothing

julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

**Comment by jheinen** [comment] 2017-09-21 18:52
Strange - I'll check this using Firefox on Linux when I'm back in office (tomorrow) ...

**Comment by jheinen** [comment] 2017-09-21 19:00
Ok - I can reproduce the problem using Firefox on macOS. Still no idea ...

**Comment by mkborregaard** [comment] 2017-09-21 19:10
It's pretty cryptic - I guess it's hard to reproduce in just GR without Plots

**Comment by apalugniok** [comment] 2017-09-21 19:14
Same for me I'm using Chrome (Version 60.0.3112.113) on macOS 10.12.6
```
- Plots                         0.12.4+            master
 - GR                            0.23.0+            master
 - IJulia                        1.6.1

Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```
also happens for me on the current releases of the packages.

One thing I noticed though is if I restart the kernel in IJulia and then run `using Plots; plot(rand(20,2), layout=2)` for the time that first plot isn't displayed the second plot is fine. Also cutting out the first plot fixes the second. So it seems like the issue isn't there as long as the first plot is not being displayed.

**Comment by daschw** [comment] 2017-09-21 19:16
I was using Firefox on Windows 7 earlier today, when I posted the issue in https://github.com/JuliaPlots/Plots.jl/issues/1090#issuecomment-331172081

**Comment by jheinen** [comment] 2017-09-23 12:00
This problem should be fixed in https://github.com/jheinen/gr/commit/70c2e49371084eec38b3ff3ed05851805edf9d2e. It's a workaround to avoid caching problems due to non-unique clip path IDs when rendering SVGs in Firefox or Chrome.

Requires (the master branch) and re-installation of the GR run-time:
```julia
ENV["GRDIR"] = ""
Pkg.build("GR")
```

**Comment by improbable22** [comment] 2017-09-25 09:56
This fixes the issue for me, many thanks! 

On my laptop I could not figure out how to get around this error (in `build` step) but I guess that's an orthogonal problem...
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html 
```

**Comment by mkborregaard** [comment] 2017-09-25 10:07
That's currently being worked on.

**Closed by mkborregaard** 2017-09-25 10:07 UTC
Labels: bug, GR, IJulia
