### ISSUE TITLE
Precompile failed in Julia v1.2

### ISSUE THREAD

**Issue by Hrj9499** [JuliaPlots/Plots.jl#2203] opened 2019-09-26 13:43 UTC
Hi there,

I installed Plots but fails in the precompile process. Other Julia packages works well for me except for this one.

I was given the message below

ERROR: LoadError: Failed to precompile FFMPEG [c87230d0-a227-11e9-1b43-d7ebe4e7570a] to C:\Users\hrj94\.julia\compiled\v1.2\FFMPEG\TGvga.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1253
 [3] _require(::Base.PkgId) at .\loading.jl:1013
 [4] require(::Base.PkgId) at .\loading.jl:911
 [5] require(::Module, ::Symbol) at .\loading.jl:906
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1094
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:432
 [12] top-level scope at .\none:3
in expression starting at C:\Users\hrj94\.julia\packages\Plots\h3o4c\src\Plots.jl:11

Any idea on that? Thanks for helping.

**Comment by daschw** [comment] 2019-09-26 13:56
Duplicate of #2184

**Closed by daschw** 2019-09-26 13:56 UTC
