### ISSUE TITLE
blank figure opened in browser

### ISSUE THREAD

**Issue by genwei007** [JuliaPlots/Plots.jl#609] opened 2016-12-10 08:57 UTC
I think this is not a new issue, but I cannot find out a way to solve it. I used `plot(rand(5),sin)` and a new webpage (called Plots.jl) was opened and nothing displayed. How can I solve it? Thanks!

**Comment by AlexanderKoshkarov** [comment] 2016-12-11 22:58
I do not know about how to fully diagnose you issue, but you probably should start with identifing a backend. https://juliaplots.github.io/backends/

if you just need a graph, probably use different backend, for exmple:
```
>using Plots; pyplot()
>plot(rand(5),sin)
```

**Comment by ChrisRackauckas** [comment] 2016-12-11 23:59
>and a new webpage (called Plots.jl) was opened and nothing displayed. How can I solve it? Thanks!

That probably means it tried to plot something with Plotly, but it wasn't able to display the Plotly output. What web browser?

**Comment by pkofod** [comment] 2018-02-05 19:16
Close this as it seems idle? If the problem isn't fixed in (plotly?) by now, a new issue will reappear.

**Comment by ChrisRackauckas** [comment] 2018-02-05 19:16
Well, it's not actionable so I'll close it.

**Closed by ChrisRackauckas** 2018-02-05 19:16 UTC
