### ISSUE TITLE
Installation in Windows10 doesn't build FFMPEG correctly

### ISSUE THREAD

**Issue by aerdely** [JuliaPlots/Plots.jl#2187] opened 2019-09-14 20:53 UTC
After:

```
import Pkg
Pkg.add("Plots")
Pkg.add("GR")
using Plots
``` 

I get the message:

FFMPEG not installed properly, run `] build FFMPEG`, restart Julia and try again

which I already did, but didn’t work. 

![FFMPEG_error2](https://user-images.githubusercontent.com/3356159/64913549-abe27a00-d707-11e9-9747-6cfe58f13625.png)

**Comment by daschw** [comment] 2019-09-26 13:56
Duplicate of #2184

**Closed by daschw** 2019-09-26 13:56 UTC
