### ISSUE TITLE
PlotlyJS can only plot one time, second plot is blank

### ISSUE THREAD

**Issue by w1res** [JuliaPlots/Plots.jl#1798] opened 2018-10-19 16:00 UTC
I seem to be only able to make one plot with the `plotlyjs()` backend enabled. The first plot shows up normally, but the second plot is blank.

I'm using Windows 10. Julia v1.0.1.

  [c52e3926] Atom v0.7.8
  [ad839575] Blink v0.8.1
  [7073ff75] IJulia v1.13.0
  [e5e0dc1b] Juno v0.5.3
  [b964fa9f] LaTeXStrings v1.0.3
  [47be7bcc] ORCA v0.1.1
  [58dd65bb] Plotly v0.2.0
  [f0f68f2c] PlotlyJS v0.11.2
  [91a5bcdd] Plots v0.20.6
  [438e738f] PyCall v1.18.5
  [d330b81b] PyPlot v2.6.3

```
using Plots
plotlyjs()
x = 1:10; y = rand(10);
plot(x,y)
plot(x,y)
```

After the first plot I get this, plot 1, (in the first window):
![run1](https://user-images.githubusercontent.com/2823875/47229351-86cd7600-d395-11e8-881a-f8ac50c95707.PNG)

After the second plot I get this, plot 2, (in the second window):
![run2](https://user-images.githubusercontent.com/2823875/47229361-8f25b100-d395-11e8-8f98-fd4d805dbae7.PNG)

I noticed if I run `plot!(x,y)`, the window gets update with the correct looking plot (it goes from looking like plot 2 to plot 1. But it also opens another window that looks like plot 2.

Another thing I tried was to close all the plot windows, and then run `plot!(x,y)` again. A plot looking like plot 2 opens up. Then I run `plot!(x,y)` again. The first plot gets updated to look like plot 1, but then another new window opens again looking like plot 2.

I don't really know how the internals work, but maybe something is being targeted to the wrong electron window?

**Comment by hsseung** [comment] 2018-10-29 03:49
I have exactly the same problem under Ubuntu 18.04.

**Comment by daschw** [comment] 2018-11-01 11:31
Duplicate of #1721

**Closed by daschw** 2018-11-01 11:31 UTC
