### ISSUE TITLE
[BUG] ffmpeg ProcessSignaled(11)

### ISSUE THREAD

**Issue by helgehr** [JuliaPlots/Plots.jl#3575] opened 2021-06-14 17:57 UTC
## Details
When trying to save a animation with `gif(anim, "anim.gif")` an error is thrown:
```
ERROR: failed process: Process(`/home/test/.julia/artifacts/7f40eeb66d90d3026ae5fb68761c263b57adb840/bin/ffmpeg -v 16 -framerate 20 -i /tmp/jl_b1XznB/%06d.png -i /tmp/jl_b1XznB/palette.bmp -lavfi paletteuse=dither=sierra2_4a -loop 0 -y /home/helge/test.gif`, ProcessSignaled(11)) [0]
```
The Problem seems to be an segmentation violation by the ffmpeg executable. When I use the same command in a terminal with `/bin/ffmpeg` instead everything seems to work fine.
This seems to be related to the following [issue](https://discourse.julialang.org/t/animation-bug/60982). I am running Arch Linux as well.
My full stacktraces is attatched: [anim.log](https://github.com/JuliaPlots/Plots.jl/files/6650318/anim.log)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |     |x
plotly       |     |     |x
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
inspectdr    |     |     |x

### Versions

Plots.jl version: 1.16.5
Backend  version (`]st -m <backend(s)>`): 0.57.5
Output of `versioninfo()`:
```
Julia Version 1.6.1
Commit 6aaedecc44* (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.0 (ORCJIT, ivybridge)
```

**Comment by t-bltg** [comment] 2021-07-06 18:17
@helgehr as a workaround you can use `Overrides.toml` in `~/.julia/artifacts` (see https://pkgdocs.julialang.org/v1/artifacts/#Overriding-artifact-locations) to point to your system ffmpeg.

Overrides.toml
```
[b22a6f82-2f65-5046-a5b2-351ab43fb4e5]
FFMPEG = "..."
# sha1(artifact)=7f40eeb66d90d3026ae5fb68761c263b57adb840
```
with FFMPEG  a path to a directory containing `bin/ffmpeg`.

**Comment by Mo8it** [comment] 2021-07-09 14:14
> @helgehr as a workaround you can use `Overrides.toml` in `~/.julia/artifacts` (see https://pkgdocs.julialang.org/v1/artifacts/#Overriding-artifact-locations) to point to your system ffmpeg or a custom built one, and julia will use it.
> 
> **Overrides.toml**
> 
> ```
> [b22a6f82-2f65-5046-a5b2-351ab43fb4e5]
> FFMPEG = "..."
> # sha1(artifact)=7f40eeb66d90d3026ae5fb68761c263b57adb840
> ```
> 
> with FFMPEG a path to a directory containing `bin/ffmpeg`.

Did not work for me :(

**Comment by t-bltg** [comment] 2021-07-09 14:26
> Did not work for me :(

Still a `SIGSEGV` (11) ?

**Comment by helgehr** [comment] 2021-07-12 09:42
Thanks for your advise!

For me it sadly does not work either. So I added this in my `.julia/artifacts/Overrides.toml`:
```
[b22a6f82-2f65-5046-a5b2-351ab43fb4e5]
FFMPEG = "/usr/bin/ffmpeg"
```

Now if I go to the julia REPL and type in `using FFMPEG` I get an InitError:
```
ERROR: InitError: Artifact "FFMPEG" was not installed correctly. Try `using Pkg; Pkg.instantiate()` to re-install all missing resources.
```

When I type in the suggested commands and afterwards try `using FFMPEG; FFMPEG.exe("-version")` I get the following error:
```julia> using FFMPEG; FFMPEG.exe("-version")
ERROR: MethodError: no method matching withenv_executable_wrapper(::FFMPEG.var"#4#6"{Cmd}, ::Nothing, ::String, ::String, ::Bool, ::Bool)
Closest candidates are:
  withenv_executable_wrapper(::Function, ::String, ::String, ::String, ::Bool, ::Bool) at /home/helge/.julia/packages/JLLWrappers/bkwIo/src/runtime.jl:37
Stacktrace:
 [1] #invokelatest#2
   @ ./essentials.jl:708 [inlined]
 [2] invokelatest
   @ ./essentials.jl:706 [inlined]
 [3] #ffmpeg#7
   @ ~/.julia/packages/JLLWrappers/bkwIo/src/products/executable_generators.jl:7 [inlined]
 [4] ffmpeg
   @ ~/.julia/packages/JLLWrappers/bkwIo/src/products/executable_generators.jl:7 [inlined]
 [5] #exe#2
   @ ~/.julia/packages/FFMPEG/OUpap/src/FFMPEG.jl:111 [inlined]
 [6] #exe#1
   @ ~/.julia/packages/FFMPEG/OUpap/src/FFMPEG.jl:64 [inlined]
 [7] exe(args::String)
   @ FFMPEG ~/.julia/packages/FFMPEG/OUpap/src/FFMPEG.jl:64
 [8] top-level scope
   @ REPL[3]:1
```

Did I do something wrong in editing the Overrides.toml?

**Comment by t-bltg** [comment] 2021-07-12 09:47
> For me it sadly does not work either. So I added this in my `.julia/artifacts/Overrides.toml`:
> 
> ```
> [b22a6f82-2f65-5046-a5b2-351ab43fb4e5]
> FFMPEG = "/usr/bin/ffmpeg"
> ```

> Did I do something wrong in editing the Overrides.toml?

Yes, it should be:
```
> [b22a6f82-2f65-5046-a5b2-351ab43fb4e5]
> FFMPEG = "/usr"
```

, so that "$(FFMPEG)/bin/ffmpeg" yields `/usr//bin/ffmpeg`.

**Comment by helgehr** [comment] 2021-07-12 10:21
Ok, thank you! I also had to install the `libavresample` library, because it was not in my `/usr/lib/` path, but apparently julia needs it.

But now it works!

**Comment by t-bltg** [comment] 2021-07-12 10:25
Glad to to hear ! Don't forget to close the issue if all is resolved :wink: .

**Closed** 2021-07-12 10:40 UTC
Labels: bug

**Comment by Mo8it** [comment] 2021-07-14 15:29
@t-bltg Thanks for your help! It did work :)
But I would not close the issue because this is only a workaround. The issue is not solved!

**Comment by t-bltg** [comment] 2021-07-14 15:35
@Mo8it, great !

It is a workaround, yes, but there is nothing `Plots.jl` can do here.

If `julia -e 'using FFPEG; FFMPEG.exe("-version")'` segfaults on Arch, then the issue should go in https://github.com/JuliaIO/FFMPEG.jl, not here.
