### ISSUE TITLE
No output on JupyterLab and PlotlyJS

### ISSUE THREAD

**Issue by staticfloat** [JuliaPlots/Plots.jl#1418] opened 2018-02-28 17:45 UTC
When using JupyterLab and PlotlyJS as my backend, I receive no output after plotting:

<img width="440" alt="screen shot 2018-02-28 at 9 43 56 am" src="https://user-images.githubusercontent.com/130920/36803271-f381a938-1c6b-11e8-8b28-421c61c15018.png">

Whereas, when using PlotlyJS directly, things work:

<img width="774" alt="screen shot 2018-02-28 at 9 45 14 am" src="https://user-images.githubusercontent.com/130920/36803327-173e1b4a-1c6c-11e8-824a-2b018cafe511.png">

**Comment by staticfloat** [comment] 2018-02-28 17:45
@sglyon notes that this may be due to incomplete MIME type passing.

**Comment by sglyon** [comment] 2018-02-28 17:47
If [these lines](https://github.com/JuliaPlots/Plots.jl/blob/18032bb9af9f24e8e3c13e9b2ec6d5423a0379dc/src/backends/plotlyjs.jl#L36-L39) were uncommented the issue would go away :)

**Comment by mkborregaard** [comment] 2018-02-28 17:48
Is this not a duplicate of #1386 ?

**Comment by mkborregaard** [comment] 2018-02-28 17:55
Those lines were uncommented by @tbreloff back in https://github.com/JuliaPlots/Plots.jl/commit/80e53adbd8453184fffe28a0b753503790a9e3fb not really sure why. It's worth just commenting them in and see what happens.

**Comment by sglyon** [comment] 2018-02-28 17:56
I'm actually putting together a PR that will fix this for both plotly and plotlyjs backends -- hang tight

**Comment by mkborregaard** [comment] 2018-02-28 17:59
:100: 💖 👍

**Comment by sglyon** [comment] 2018-02-28 18:25
<img width="2560" alt="screen shot 2018-02-28 at 1 24 33 pm" src="https://user-images.githubusercontent.com/1001948/36805190-bfde2754-1c8a-11e8-92f3-68f592e09f5c.png">

got it working -- but need to leave now. will package into PR soon

**Closed** 2018-03-01 06:41 UTC
