### ISSUE TITLE
Annotations not working with PGFPlots

### ISSUE THREAD

**Issue by jebej** [JuliaPlots/Plots.jl#735] opened 2017-03-15 20:54 UTC
As per the [example](https://juliaplots.github.io/examples/pgfplots/#annotations), and in my own trials as well.

**Comment by daschw** [comment] 2018-06-24 18:12
The problem is the `#3` sign in the text, which LaTeX interprets as parameter.
```julia
plot(y,annotations=(3,y[3],text("this is \\#3",:left)),leg=false)
```
works.
Maybe we should edit the example.

**Comment by BeastyBlacksmith** [comment] 2021-06-12 06:55
Thats fixed in pgfplotsx

**Closed by BeastyBlacksmith** 2021-06-12 06:55 UTC
