### ISSUE TITLE
Make tests pass

### ISSUE THREAD

**Issue by tbreloff** [JuliaPlots/Plots.jl#670] opened 2017-02-06 14:29 UTC
The VRT tests fail because of the PyPlot.jl upgrade to Matplotlib 2.0.

**Comment by daschw** [comment] 2017-03-16 22:24
Ok, so I've run the VRT tests locally today and I have found basically two issues for pyplot/matplotlib2:

1. The colorbar labels are cropped, as can be seen in the following pictures:
![4_colors](https://cloud.githubusercontent.com/assets/16589944/24019779/c39d266e-0a99-11e7-9671-bc92a600b1b1.png)
![10_histogram2d](https://cloud.githubusercontent.com/assets/16589944/24019786/ca6eeb44-0a99-11e7-8ad3-abe169b4545e.png)
![22_contours](https://cloud.githubusercontent.com/assets/16589944/24019789/cf52121c-0a99-11e7-9d12-61769a34e70a.png)
![24_3d](https://cloud.githubusercontent.com/assets/16589944/24019797/d46cf80c-0a99-11e7-9fad-af497fe24704.png)
![28_heatmap](https://cloud.githubusercontent.com/assets/16589944/24019807/dcd35644-0a99-11e7-93df-1eda1bcfcd17.png)
Should I create a seperate issue for this?

2. (probably minor) The display of line styles (dot, dashdot, ...) has changed:
![12_line_styles](https://cloud.githubusercontent.com/assets/16589944/24020041/dfc4c7b0-0a9a-11e7-8bb7-b078cda356b4.png)
I don't know, if this is a big issue, but in the legend the dashed and dashdotted lines cannot really be identified as such.

cc: @mkborregaard

**Comment by daschw** [comment] 2017-03-16 22:32
I've also run into some problems with GR:

1. Images are displayed transposed. This is probably already known via https://github.com/JuliaPlots/Plots.jl/issues/432
![6_images](https://cloud.githubusercontent.com/assets/16589944/24020427/68354150-0a9c-11e7-9f27-57f69bc584e0.png)

2. The custom marker shapes are weirdly stretched:
![21_custom_markers](https://cloud.githubusercontent.com/assets/16589944/24020824/259b7510-0a9e-11e7-80e7-1e6a4d803372.png)

3. Colorbars are not shown:
![24_3d](https://cloud.githubusercontent.com/assets/16589944/24020916/96447dd4-0a9e-11e7-873b-3c8084d755bd.png)
![28_heatmap](https://cloud.githubusercontent.com/assets/16589944/24020928/a449b57a-0a9e-11e7-98ae-d5b4ff47020d.png)

**Comment by tbreloff** [comment] 2017-03-17 00:41
In general you should accept the current image unless there's been a
regression. So if it used to be an issue and it's still an issue, no
problem.

**Comment by mkborregaard** [comment] 2017-03-17 08:32
As far as I can see there is a regression on all these examples?
Here is my suggestion (needs to be confirmed by @tbreloff as this is just my naive take on it): 

1. Except for the first image, save the current (new/left) image for pyplot regardless of clipping of the color bar, but open an issue for color bar clipping.
2. Don't save the new version of the very first image as the legend position is off, and this seems necessary to fix? And open an issue.
3. Just save the new version of the one with the linestyles. 
4. I have reopened the image rotation issue on GR. Don't save the new image.
5. Don't save the new version with the custom marker, open an issue for that.
6. Same for GR colorbars.

**Comment by mkborregaard** [comment] 2017-03-17 08:32
Oh and nice work!

**Comment by daschw** [comment] 2017-03-17 09:04
OK, of course I will wait for @tbreloff 's advice/confirmation.
In my opinion your suggestions sound very reasonable!
In the meantime I have already found an issue related to the color bar clipping (https://github.com/JuliaPlots/Plots.jl/issues/603). However, I guess this is more general and unrelated to matplotlib2, so I suppose I should still open a new issue?

**Comment by mkborregaard** [comment] 2017-03-17 09:12
Not sure, I have a feeling it's the same issue, really.

**Comment by mkborregaard** [comment] 2017-03-24 13:48
@tbreloff should @daschw go ahead with the actions I suggested? Or - is it important that all tests pass for the 0.6 transition?

**Comment by ma-laforge** [comment] 2017-03-25 22:14
Not sure if this will affect future actions, but I recently submitted PR https://github.com/JuliaPlots/Plots.jl/pull/740.

If it gets merged, all outputs will be shifted a bit:

 1. Definition/calculation of "pixel" was altered/corrected.
 2. "point" is now the base unit in Plots.jl (instead of "pixel").

These changes were necessary to control dpi in a meaningful/intuitive fashion.
 
### If the Plots.jl group (@tbreloff) decides to merge:

Backend maintainers will probably want to re-tweak their outputs to match these re-definitions.

Of course, these changes will affect the pyplot() and gr() outputs as well.

**Comment by mkborregaard** [comment] 2017-03-31 14:44
The GR color bar issue is fixed :-) https://github.com/JuliaPlots/Plots.jl/pull/754

**Comment by daschw** [comment] 2017-05-17 18:53
@mkborregaard Do you think that the legend position in the first plot is really an issue?
Maybe it is related to the changes described [here](https://matplotlib.org/users/dflt_style_changes.html#legends)
On the other hand, [here](https://github.com/JuliaPlots/Plots.jl/blob/master/src/backends/pyplot.jl#L1185) it looks like Plots always chose `"best"` as default legend position, so I cannot really explain the changed location

**Comment by mkborregaard** [comment] 2017-05-17 19:36
It's so weird, though

**Comment by mkborregaard** [comment] 2017-05-17 21:13
But not a big problem, agreed. You should probably just accept the image.

**Closed** 2017-06-02 14:23 UTC
