### ISSUE TITLE
docs example not working

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaPlots/Plots.jl#2088] opened 2019-07-03 16:28 UTC
this example from the docs section "Layouts, margins, label rotation, title location"
```julia
using Plots.PlotMeasures
plot(rand(100, 6), layout=@layout(), title=["A" "B" "C"], title_location=:left, left_margin=[20mm 0mm], bottom_margin=10px, xrotation=60)
```
produces the error
```julia
MethodError: no method matching @layout(::LineNumberNode, ::Module)
Closest candidates are:
  @layout(::LineNumberNode, ::Module, !Matched::Expr) at /Users/abradley/.julia/packages/Plots/p4X67/src/layouts.jl:703
```

on 
```julia
julia> versioninfo()
Julia Version 1.1.1
Commit 55e36cc (2019-05-16 04:10 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

**Comment by mkborregaard** [comment] 2019-07-04 06:19
I wonder what's gone wrong here - the examples in the docs are generated from examples.jl, in this case here: https://github.com/JuliaPlots/Plots.jl/blob/master/src/examples.jl#L345-L353
As you can see, the correct syntax is 
```julia
using Plots.PlotMeasures # for Measures, e.g. mm and px
plot(rand(100,6),layout=@layout([a b; c]),title=["A" "B" "C"],
    title_location=:left, left_margin=[20mm 0mm],
    bottom_margin=10px, xrotation=60
)
```
These docs are auto-generated - Documenter bug? @daschw any ideas?

**Comment by daschw** [comment] 2019-07-04 07:20
Seems to be related to #2019. I'm anyway currently working on the docs (moving the documentation images from PlotReferenceImages back to PlotDocs so the Plots tests suite can be used again to update reference images) so I will have a look.

**Comment by daschw** [comment] 2019-07-04 07:37
It's not a Documenter bug. The issue is in `PlotDocs.filter_out_line_numbers!`:
```julia
julia> using PlotDocs

julia> example = PlotDocs._examples[29]
Plots.PlotExample("Layouts, margins, label rotation, title location", "", Expr[quote
    #= C:\Users\Daniel\.julia\dev\Plots\src\examples.jl:348 =#
    using Plots.PlotMeasures
    #= C:\Users\Daniel\.julia\dev\Plots\src\examples.jl:349 =#
    plot(rand(100, 6), layout=#= C:\Users\Daniel\.julia\dev\Plots\src\examples.jl:349 =# @layout([a b; c]), title=["A" "B" "C"], title_location=:left, left_margin=[20mm 0mm], bottom_margin=10px, xrotation=60)
end])

julia> expr = copy(example.exprs[1])
quote
    #= C:\Users\Daniel\.julia\dev\Plots\src\examples.jl:348 =#
    using Plots.PlotMeasures
    #= C:\Users\Daniel\.julia\dev\Plots\src\examples.jl:349 =#
    plot(rand(100, 6), layout=#= C:\Users\Daniel\.julia\dev\Plots\src\examples.jl:349 =# @layout([a b; c]), title=["A" "B" "C"], title_location=:left, left_margin=[20mm 0mm], bottom_margin=10px, xrotation=60)
end

julia> PlotDocs.filter_out_line_numbers!(expr);

julia> expr
quote
    using Plots.PlotMeasures
    plot(rand(100, 6), layout=@layout(), title=["A" "B" "C"], title_location=:left, left_margin=[20mm 0mm], bottom_margin=10px, xrotation=60)
end
```
Also, I'm not sure why there is a LineNumberNode in 
```julia
plot(rand(100, 6), layout=#= C:\Users\Daniel\.julia\dev\Plots\src\examples.jl:349 =# @layout([a b; c]), title=["A" "B" "C"], title_location=:left, left_margin=[20mm 0mm], bottom_margin=10px, xrotation=60)
```

**Comment by mkborregaard** [comment] 2019-07-04 07:48
No that's rather bizarre

**Comment by daschw** [comment] 2020-03-02 16:14
Fixed by https://github.com/JuliaPlots/PlotDocs.jl/pull/164

**Closed by daschw** 2020-03-02 16:14 UTC
Labels: Documentation
