### ISSUE TITLE
Cannot plot large scale figure with plotlyjs() backend on atom Juno

### ISSUE THREAD

**Issue by haotian127** [JuliaPlots/Plots.jl#2405] opened 2020-02-19 00:16 UTC
Hi,

When I try something like,
```
using Plots
plotlyjs()
heatmap(rand(10,10))
```
it works fine and generate the correct figure. But when I increase the scale,
```
using Plots
plotlyjs()
heatmap(rand(400,400))
```
it does not output the resulting figure. Any thoughts about what is wrong? Thanks a lot!

```
julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\lihao\AppData\Local\atom\app-1.44.0\atom.exe"  -a
  JULIA_NUM_THREADS = 6
```

**Comment by mkborregaard** [comment] 2020-02-19 09:13
I can reproduce, on the newest versions. Very strange though. @pfitzseb did you not change the way Juno handles plotlyjs plots recently?

**Comment by pfitzseb** [comment] 2020-02-19 10:12
Turns out there *is* a limit on the size of data URIs after all. Everything under 2MB (equivalent to heatmap(rand(168,168))) works fine, everything above that doesn't. This is a Juno bug though, so let's close this in favour of https://github.com/JunoLab/Juno.jl/issues/488.

**Closed** 2020-02-19 10:30 UTC
