### ISSUE TITLE
Axis label (guide?) needs padding

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaPlots/Plots.jl#1988] opened 2019-04-08 16:45 UTC
The y-axis label (in GR) is too close to the axis tick labels, and there doesn't appear to be an attribute to modify this.

![label](https://user-images.githubusercontent.com/1438610/55741734-f98de480-59fb-11e9-844d-d81b5fedfcd2.png)

**Comment by steinQF** [comment] 2019-04-13 13:50
The same issue exists in `plotlyjs`, at least for logarithmic scales (which have tick labels that are wider than usual).

**Comment by mkborregaard** [comment] 2019-04-15 13:06
@jheinen could this be an artifact of https://github.com/JuliaPlots/Plots.jl/commit/61d13b9b2d783f2ffa8cebb2518843951c25f20e ?

**Comment by jheinen** [comment] 2019-04-15 13:24
@mkborregaard : Yes, we need a solution that takes the effective/maximum length of the labels into account. Otherwise, we will always "waste space".

**Comment by mkborregaard** [comment] 2019-04-15 13:31
I think wasting space is a lot better than overlap, though, if we have to choose. I think it should be possible to calculate the the labels from the `ticks` and `tickfont`, which are available in the `plotattributes` object at backend time.

**Comment by daschw** [comment] 2019-06-15 16:50
I think that's fixed for GR in #2018:
```julia
using Plots
plot([0, 1], yguide = "p(chance association)")
```
![gr_guide](https://user-images.githubusercontent.com/16589944/59554055-fc79f800-8f9d-11e9-8919-727391abe6bd.png)

I agree that PlotlyJS with scientific format could use a little more space.
![plotly_guide](https://user-images.githubusercontent.com/16589944/59554070-524ea000-8f9e-11e9-8815-8045518ce7cc.png)

**Comment by bartolsthoorn** [comment] 2020-12-10 00:42
Is there any work-around at this time? This is also a problem for GR. For example, in this piece of code the `bottom_margin` does not give margin between the guide and the axis, but just margin to the whole figure..
```
using Plots
using Plots.PlotMeasures
plot(1:4, xguide="x label", bottom_margin=20mm)
```

Real-world example of the problem for GR (where bottom_margin/left_margin would not fix the overlap):
![mcs](https://user-images.githubusercontent.com/106586/101706173-d9dc7880-3a88-11eb-82d6-d77dc01d64e3.png)

**Comment by mkborregaard** [comment] 2020-12-10 08:32
What backend is that - PGFPlotsX?

**Comment by bartolsthoorn** [comment] 2020-12-10 10:22
@mkborregaard It is GR, I just replaced all the labels using `LaTeXStrings` so that I can use latex in them later and the font family matches the publication.

**Comment by Ezequiel92** [comment] 2021-01-07 15:01
To add to @bartolsthoorn comment, in GR there are several ways to get a Computer Modern font/LaTeX symbols, and with each one you can get a different separation between the axis guides and the numbers. It is probably related to the [comment](https://github.com/JuliaPlots/Plots.jl/issues/3210#issuecomment-754059046) on issue #3210, because in each instance that the padding is different the text size is different too, and that is probably not being taken into account. The separation for the x axis and the y axis is sometimes different too, if my eyes are not lying. 

A MWE for several possible combinations would be

```julia
using Plots
using LaTeXStrings

data_linear = rand(10)

xlabel = "x label"
ylabel = "y label"
xlabelLaTeX = L"\textrm{x label}"
ylabelLaTeX = L"\textrm{y label}"
```

<table>
<tr>
<td> MWE </td> <td> Result </td>
</tr>

<tr>
<td>

```julia
plot(data_linear, 
xlabel=xlabel, 
ylabel=ylabel)
```
</td>
<td> 

![non_latex_label_non_latex_ticks_low](https://user-images.githubusercontent.com/76693950/103902197-f1833d00-50d8-11eb-94f5-c89bbdd9d41f.png) ![non_latex_label_non_latex_ticks_high](https://user-images.githubusercontent.com/76693950/103902237-fea02c00-50d8-11eb-9d68-feea44e9ebe6.png) 
</td>
</tr>

<tr>
<td>

```julia
plot(data_linear, 
xlabel=xlabelLaTeX, 
ylabel=ylabelLaTeX)
```
</td>
<td> 

![latex_label_non_latex_ticks_low](https://user-images.githubusercontent.com/76693950/103902333-24c5cc00-50d9-11eb-8327-c447ca037641.png) ![latex_label_non_latex_ticks_high](https://user-images.githubusercontent.com/76693950/103902359-2c857080-50d9-11eb-84b7-0295c1ae4c3a.png) 
</td>
</tr>

<tr>
<td>

```julia
plot(data_linear, 
xlabel=xlabel, 
ylabel=ylabel, 
xformatter=:latex, 
yformatter=:latex)
```
</td>
<td> 

![non_latex_label_latex_ticks_low](https://user-images.githubusercontent.com/76693950/103902558-75d5c000-50d9-11eb-9246-87decfbf2ee8.png) ![non_latex_label_latex_ticks_high](https://user-images.githubusercontent.com/76693950/103902575-7b330a80-50d9-11eb-9ad3-083d2fb979c6.png) 
</td>
</tr>

<tr>
<td>

```julia
plot(data_linear, 
xlabel=xlabelLaTeX, 
ylabel=ylabelLaTeX, 
xformatter=:latex, 
yformatter=:latex)
```
</td>
<td> 

![latex_label_latex_ticks_low](https://user-images.githubusercontent.com/76693950/103902631-900f9e00-50d9-11eb-8a61-47c8cee14453.png) ![latex_label_latex_ticks_high](https://user-images.githubusercontent.com/76693950/103902654-9736ac00-50d9-11eb-919b-f9b6f9c25337.png) 
</td>
</tr>

<tr>
<td>

```julia
plot(data_linear, 
xlabel=xlabel, 
ylabel=ylabel, 
fontfamily="Computer Modern")
```
</td>
<td> 

![gr_latex_font_low](https://user-images.githubusercontent.com/76693950/103904824-90f5ff00-50dc-11eb-9551-0a2f94f15130.png) ![gr_latex_font_high](https://user-images.githubusercontent.com/76693950/103904849-97847680-50dc-11eb-94a2-667cb0b4f990.png)
</td>
</tr>

<tr>
<td>

```julia
plot(data_linear, 
xlabel=xlabelLaTeX, 
ylabel=ylabelLaTeX, 
fontfamily="Computer Modern")
```
</td>
<td> 

![gr_latex_font_latex_label_low](https://user-images.githubusercontent.com/76693950/103905047-e16d5c80-50dc-11eb-9f9c-52e73f93ea00.png) ![gr_latex_font_latex_label_high](https://user-images.githubusercontent.com/76693950/103905077-e9c59780-50dc-11eb-8a80-f64df627152b.png)
</td>
</tr>
</table>

In general, I think that the separation is ok, even thought it would be better if it were larger, but there are a few cases where there is no separation and the labels collide, in which case that would be a bug, I think. 

To contrast to the examples above, if one uses pgfplotsx, the separation is much larger, and in my opinion is the best looking. 

<table>
<tr>
<td> MWE </td> <td> Result </td>
</tr>

<tr>
<td>

```julia
using Plots
pgfplotsx()

plot(rand(10), 
xlabel="x label", 
ylabel="y label")
```
</td>
<td> 

![pgfplotsx_basic_low](https://user-images.githubusercontent.com/76693950/103905775-c94a0d00-50dd-11eb-93e6-6c7cca4b37e7.png) ![pgfplotsx_basic_high](https://user-images.githubusercontent.com/76693950/103905791-ce0ec100-50dd-11eb-83c1-e69dc9ff47bf.png)
</td>
</tr>
</table>

**Comment by daschw** [comment] 2021-01-10 19:32
Would #3218 be an improvement/fix for this?

**Closed** 2021-01-12 08:49 UTC
Labels: Plotly, PlotlyJS

**Comment by abcdvvvv** [comment] 2025-02-16 12:19
I had a similar problem recently. I read through the issue and although the issue is closed, the distance between the axis label and the axis tick is still not “arbitrarily” adjustable.

I have plotted the following diagram, but I think the distance between the axis labels and the tick is too big, can I reduce it?

```julia
# GR backend
p1 = plot(1:10, (1:10).^2, marker=:circle, xlabel="xxxxx",
    ylabel="Time (s)", title="Performance", legend=false)
```

<img src="https://github.com/user-attachments/assets/07bd93ed-ec93-4dbb-8b2b-8dca88bcfade" alt="Image" width="400">
