### ISSUE TITLE
contour with pgfplots() is actually contour3d

### ISSUE THREAD

**Issue by mmikhasenko** [JuliaPlots/Plots.jl#1478] opened 2018-04-08 17:43 UTC
![screenshot from 2018-04-08 18-22-16](https://user-images.githubusercontent.com/22725744/38469733-d3894386-3b59-11e8-8469-97c377fea04c.png)

Is there a way to get just contours?

**Comment by daschw** [comment] 2018-04-08 17:45
This needs to be fixed in the backend code. Thanks for reporting! 
Until it's fixed, you could use another backend.

**Comment by floswald** [comment] 2018-04-12 15:38
duplicate of #1321

**Comment by daschw** [comment] 2018-04-12 17:14
Thanks!
Closing as dup of #1321.

**Closed by daschw** 2018-04-12 17:14 UTC
Labels: PGFPlots, bug
