### ISSUE TITLE
secondary y axis title goes in a wrong place

### ISSUE THREAD

**Issue by montyvesselinov** [JuliaPlots/Plots.jl#1863] opened 2018-12-07 20:17 UTC
```julia
using Plots

plot(rand(10); ylabel="a")
plot!(twinx(), rand(10); ylabel="b")
```

**Comment by BioTurboNick** [comment] 2019-06-05 01:58
Just came across this looking for how to add a secondary y axis, thought I'd add a picture and clarify that  "wrong place" means it is cut off.

![secondaryaxis](https://user-images.githubusercontent.com/1438610/58924927-aee6cb00-8713-11e9-886e-ed3c46e6c494.png)

**Comment by ssfrr** [comment] 2020-02-25 17:08
dup of #2205?

**Comment by liupgd** [comment] 2022-02-19 12:26
If plotly backend is used, the secondary y axis goes to the left. 
Plots.jl version: 1.25.10

![image](https://user-images.githubusercontent.com/3350539/154800667-9d81b09c-93dd-494e-bd1f-7603b7fea1d9.png)

**Comment by BeastyBlacksmith** [comment] 2022-02-28 14:28
For plotly it is a duplicate of https://github.com/JuliaPlots/Plots.jl/issues/2956

**Comment by t-bltg** [comment] 2022-11-01 20:37
Closed by https://github.com/JuliaPlots/Plots.jl/pull/4488.

**Closed by t-bltg** 2022-11-01 20:37 UTC
Labels: duplicate
