### ISSUE TITLE
PlotlyJS backending for Plots broken on macos?

### ISSUE THREAD

**Issue by iwelch** [JuliaPlots/Plots.jl#1749] opened 2018-09-17 17:07 UTC
macos.  Plots v"0.20.2".  PlotlyJS v"0.11.1".  fresh install of PlotlyJS.

```
Pkg.add("Blink"); using Blink; Blink.AtomShell.install(); exit()
```

then

```
using Plots; plotlyjs(); plot(1:10, sqrt.(1:10))
```

only plots an empty coordinate system xlim=(-1,6) and ylim=(-1,4). 

PlotlyJS natively works and plots the parabola:

```
julia> using PlotlyJS

julia> plot(1:10, sqrt.(1:10))
```

there are other issues, too, like a `scatter!` following creates a new empty graph.  and a savefig seems to save the gr figure, not the plotlyjs figure, even after installing ORCA.  again, PlotlyJS native works fine.

**Comment by daschw** [comment] 2018-11-01 11:41
Duplicate of #1721

**Closed by daschw** 2018-11-01 11:41 UTC
