### ISSUE TITLE
3D axis labels in wrong position using GR backend

### ISSUE THREAD

**Issue by azsigmon** [JuliaPlots/Plots.jl#743] opened 2017-03-23 13:16 UTC
When I plot in 3D, the axis labels are not shown correctly. The z axis is labelled with the ylabel, the xlabel is in the bottom and the zlabel is not shown:
![example](https://cloud.githubusercontent.com/assets/4508364/24249344/2a5f362e-0fd3-11e7-8522-75f9a1831054.png)
To reproduce the problem use this line:
`using Plots; gr(); x = rand(100); y = rand(100); z = rand(100); plot(x, y, z, xlabel = "x", ylabel = "y", zlabel = "z")`

**Comment by mkborregaard** [comment] 2017-03-23 21:58
I think the issue is that guides aren't set by GR.jl, they are created with `grtext` here: https://github.com/JuliaPlots/Plots.jl/blob/master/src/backends/gr.jl#L713-L726
I think a solution could be to check if the seriestype is three-dimensional, and if it is, pass `guide`s to GR's `titles3d` function.

**Comment by apalugniok** [comment] 2017-10-10 09:05
I'll give this a shot 😄

**Comment by mkborregaard** [comment] 2017-10-10 09:31
Awesome, you're really on a roll!

**Comment by apalugniok** [comment] 2017-10-10 09:59
A very quick quick implementation (just adding `titles3d` to the end of the `if is3d(sp)` block in `gr.jl`) gives:
![title3d](https://user-images.githubusercontent.com/22132297/31380566-9d306b90-ada9-11e7-95e6-8473735a17b2.png)

The position of the z axis guide is intended GR behaviour (see here: https://gr-framework.org/examples/kws2.html). But I'm note sure where the large padding comes from.

**Comment by apalugniok** [comment] 2017-10-10 11:07
The padding seems to be a GR specific issue.
```
using GR
x = 1:1:10
y = z = rand(10)
GR.surface(x,y,z, xlabel = "x", ylabel = "y", zlabel = "z")
```
<img width="593" alt="grissue" src="https://user-images.githubusercontent.com/22132297/31383522-4756c746-adb3-11e7-833d-4134642b58b5.png">

@jheinen Any Ideas? I can open an issue on GR.jl if you would like.

**Comment by mkborregaard** [comment] 2018-04-15 16:24
This was just re-reported here https://github.com/JuliaPlots/Plots.jl/issues/1483
@apalugniok did your fix work?

**Comment by apalugniok** [comment] 2018-04-15 16:28
I never merged it because of the huge padding issue, apart from that it worked.

**Comment by t37w** [comment] 2018-04-15 19:46
@apalugniok : at one hand, your update would it make better than current.  On the other hand, having a partial fix may weaken the visibility of the root coarse.

From my point of view, the zlabel looks like of being aligned with the x-axis. But it should be rotated to be parallel to the z-axis similar to the other axes. Thus, to be changed in the backend part 'GR.jl'.

**Comment by mkborregaard** [comment] 2018-04-16 06:11
I think the rotated z axis label is a GR thing, not something we can adress from Plots. @jheinen ?

**Comment by mkborregaard** [comment] 2019-02-26 17:04
@apalugniok where does your fix live? Let's get this fixed now.

**Comment by apalugniok** [comment] 2019-02-26 17:26
Seems like I still have it in a branch on my fork of Plots. Hopefully it doesn't have many merge conflicts.

**Comment by mkborregaard** [comment] 2019-02-26 17:41
feel like rebasing and opening a pr? :-D

**Comment by apalugniok** [comment] 2019-02-26 18:47
Sure! I'll get it done tomorrow.

**Closed** 2019-02-27 11:25 UTC
