### ISSUE TITLE
[FR]hi im new here, idk what happened here but can anybody help me

### ISSUE THREAD

**Issue by rozaanalex** [JuliaPlots/Plots.jl#3011] opened 2020-09-27 08:51 UTC
Please search existing issues to avoid duplicates.could not load library "libGR.dll" The specified module could not be found. Stacktrace: [1] setcharheight(::Float64) at C:\Users\Acer\.julia\packages\GR\BwGt2\src\GR.jl:1417 [2] gr_set_font(::Plots.Font, ::Plots.Subplot{Plots.GRBackend}; halign::Symbol, valign::Symbol, color::RGBA{Float64}, rotation::Int64) at C:\Users\Acer\.julia\packages\Plots\fewot\src\backends\gr.jl:358 [3] gr_set_tickfont(::Plots.Subplot{Plots.GRBackend}, ::Symbol) at C:\Users\Acer\.julia\packages\Plots\fewot\src\backends\gr.jl:611 [4] _update_min_padding!(::Plots.Subplot{Plots.GRBackend}) at C:\Users\Acer\.julia\packages\Plots\fewot\src\backends\gr.jl:799 [5] iterate at .\generator.jl:47 [inlined] [6] _collect(::Array{AbstractLayout,2}, ::Base.Generator{Array{AbstractLayout,2},typeof(Plots._update_min_padding!)}, ::Base.EltypeUnknown, ::Base.HasShape{2}) at .\array.jl:699 [7] collect_similar(::Array{AbstractLayout,2}, ::Base.Generator{Array{AbstractLayout,2},typeof(Plots._update_min_padding!)}) at .\array.jl:628 [8] map(::Function, ::Array{AbstractLayout,2}) at .\abstractarray.jl:2162 [9] _update_min_padding!(::Plots.GridLayout) at C:\Users\Acer\.julia\packages\Plots\fewot\src\layouts.jl:310 [10] prepare_output(::Plots.Plot{Plots.GRBackend}) at C:\Users\Acer\.julia\packages\Plots\fewot\src\plot.jl:184 [11] show(::Base.GenericIOBuffer{Array{UInt8,1}}, ::MIME{Symbol("image/svg+xml")}, ::Plots.Plot{Plots.GRBackend}) at C:\Users\Acer\.julia\packages\Plots\fewot\src\output.jl:214 [12] sprint(::Function, ::MIME{Symbol("image/svg+xml")}, ::Vararg{Any,N} where N; context::Nothing, sizehint::Int64) at .\strings\io.jl:105 [13] sprint at .\strings\io.jl:101 [inlined] [14] _ijulia_display_dict(::Plots.Plot{Plots.GRBackend}) at C:\Users\Acer\.julia\packages\Plots\fewot\src\ijulia.jl:53 [15] display_dict(::Plots.Plot{Plots.GRBackend}) at C:\Users\Acer\.julia\packages\Plots\fewot\src\init.jl:73 [16] #invokelatest#1 at .\essentials.jl:710 [inlined] [17] invokelatest at .\essentials.jl:709 [inlined] [18] execute_request(::ZMQ.Socket, ::IJulia.Msg) at C:\Users\Acer\.julia\packages\IJulia\tOM8L\src\execute_request.jl:112 [19] #invokelatest#1 at .\essentials.jl:710 [inlined] [20] invokelatest at .\essentials.jl:709 [inlined] [21] eventloop(::ZMQ.Socket) at C:\Users\Acer\.julia\packages\IJulia\tOM8L\src\eventloop.jl:8 [22] (::IJulia.var"#15#18")() at .\task.jl:356

**Comment by daschw** [comment] 2020-09-29 22:34
Closing as duplicate of #2903. Maybe
```
ENV["GRDIR"] = ""
import Pkg
Pkg.build("GR")
```
helps.

**Closed by daschw** 2020-09-29 22:34 UTC
Labels: duplicate
