### ISSUE TITLE
PGFPlots SVG error when displaying from the REPL

### ISSUE THREAD

**Issue by stelmo** [JuliaPlots/Plots.jl#1539] opened 2018-05-22 17:45 UTC
Hi, it seems Plots is having an issue displaying graphs when I use the pgfplots backend on the REPL. I can use the PGFPlots package by itself to generate pdfs and then manually convert them to svgs using pdf2svg. I can also display the figures on IJulia, but when I try displaying graphs from Julia's command line I get:

`julia> using Plots`

`julia> pgfplots()
Plots.PGFPlotsBackend()`

`julia> x = [1,2,3]; y = [1,4,2];`

`julia> plot(x,y)
Error saving as SVG
Error showing value of type Plots.Plot{Plots.PGFPlotsBackend}:
ERROR: SystemError: opening file C:\Users\STFA5E~1.ELM\AppData\Local\Temp\jl_49F6.tmp.log: No such file or directory
Stacktrace:
 [1] #systemerror#44 at .\error.jl:64 [inlined]
 [2] systemerror(::String, ::Bool) at .\error.jl:64
 [3] open(::String, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at .\iostream.jl:104
 [4] open(::Base.#readstring, ::String) at .\iostream.jl:150
 [5] save(::TikzPictures.PDF, ::TikzPictures.TikzPicture) at C:\Users\St. Elmo\.julia\v0.6\TikzPictures\src\TikzPictures.jl:201
 [6] save(::TikzPictures.SVG, ::TikzPictures.TikzPicture) at C:\Users\St. Elmo\.julia\v0.6\TikzPictures\src\TikzPictures.jl:262
 [7] _display(::Plots.Plot{Plots.PGFPlotsBackend}) at C:\Users\St. Elmo\.julia\v0.6\Plots\src\backends\pgfplots.jl:607
 [8] display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::MIME{Symbol("text/plain")}, ::Plots.Plot{Plots.PGFPlotsBackend}) at C:\Users\St. Elmo\.julia\v0.6\Plots\src\output.jl:149
 [9] display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::Plots.Plot{Plots.PGFPlotsBackend}) at .\REPL.jl:125
 [10] display(::Plots.Plot{Plots.PGFPlotsBackend}) at .\multimedia.jl:218
 [11] eval(::Module, ::Any) at .\boot.jl:235
 [12] print_response(::Base.Terminals.TTYTerminal, ::Any, ::Void, ::Bool, ::Bool, ::Void) at .\REPL.jl:144
 [13] print_response(::Base.REPL.LineEditREPL, ::Any, ::Void, ::Bool, ::Bool) at .\REPL.jl:129
 [14] (::Base.REPL.#do_respond#16{Bool,Base.REPL.##26#36{Base.REPL.LineEditREPL,Base.REPL.REPLHistoryProvider},Base.REPL.LineEditREPL,Base.LineEdit.Prompt})(::Base.LineEdit.MIState, ::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Bool) at .\REPL.jl:646`

Does anyone know how to fix this?

**Comment by lrsantos11** [comment] 2018-10-11 15:10
+1 here on macOS

**Comment by matthieugomez** [comment] 2018-10-24 16:58
+1

**Comment by lrsantos11** [comment] 2019-01-24 01:33
Someone knows how to corrects this issue?

**Comment by arlk** [comment] 2019-01-27 14:10
I ran into this earlier. A *very* hacky workaround that you can do:
```julia
julia> p = plot(rand(10));
julia> savefig(p, "myplot.svg")
```
And you can open the svg using your favorite svg viewer. On OSX I just run ``run(`open myplot.svg\`)``.

**Comment by balazsmezei** [comment] 2019-03-05 01:15
This is caused by an issue in [TikzPictures.jl](https://github.com/JuliaTeX/TikzPictures.jl), fixed by this [pull request](https://github.com/JuliaTeX/TikzPictures.jl/pull/46) pending to be merged.

**Closed** 2020-05-19 17:22 UTC
