### ISSUE TITLE
Layout interpreted incorrectly when using PlotlyJS backend with Blink.

### ISSUE THREAD

**Issue by lassepe** [JuliaPlots/Plots.jl#2145] opened 2019-08-16 19:29 UTC
When using this package with the `PlotlyJS.jl` backend and default rendering in `Blink`, subplots don't seem to be working correctly. Please correct me if this bug should be filed in the `PlotlyJS.jl` repository.

E.g. for this very simple example:

```julia
using Plots
plotlyjs()

d1 = rand(10)
d2 = rand(10)

l = @layout [a b]
p1 = plot(d1)
p2 = plot(d2)

plot(p1, p2; layout=l)
```

The first plot is rendered to the entire space and the second plot is only rendered to the right grid cell:

![image](https://user-images.githubusercontent.com/10076790/63192659-78390500-c020-11e9-9546-b55fa5180c37.png)

---

However, doing the same with plain `PlotlyJS.jl` works out of the box:

```julia
using PlotlyJS

d1 = rand(10)
d2 = rand(10)

p1 = plot(d1)
p2 = plot(d2)
display([p1 p2])
```

Result:

![image](https://user-images.githubusercontent.com/10076790/63192902-07deb380-c021-11e9-99e8-b9290c1ec98f.png)

---

Also, simply using the code of the first example but using `plotly()` instead of `plotlyjs()` will produce the desired result:

![image](https://user-images.githubusercontent.com/10076790/63193058-5724e400-c021-11e9-85e5-5772ac9c5ce0.png)

---

**Comment by daschw** [comment] 2019-08-23 10:30
duplicate of #1869.

**Closed by daschw** 2019-08-23 10:30 UTC
Labels: PlotlyJS
