### ISSUE TITLE
Installation of package plots fails

### ISSUE THREAD

**Issue by rolfdstoll** [JuliaPlots/Plots.jl#2184] opened 2019-09-11 09:33 UTC
With Julia Version 1.2.0 the installation of package plots fails.
The error is: Error building `FFMPEG`
I attached the relevant build.log.
I work with Win10. The error appears equally on different Windows 10 machines.

[build.log](https://github.com/JuliaPlots/Plots.jl/files/3600009/build.log)

**Comment by daschw** [comment] 2019-09-11 09:42
Seems like a https://github.com/JuliaIO/FFMPEG.jl issue.
cc: @asinghvi17

**Comment by rolfdstoll** [comment] 2019-09-11 11:56
Ok, but how to fix it?

**Comment by asinghvi17** [comment] 2019-09-11 12:07
@daschw could you translate the error thrown by Download?  Something to do with a certificate?  Might have to retry the build.

**Comment by daschw** [comment] 2019-09-11 12:09
Not really, I was looking for the error code on google, and found e.g. https://stackoverflow.com/questions/54938026/curl-unknown-error-0x80092012-the-revocation-function-was-unable-to-check-r

**Comment by aerdely** [comment] 2019-09-14 21:48
The same happens to me. 
![FFMPEG_error2](https://user-images.githubusercontent.com/3356159/64913962-6a55cd00-d70f-11e9-9c31-755898de3804.png)

**Comment by asinghvi17** [comment] 2019-09-14 22:43
What's the output of `]status FFMPEG`?

**Comment by aerdely** [comment] 2019-09-15 06:28
@asinghvi17 
pkg> status FFMPEG
    Status `C:\Users\aerde\.juliapro\JuliaPro_v1.2.0-1\environments\v1.2\Project.toml`
  [c87230d0] FFMPEG v0.2.2

**Comment by mkborregaard** [comment] 2019-09-18 06:33
cf https://discourse.julialang.org/t/problem-installing-plots-jl-a-ffmpeg-issue/28766

**Comment by mkborregaard** [comment] 2019-09-18 06:35
@daschw any idea why we get this? Plots should not try to install ffmpeg I believe? (or it should, but it doesn't). Is there some change in the build step that calls on our tests?

**Comment by SimonDanisch** [comment] 2019-09-18 09:10
I think after moving FFMPEG to BinaryProvider, we decided it's ok to depend on it...
Can you try: `add FFMPEG#sd-download; build FFMPEG`

**Comment by mkborregaard** [comment] 2019-09-18 10:11
Ah sorry, haven't been following the developments closely enough then.

**Comment by rolfdstoll** [comment] 2019-09-18 15:35
> 
> 
> I think after moving FFMPEG to BinaryProvider, we decided it's ok to depend on it...
> Can you try: `add FFMPEG#sd-download; build FFMPEG`

Thanks, that helped. I could install plots now

**Comment by SimonDanisch** [comment] 2019-09-26 13:57
This fix is on the newest tagged version... If that version doesn't work, there is an additional improvement on FFMPEG#master

**Comment by TeeKay18** [comment] 2019-10-05 18:25
> I think after moving FFMPEG to BinaryProvider, we decided it's ok to depend on it...
> Can you try: `add FFMPEG#sd-download; build FFMPEG`

I had exactly the same problem as aerdely (screenshot with precompiling Plots), I tried and this happened: 
![image](https://user-images.githubusercontent.com/20844643/66259158-02deea80-e7ae-11e9-8a24-faa81cf154cf.png)

Any idea what should I do here? I'm stuck on it for a few hours at least, I'm new to Julia. Thank you in advance.

**Comment by giordano** [comment] 2019-10-05 18:29
The branch `sd-download` doesn't exist anymore after PR https://github.com/JuliaIO/FFMPEG.jl/pull/16 has been merged, use `master` instead.

**Comment by TeeKay18** [comment] 2019-10-05 18:38
Didn't work either.
![image](https://user-images.githubusercontent.com/20844643/66259320-e774df00-e7af-11e9-96ee-9d53acdb97da.png)

**Comment by giordano** [comment] 2019-10-05 18:42
The error you get at the ends looks like this: https://stackoverflow.com/questions/49140930/powershell-script-fails-during-remote-execution-but-works-locally

**Comment by giordano** [comment] 2019-10-05 18:47
See also this thread on discourse: https://discourse.julialang.org/t/problems-with-codeczlib/10124

**Comment by TeeKay18** [comment] 2019-10-05 20:12
After updating Powershell to version 5.1 from 2.0 (I'm on Windows 7 SP1, 32 bit), I got exactly the same error as user kongdd in this topic: (his log under writing "Thanks in advance!") 
https://github.com/JuliaIO/FFMPEG.jl/issues/12

What seems to have finally done the job is this: 
![image](https://user-images.githubusercontent.com/20844643/66260294-16de1880-e7bd-11e9-9c8e-f074133bb3a8.png) 

"using Plots" doesn't make an error anymore. 

For now, thanks very much for your help @giordano :) If anything wrong happened later I will ask but for now everything's fine.

**Comment by giordano** [comment] 2019-10-05 20:17
I don't see any error in this screenshot

**Comment by TeeKay18** [comment] 2019-10-05 20:48
Yes, it definitely works with that fork, you've done a great job. I've also successfully made my first simple plot in Julia and that was my main goal here :)

**Comment by aerdely** [comment] 2019-10-06 17:58
@giordano 's fork worked for me, also.

**Comment by aminya** [comment] 2019-10-13 01:09
I still have the problem. Adding everything master doesn't work

**Comment by VasilijeBursac** [comment] 2019-10-29 01:15
It still doesn't work for me, even after `]add https://github.com/giordano/FFMPEG.jl#tmp` . Any solutions?
![greska](https://user-images.githubusercontent.com/53561957/67729590-f5560280-f9f1-11e9-9ad0-18a0915c6be2.jpg)

**Comment by giordano** [comment] 2019-10-29 01:33
@VasilijeBursac I should have fixed it.  Try to update:
```
]update
```

**Comment by VasilijeBursac** [comment] 2019-10-29 09:01
It still doesn't work. If I have done something wrong, tell me, because I started using Julia yesterday, so I  am still getting used to it.
![1](https://user-images.githubusercontent.com/53561957/67752285-04a97000-fa33-11e9-8faa-6034701c1174.jpg)
![2](https://user-images.githubusercontent.com/53561957/67752286-04a97000-fa33-11e9-8388-8b077c3c95bc.jpg)

**Comment by giordano** [comment] 2019-10-29 09:06
It's all right 🙂 In the package manager mode (the one you enter with `]`, run the command
```
build FFMPEG
```
I'm sorry about this mess, we're in the process of improving user experience about installing binary dependencies like ffmpeg, this should get much smoother in the next few weeks

**Comment by VasilijeBursac** [comment] 2019-10-29 10:15
No problem, I completely understand you.
I'm sorry for bothering you, but I keep getting the error...
![3](https://user-images.githubusercontent.com/53561957/67757988-1f80e200-fa3d-11e9-9cb6-03aa9677e3c8.jpg)

**Comment by giordano** [comment] 2019-10-29 10:37
Could you please copy here the error message rather than posting screenshots?  It makes it easier for use to help you having the plain-text (for example to try and see what's wrong with the download)

**Comment by VasilijeBursac** [comment] 2019-10-29 10:41
Sure! Sorry 
```
Error: Error building `FFMPEG`:
┌ Warning: On Windows, creating file symlinks requires Administrator privileges
└ @ Base.Filesystem file.jl:797
[ Info: Downloading https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.6+1/Bzip2.v1.0.6.x86_64-w64-mingw32.tar.gz to C:\Users\Hp Workstation\.julia\
usr\downloads\Bzip2.v1.0.6.x86_64-w64-mingw32.tar.gz...
ERROR: LoadError: LoadError: Could not download https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.6+1/Bzip2.v1.0.6.x86_64-w64-mingw32.tar.gz to C:\
\packages\FFMPEG\MsCzM\deps\usr\downloads\Bzip2.v1.0.6.x86_64-w64-mingw32.tar.gz:
ErrorException("")
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] #download#93(::Bool, ::typeof(BinaryProvider.download), ::String, ::String) at C:\Users\Hp Workstation\.julia\packages\BinaryProvider\gnxnM\src\PlatformEngines.jl:502
 [3] #download at .\none:0 [inlined]
 [4] #download_verify#94(::Bool, ::Bool, ::Bool, ::typeof(download_verify), ::String, ::String, ::String) at C:\Users\Hp Workstation\.julia\packages\BinaryProvider\gnxnM\src\Plat
 [5] #download_verify at .\tuple.jl:0 [inlined]
 [6] #install#133(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::typeof(install), ::String, ::String) at C:\Users\Hp Workstation\.julia\packages\BinaryProvider\gnxnM\src\Prefix.jl
 [7] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at .\tuple.jl:
 [8] top-level scope at C:\Users\Hp Workstation\.julia\packages\FFMPEG\MsCzM\deps\build_Bzip2.v1.0.6.jl:44
 [9] include at .\boot.jl:328 [inlined]
 [10] include_relative(::Module, ::String) at .\loading.jl:1094
 [11] include at .\Base.jl:31 [inlined]
 [12] include(::String) at C:\Users\Hp Workstation\.julia\packages\FFMPEG\MsCzM\deps\build.jl:53
 [13] top-level scope at C:\Users\Hp Workstation\.julia\packages\FFMPEG\MsCzM\deps\build.jl:54
 [14] include at .\boot.jl:328 [inlined]
 [15] include_relative(::Module, ::String) at .\loading.jl:1094
 [16] include(::Module, ::String) at .\Base.jl:31
 [17] include(::String) at .\client.jl:431
 [18] top-level scope at none:5
in expression starting at C:\Users\Hp Workstation\.julia\packages\FFMPEG\MsCzM\deps\build_Bzip2.v1.0.6.jl:42
in expression starting at C:\Users\Hp Workstation\.julia\packages\FFMPEG\MsCzM\deps\build.jl:46
caused by [exception 2]

Stacktrace:
 [1] error() at .\error.jl:42
 [2] #download#93(::Bool, ::typeof(BinaryProvider.download), ::String, ::String) at C:\Users\Hp Workstation\.julia\packages\BinaryProvider\gnxnM\src\PlatformEngines.jl:496
 [3] #download at .\none:0 [inlined]
 [4] #download_verify#94(::Bool, ::Bool, ::Bool, ::typeof(download_verify), ::String, ::String, ::String) at C:\Users\Hp Workstation\.julia\packages\BinaryProvider\gnxnM\src\Plat
 [5] #download_verify at .\tuple.jl:0 [inlined]
 [6] #install#133(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::typeof(install), ::String, ::String) at C:\Users\Hp Workstation\.julia\packages\BinaryProvider\gnxnM\src\Prefix.jl
 [7] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at .\tuple.jl:
 [8] top-level scope at C:\Users\Hp Workstation\.julia\packages\FFMPEG\MsCzM\deps\build_Bzip2.v1.0.6.jl:44
 [9] include at .\boot.jl:328 [inlined]
 [10] include_relative(::Module, ::String) at .\loading.jl:1094
 [11] include at .\Base.jl:31 [inlined]
 [12] include(::String) at C:\Users\Hp Workstation\.julia\packages\FFMPEG\MsCzM\deps\build.jl:53
 [13] top-level scope at C:\Users\Hp Workstation\.julia\packages\FFMPEG\MsCzM\deps\build.jl:54
 [14] include at .\boot.jl:328 [inlined]
 [15] include_relative(::Module, ::String) at .\loading.jl:1094
 [16] include(::Module, ::String) at .\Base.jl:31
 [17] include(::String) at .\client.jl:431
 [18] top-level scope at none:5
caused by [exception 1]
IOError: symlink: operation not permitted (EPERM)
Stacktrace:
 [1] uv_error at .\libuv.jl:90 [inlined]
 [2] symlink(::String, ::String) at .\file.jl:800
 [3] probe_symlink_creation(::String) at C:\Users\Hp Workstation\.julia\packages\BinaryProvider\gnxnM\src\PlatformEngines.jl:121
 [4] #probe_platform_engines!#30(::Bool, ::typeof(BinaryProvider.probe_platform_engines!)) at C:\Users\Hp Workstation\.julia\packages\BinaryProvider\gnxnM\src\PlatformEngines.jl:
 [5] probe_platform_engines! at C:\Users\Hp Workstation\.julia\packages\BinaryProvider\gnxnM\src\PlatformEngines.jl:169 [inlined]
 [6] __init__() at C:\Users\Hp Workstation\.julia\packages\BinaryProvider\gnxnM\src\BinaryProvider.jl:28
 [7] _include_from_serialized(::String, ::Array{Any,1}) at .\loading.jl:685
 [8] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:765
 [9] _require(::Base.PkgId) at .\loading.jl:990
 [10] require(::Base.PkgId) at .\loading.jl:911
 [11] require(::Module, ::Symbol) at .\loading.jl:906
 [12] include at .\boot.jl:328 [inlined]
 [13] include_relative(::Module, ::String) at .\loading.jl:1094
 [14] include(::Module, ::String) at .\Base.jl:31
 [15] include(::String) at .\client.jl:431
 [16] top-level scope at none:5
Exception setting "SecurityProtocol": "Cannot convert null to type "System.Net.SecurityProtocolType" due to invalid enumeration values. Specify one of the following enumeration v

ossible enumeration values are "Ssl3, Tls"."
At line:1 char:35
+ [System.Net.ServicePointManager]:: <<<< SecurityProtocol =
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

Exception calling "DownloadFile" with "2" argument(s): "The underlying connection was closed: An unexpected error occurred on a send."
At line:5 char:24
+ $webclient.DownloadFile <<<< ("https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.6+1/Bzip2.v1.0.6.x86_64-w64-mingw32.tar.gz", "C:\Users\Hp Workst

EG\MsCzM\deps\usr\downloads\Bzip2.v1.0.6.x86_64-w64-mingw32.tar.gz")
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

@ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Pkg\src\backwards_compatible_isolation.jl:647
```

**Comment by giordano** [comment] 2019-10-29 13:55
@VasilijeBursac it looks like you have issues similar to those in https://discourse.julialang.org/t/problems-with-codeczlib/10124, mentioned also above.  Try upgrading powershell, as suggested in the post marked as solution

**Comment by VasilijeBursac** [comment] 2019-10-29 20:40
@giordano Thank you! I upgraded powershell, and the error is gone! Problem solved!

**Comment by giordano** [comment] 2019-10-29 21:26
You're welcome! I'm glad you were able to fix that.

The hope is that in the the future we'll be able to use a reliable pure-julia client for download, to eliminate all differences on different platforms, see https://github.com/JuliaLang/julia/issues/27043

**Comment by VasilijeBursac** [comment] 2019-10-29 21:41
@giordano It's nice to hear that! Keep up the great work!

**Comment by aminya** [comment] 2019-10-29 23:43
> The hope is that in the the future we'll be able to use a reliable pure-julia client for download, to eliminate all differences on different platforms, see [JuliaLang/julia#27043](https://github.com/JuliaLang/julia/issues/27043)

But that future isn't near future. `Base.download` isn't used much. The issue is open since 2018. So stick to current solutions instead of waiting for that.

**Closed** 2019-10-30 08:19 UTC

**Comment by VasilijeBursac** [comment] 2019-10-30 11:39
@aminya Sure! Thanks for advice!

**Comment by arseny-sandaar** [comment] 2020-12-24 12:10
Hello,
I had the same problem with FFMPEG and I followed all the instructions proposed here.
24 Dec 2020
Julia 1..0, atom 1.53.0x64, Windows 10
This what I've got:
```
julia> using Plots
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
Deps path: C:\Users\Arsenii.Sleptsov\.julia\packages\FFMPEG\MsCzM\src\..\deps\deps.jl
ERROR: LoadError: FFMPEG not installed properly, run `] build FFMPEG`, restart Julia and try again
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] top-level scope at C:\Users\Arsenii.Sleptsov\.julia\packages\FFMPEG\MsCzM\src\FFMPEG.jl:18
 [3] include at .\boot.jl:328 [inlined]
 [4] include_relative(::Module, ::String) at .\loading.jl:1094
 [5] include(::Module, ::String) at .\Base.jl:31
 [6] top-level scope at none:2
 [7] eval at .\boot.jl:330 [inlined]
 [8] eval(::Expr) at .\client.jl:432
 [9] top-level scope at .\none:3
in expression starting at C:\Users\Arsenii.Sleptsov\.julia\packages\FFMPEG\MsCzM\src\FFMPEG.jl:16
ERROR: LoadError: Failed to precompile FFMPEG [c87230d0-a227-11e9-1b43-d7ebe4e7570a] to C:\Users\Arsenii.Sleptsov\.julia\compiled\v1.2\FFMPEG\TGvga.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1253
 [3] _require(::Base.PkgId) at .\loading.jl:1013
 [4] require(::Base.PkgId) at .\loading.jl:911
 [5] require(::Module, ::Symbol) at .\loading.jl:906
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1094
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:432
 [12] top-level scope at .\none:3
in expression starting at C:\Users\Arsenii.Sleptsov\.julia\packages\Plots\u8HRI\src\Plots.jl:15
ERROR: Failed to precompile Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80] to C:\Users\Arsenii.Sleptsov\.julia\compiled\v1.2\Plots\ld3vC.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1253
 [3] _require(::Base.PkgId) at .\loading.jl:1013
 [4] require(::Base.PkgId) at .\loading.jl:911
 [5] require(::Module, ::Symbol) at .\loading.jl:906
```
as it was suggested in the error message I tried ']build FFMPEG'

```
(v1.2) pkg>  build FFMPEG
  Building FFMPEG → `C:\Users\Arsenii.Sleptsov\.julia\packages\FFMPEG\MsCzM\deps\build.log`
┌ Error: Error building `FFMPEG`: 
│ ERROR: LoadError: LoadError: UndefVarError: PlatformEngines not defined
│ Stacktrace:
│  [1] redirect_download_engine(::getfield(BinaryProvider, Symbol("##56#85")){getfield(BinaryProvider, Symbol("##51#80")){Cmd,String}}) at C:\Users\Arsenii.Sleptsov\.julia\packages\BinaryProvider\IjWSK\src\JuliaTeam.jl:14│  [2] (::getfield(BinaryProvider, Symbol("##60#89")))(::String, ::String) at C:\Users\Arsenii.Sleptsov\.julia\packages\BinaryProvider\IjWSK\src\PlatformEngines.jl:519
│  [3] #download#106(::Bool, ::typeof(BinaryProvider.download), ::String, ::String) at C:\Users\Arsenii.Sleptsov\.julia\packages\BinaryProvider\IjWSK\src\PlatformEngines.jl:607
│  [4] #download at .\none:0 [inlined]
│  [5] #download_verify#107(::Bool, ::Bool, ::Bool, ::typeof(download_verify), ::String, ::String, ::String) at C:\Users\Arsenii.Sleptsov\.julia\packages\BinaryProvider\IjWSK\src\PlatformEngines.jl:692
│  [6] #download_verify at .\tuple.jl:0 [inlined]
│  [7] #install#147(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::typeof(install), ::String, ::String) at C:\Users\Arsenii.Sleptsov\.julia\packages\BinaryProvider\IjWSK\src\Prefix.jl:314
│  [8] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at .\tuple.jl:0
│  [9] top-level scope at C:\Users\Arsenii.Sleptsov\.julia\packages\FFMPEG\MsCzM\deps\build_Bzip2.v1.0.6.jl:44
│  [10] include at .\boot.jl:328 [inlined]
│  [11] include_relative(::Module, ::String) at .\loading.jl:1094
│  [12] include at .\Base.jl:31 [inlined]
│  [13] include(::String) at C:\Users\Arsenii.Sleptsov\.julia\packages\FFMPEG\MsCzM\deps\build.jl:53
│  [14] top-level scope at C:\Users\Arsenii.Sleptsov\.julia\packages\FFMPEG\MsCzM\deps\build.jl:54
│  [15] include at .\boot.jl:328 [inlined]
│  [16] include_relative(::Module, ::String) at .\loading.jl:1094
│  [17] include(::Module, ::String) at .\Base.jl:31
│  [18] include(::String) at .\client.jl:431
│  [19] top-level scope at none:5
│ in expression starting at C:\Users\Arsenii.Sleptsov\.julia\packages\FFMPEG\MsCzM\deps\build_Bzip2.v1.0.6.jl:42
│ in expression starting at C:\Users\Arsenii.Sleptsov\.julia\packages\FFMPEG\MsCzM\deps\build.jl:46
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Pkg\src\backwards_compatible_isolation.jl:647
```

then I tried 'add FFMPEG#sd-download; build FFMPEG'

```
(v1.2) pkg> add FFMPEG#sd-download; build FFMPEG
  Updating git-repo `https://github.com/JuliaIO/FFMPEG.jl.git`
  Updating git-repo `https://github.com/JuliaIO/FFMPEG.jl.git`
ERROR: git object sd-download could not be found
```
I found out that I had to use `master` which gave an error
```
(v1.2) pkg> add FFMPEG#master; build FFMPEG
  Updating git-repo `https://github.com/JuliaIO/FFMPEG.jl.git`
 Resolving package versions...
┌ Warning: julia version requirement for package FFMPEG not satisfied
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Pkg\src\Operations.jl:225
ERROR: Unsatisfiable requirements detected for package FFMPEG [c87230d0]:
 FFMPEG [c87230d0] log:
 ├─possible versions are: 0.4.0 or uninstalled
 ├─FFMPEG [c87230d0] is fixed to version 0.4.0
 └─found to have no compatible versions left with Plots [91a5bcdd] 
   └─Plots [91a5bcdd] log:
     ├─possible versions are: [0.12.1-0.12.4, 0.13.0-0.13.1, 0.14.0-0.14.2, 0.15.0-0.15.1, 0.16.0, 0.17.0-0.17.4, 0.18.0, 0.19.0-0.19.3, 0.20.0-0.20.6, 0.21.0, 0.22.0-0.22.5, 0.23.0-0.23.2, 0.24.0, 0.25.0-0.25.3, 0.26.0-0.26.3, 0.27.0-0.27.1, 0.28.0-0.28.4, 0.29.0-0.29.9, 1.0.0-1.0.14, 1.1.0-1.1.4, 1.2.0-1.2.6, 1.3.0-1.3.7, 1.4.0-1.4.4, 1.5.0-1.5.9, 1.6.0-1.6.3] or uninstalled
     └─restricted to versions 1.4.4 by an explicit requirement, leaving only versions 1.4.4
```

I proceeded with the following ']add https://github.com/giordano/FFMPEG.jl#tmp' and it gave an error:

```
(v1.2) pkg> add https://github.com/giordano/FFMPEG.jl#tmp
  Updating git-repo `https://github.com/giordano/FFMPEG.jl`
  Updating git-repo `https://github.com/giordano/FFMPEG.jl`
 Resolving package versions...
  Updating `C:\Users\Arsenii.Sleptsov\.julia\environments\v1.2\Project.toml`
 [no changes]
  Updating `C:\Users\Arsenii.Sleptsov\.julia\environments\v1.2\Manifest.toml`
 [no changes]

(v1.2) pkg> build FFMPEG
  Building FFMPEG → `C:\Users\Arsenii.Sleptsov\.julia\packages\FFMPEG\MsCzM\deps\build.log`
┌ Error: Error building `FFMPEG`: 
│ ERROR: LoadError: LoadError: UndefVarError: PlatformEngines not defined
│ Stacktrace:
│  [1] redirect_download_engine(::getfield(BinaryProvider, Symbol("##56#85")){getfield(BinaryProvider, Symbol("##51#80")){Cmd,String}}) at C:\Users\Arsenii.Sleptsov\.julia\packages\BinaryProvider\IjWSK\src\JuliaTeam.jl:14│  [2] (::getfield(BinaryProvider, Symbol("##60#89")))(::String, ::String) at C:\Users\Arsenii.Sleptsov\.julia\packages\BinaryProvider\IjWSK\src\PlatformEngines.jl:519
│  [3] #download#106(::Bool, ::typeof(BinaryProvider.download), ::String, ::String) at C:\Users\Arsenii.Sleptsov\.julia\packages\BinaryProvider\IjWSK\src\PlatformEngines.jl:607
│  [4] #download at .\none:0 [inlined]
│  [5] #download_verify#107(::Bool, ::Bool, ::Bool, ::typeof(download_verify), ::String, ::String, ::String) at C:\Users\Arsenii.Sleptsov\.julia\packages\BinaryProvider\IjWSK\src\PlatformEngines.jl:692
│  [6] #download_verify at .\tuple.jl:0 [inlined]
│  [7] #install#147(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::typeof(install), ::String, ::String) at C:\Users\Arsenii.Sleptsov\.julia\packages\BinaryProvider\IjWSK\src\Prefix.jl:314
│  [8] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at .\tuple.jl:0
│  [9] top-level scope at C:\Users\Arsenii.Sleptsov\.julia\packages\FFMPEG\MsCzM\deps\build_Bzip2.v1.0.6.jl:44
│  [10] include at .\boot.jl:328 [inlined]
│  [11] include_relative(::Module, ::String) at .\loading.jl:1094
│  [12] include at .\Base.jl:31 [inlined]
│  [13] include(::String) at C:\Users\Arsenii.Sleptsov\.julia\packages\FFMPEG\MsCzM\deps\build.jl:53
│  [14] top-level scope at C:\Users\Arsenii.Sleptsov\.julia\packages\FFMPEG\MsCzM\deps\build.jl:54
│  [15] include at .\boot.jl:328 [inlined]
│  [16] include_relative(::Module, ::String) at .\loading.jl:1094
│  [17] include(::Module, ::String) at .\Base.jl:31
│  [18] include(::String) at .\client.jl:431
│  [19] top-level scope at none:5
│ in expression starting at C:\Users\Arsenii.Sleptsov\.julia\packages\FFMPEG\MsCzM\deps\build_Bzip2.v1.0.6.jl:42
│ in expression starting at C:\Users\Arsenii.Sleptsov\.julia\packages\FFMPEG\MsCzM\deps\build.jl:46
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Pkg\src\backwards_compatible_isolation.jl:647
```

I tried ']update' and it didn't work

Finally, I updated my Powershell on windows and repeated everything: it didn't work.

Please, could you help with this issue?
What I am doing wrong?

**Comment by giordano** [comment] 2020-12-24 12:13
Any chance of updating Julia to the [current stable version](https://julialang.org/downloads/#current_stable_release) (v1.5.3 as of today)?  Julia v1.2 is unsupported, nothing we can do for that version

**Comment by arseny-sandaar** [comment] 2020-12-24 13:59
> Any chance of updating Julia to the [current stable version](https://julialang.org/downloads/#current_stable_release) (v1.5.3 as of today)? Julia v1.2 is unsupported, nothing we can do for that version

Thanks, it works now.
