### ISSUE TITLE
The label of the second y axis on the right is partially missing

### ISSUE THREAD

**Issue by hurricane007** [JuliaPlots/Plots.jl#2636] opened 2020-04-26 12:28 UTC
Hello, 
there is one strange behavior when plotting the second y-axis. for example, the code below gives a figure whose right y label is partially cut. 

```julia
using Plots, LaTeXStrings
a = 1:10
b = rand(10)
plot(a,b, label = "randData", ylabel = "Rand data",color = :red, 
    legend = :topleft, grid = :off, xlabel = "numbers")
p = twinx()
plot!(p,a,log.(a), label = L"log(x)", legend = :topright, 
     box = :on, grid = :off, ylabel = "y label 2")
```
![image](https://user-images.githubusercontent.com/16286632/80307494-b69adc80-87c9-11ea-9ffa-1a6f19167913.png)
However, if we added a savefig after, the second y label magically shown up.  
Does anyone know what is the reason? 
In addition, is it possible to add an example of drawing the second y-axis in the tutorial? 
![image](https://user-images.githubusercontent.com/16286632/80307546-feb9ff00-87c9-11ea-9ef3-ae5666daba87.png)

**Comment by BeastyBlacksmith** [comment] 2020-04-26 12:46
Is it correct, that this is using the GR backend in a jupyter notebook?

**Comment by BeastyBlacksmith** [comment] 2020-04-26 12:50
I can confirm that this also happens with GR from the terminal, but I can resize the window to fit the label.

**Comment by hurricane007** [comment] 2020-04-26 19:39
I was using pyplot in notebook. 
I tried in REPL and found the same behavior. It's possible to resize the window to show the right Y label.

**Comment by BeastyBlacksmith** [comment] 2020-04-28 12:52
duplicate of https://github.com/JuliaPlots/Plots.jl/issues/2205

**Comment by BeastyBlacksmith** [comment] 2020-04-28 12:56
Solution would be to add the `guidefontsize` to the right margin

**Comment by jessebett** [comment] 2020-06-04 03:12
I am also hitting this issue where it's cutting off axis labels.

**Comment by benfolsom** [comment] 2020-08-20 09:15
You can use the left_margin and right_margin commands. Note that it uses "mm" which is deprecated, so you need to load it from Plots.Measures or do as below.

```
a = 1:10
b = rand(10)
plot(a,b, label = "randData", ylabel = "Rand data",color = :red, 
    legend = :topleft, grid = :off, xlabel = "numbers",left_margin = 5Plots.mm, right_margin = 15Plots.mm)
p = twinx()
plot!(p,a,log.(a), label = L"log(x)", legend = :topright, 
     box = :on, grid = :off, ylabel = "y label 2",left_margin = 5Plots.mm, right_margin = 15Plots.mm)
```

See  #220

**Closed** 2022-11-01 20:10 UTC
Labels: bug, duplicate, GR, PyPlot, documentation - API
