### ISSUE TITLE
no longer possible to have multiple plot windows

### ISSUE THREAD

**Issue by lewisl** [JuliaPlots/Plots.jl#2057] opened 2019-06-08 01:02 UTC
Like the title says,
```
plot(1:4)
plot(7:10)
```
One plot window is updated:  the line with 1:4 as x axis and y, becomes a plot of 2 series as if the second command was plot!(7:10).

I loved plots: it's elegance and simplicity and the great appearance that could be achieved with plot themes.  I am giving up.  Two many bugs, instabilities and inconsisitencies.

PyPlot is a big ugly, harder to use, but works.

GR crashes or hangs Plots.  Reported several times over at GR.jl.  J.Heinen can't reproduce it.  It's probably a Plots issue.

I'd use GR directly but there is essentially no documentation for it's direct Julia API.

I'll give PlotlyJS' direct API a shot, but last I looked over a year ago there wasn't much documentation for it.  That might well be improved.

Except for PyPlot, the state of Julia plotting remains parlous.  Too many fragmented efforts. Karpinski should bang some heads together, get everyone to work on ONE, and get some financial support for a small team.  All the others can do whatever they want, but without support.

**Comment by andyDoucette** [comment] 2021-08-18 01:35
+1  This is a very important feature!

**Comment by t-bltg** [comment] 2021-09-25 09:39
Duplicate of https://github.com/JuliaPlots/Plots.jl/issues/822.

**Closed by t-bltg** 2021-09-25 09:39 UTC
