### ISSUE TITLE
Pie chart legend is cut

### ISSUE THREAD

**Issue by my-little-repository** [JuliaPlots/Plots.jl#602] opened 2016-12-06 10:02 UTC
When plotting a pie chart using the gr backend, the legend of some pieces of the pie does not appear on screen. The viewport is too small and the legend is off screen. In the following example, "3" is offscreen and also off figure if saved.
 
    julia> using Plots; gr()
     Plots.GRBackend()

    julia> pie(["1", "2", "3"], [.4, .1, .5])

I don't know if the problem also happens with the pyplot backend. I am using Julia Version 0.5.0 (2016-09-19 18:14 UTC) together with Plots 0.10.1 and GR  0.18.0.

**Comment by JackDevine** [comment] 2017-02-17 01:57
The margin attribute defaults to 1mm, so a work around would be the following:
```julia
julia> using Plots; gr();

julia> pie(["1", "2", "3"], [.4, .1, .5], margin=2mm)
``` 
I could make a PR where I change src/args.jl so that the default margin size is 2mm, but I am not sure what other effects that would have.

**Comment by mkborregaard** [comment] 2017-09-03 20:26
@my-little-repository why did you close the issue - is it fixed on your system? I still have the issue on GR, and the legends don't show at all on plotlyjs, so it should probably remain open. We will come to it eventually :-)

**Comment by mkborregaard** [comment] 2017-09-03 20:27
@JackDevine I don't think we need to change the overall margin size, just the handling of pie plots.

**Comment by my-little-repository** [comment] 2017-09-03 21:19
@mkborregaard It seems to work now with GR. Everything appears in the window.

     julia> using Plots
     julia> gr()
     Plots.GRBackend()
     julia>  pie(["1", "2", "3"], [.4, .1, .5], title = "some pie")
     julia> Plots.savefig("pie.png")

![pie](https://user-images.githubusercontent.com/5676301/30006679-0d7bf5b8-90fe-11e7-8a6d-0d582a410d97.png)

 I am using Julia v0.6 together with GR 0.23.0 and Plots 0.12.3.

 I didn't try plotlyjs though. I just tried with the plotly backend and the result is a bit weird, the title is over the pie and the labels of the regions only appear on mouseover.

**Comment by mkborregaard** [comment] 2017-09-03 21:26
That's so weird, I still have the error on Plots and GR master :confused:

**Comment by JackDevine** [comment] 2017-09-03 21:34
GR works for me too. PyPlot is also fine. plotly and plotlyjs are not showing the labels at all though.

**Comment by my-little-repository** [comment] 2017-09-03 21:42
Looking at plotly pie [examples](https://plot.ly/python/pie-charts/) it seems that by default, the labels only appear on mouseover. The title should appear on top of the chart though, not on the pie itself.

**Comment by JackDevine** [comment] 2017-09-03 22:01
Yeah, but those examples still have legends on the top right, whereas when I use plotly I don't get a legend

![newplot](https://user-images.githubusercontent.com/8610352/30006885-d76b659a-9156-11e7-844a-3592055dc3db.png)

**Comment by my-little-repository** [comment] 2017-09-03 22:04
@JackDevine Yes indeed, same plot result here.

**Comment by JackDevine** [comment] 2017-09-03 23:45
Ok, I just tested this on OSX and I have the issue of the label being chopped on GR (on linux things were fine). @mkborregaard what operating system are you using?

**Comment by mkborregaard** [comment] 2017-09-04 04:51
MacOS :-) So that explains the discrepancy

**Comment by JackDevine** [comment] 2017-09-04 05:12
Ok, atleast we know what the problem is, maybe we need an osx tag? I am seeing this in Jupyter notebooks as well as GKS term, but I can't really explain why this would only happen on osx.

**Comment by mkborregaard** [comment] 2017-09-04 06:00
Yeah, we have no other examples of different behaviour on MacOS - except pyplot has weird dpi behaviour in retina screens, but not on savefig. This is likely to be in the backends.

**Closed** 2020-04-28 20:01 UTC
Labels: GR, Plotly, good first issue
