### ISSUE TITLE
'link' subplot attribute works with pyplot() but not plotly()

### ISSUE THREAD

**Issue by ko56** [JuliaPlots/Plots.jl#1124] opened 2017-10-02 21:50 UTC
```julia
using Plots
plotly()
scatter(rand(10,6), layout=(3,2), link=:all)
```

The y axes are not identical.  But this works with pyplot().

**Comment by mkborregaard** [comment] 2017-10-03 04:42
Yes, this is a known plotly bug. It's mentioned in the meta-issue but might make sense for it to have its own issue (since this should really be a priority).

**Comment by mkborregaard** [comment] 2017-10-03 06:29
This is likely a duplicate of #850

**Comment by ko56** [comment] 2017-10-03 12:33
I've seen the same problem, but decided to report only the 'link' one.

**Comment by daschw** [comment] 2017-11-20 08:19
Closed by #1253

**Closed by daschw** 2017-11-20 08:19 UTC
Labels: bug, Hacktoberfest, Plotly
