### ISSUE TITLE
[BUG] Log scale with custom ticks errors when using LaTeX tick labels (PGFPlots)

### ISSUE THREAD

**Issue by JamieMair** [JuliaPlots/Plots.jl#4315] opened 2022-08-20 03:30 UTC
## Details

The following code runs as expected, allowing LaTeX math expressions to be used as custom ticks:
```julia
using Plots
using LaTeXStrings
pgfplotsx()

xvals = 1:10
yvals = rand(length(xvals))
plot(xvals, yvals, legend=false, xscale=:log10, xticks=(xvals, (x->LaTeXString("\$ 10 ^ {$x} \$")).(xvals)))
```
However, when using a log scale (as below), this errors:
```julia
using Plots
using LaTeXStrings
pgfplotsx()

xvals = 1:10
yvals = rand(length(xvals))
plot(xvals, yvals, legend=false, xscale=:log10, xticks=(xvals, (x->LaTeXString("\$ 10 ^ {$x} \$")).(xvals)))
```
Using a custom set of xticks is fine as long as the equation does not contain the `^`. 

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     | x
pyplot       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |  x  |     | 
unicodeplots |     |     | x
inspectdr    |     |     | x
gaston       |     |     | x

### Versions

Plots.jl version:  `Plots v1.31.5`
Backend  version (`]st -m <backend(s)>`): `PGFPlotsX v1.5.0`
Output of `versioninfo()`:
```
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: AMD Ryzen Threadripper 3970X 32-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, znver2)
Environment:
  JULIA_NUM_THREADS = 16
  JULIA_EDITOR = code
```

**Comment by t-bltg** [comment] 2022-08-20 07:26
> Plots.jl version: Plots v1.31.5

I can't reproduce on `1.31.7`, can you upgrade `Plots` to the latest release ?

**Comment by t-bltg** [comment] 2022-08-30 09:01
No answer from op, closing.

**Closed** 2022-08-30 09:00 UTC
Labels: bug, PGFPlotsX

**Comment by JamieMair** [comment] 2022-08-31 08:56
I have updated to the most recent version and the code now runs.
