### ISSUE TITLE
Warnings when using pyplot() backend

### ISSUE THREAD

**Issue by BerntLie** [JuliaPlots/Plots.jl#1954] opened 2019-03-13 14:04 UTC
I get some warnings when using `pyplot()` as backend for `Plots` in `IJulia` on my laptop:

![image](https://user-images.githubusercontent.com/28146074/54284978-520ac700-45a1-11e9-976f-2d62420c5ce3.png)

**Comment by isaacsas** [comment] 2019-03-13 14:16
To workaround for now: in the package manager
```
add PyCall@v1.18.5 PyPlot@v2.7.0
pin PyCall PyPlot
```
At least for me that reverted them to a version before the change in API which is causing the warnings.

**Comment by stevengj** [comment] 2019-03-13 15:41
Duplicate of #1932

**Closed** 2019-03-15 14:17 UTC
