### ISSUE TITLE
Allow values to get passed to hline/vline instead of vectors

### ISSUE THREAD

**Issue by djsegal** [JuliaPlots/Plots.jl#2575] opened 2020-04-13 20:01 UTC
Right now you get an error:

```
scatter(rand(100))
hline!(0.5)
```

---

```
Cannot convert Float64 to series data for plotting

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] prepareSeriesData(::Float64) at /Users/dan/.julia/packages/Plots/cc8wh/src/series.jl:14
 [3] convertToAnyVector(::Float64, ::Dict{Symbol,Any}) at /Users/dan/.julia/packages/Plots/cc8wh/src/series.jl:29
 [4] macro expansion at /Users/dan/.julia/packages/Plots/cc8wh/src/series.jl:129 [inlined]
 [5] apply_recipe(::Dict{Symbol,Any}, ::Type{Plots.SliceIt}, ::Nothing, ::Float64, ::Nothing) at /Users/dan/.julia/packages/RecipesBase/G4s6f/src/RecipesBase.jl:279
```

// this should just automatically cast the hline or vline like: 

> **`hline([0.5])`**

**Comment by BeastyBlacksmith** [comment] 2020-04-14 06:04
If this is going to be done, we shouldn't specialize `hline`/`vline`, but generally allow things like `scatter(0.2,0.3)`.

**Comment by mkborregaard** [comment] 2020-04-14 08:42
Note that `scatter(2)` does something different.
I disagree with
> this should just automatically cast the hline or vline

A distinction between vectors and scalars is exactly what makes julia nicer than R IMHO

**Comment by BeastyBlacksmith** [comment] 2020-04-14 08:52
> Note that `scatter(2)` (using an Int rather than a float) does something different (opens an empty plot with 2 subplots).

Which I do find surprising

**Comment by mkborregaard** [comment] 2020-04-14 09:01
Maybe? At least it's the current behaviour and some users depend on it (useful for live updating plots where you gradually push to the series)

**Comment by daschw** [comment] 2020-04-14 09:43
`plt = plot(2)` creates a plot with 2 empty series (in one subplot). Then you can push a point to the ith series with `push!(plt, i, (x, y))`.

**Comment by mkborregaard** [comment] 2020-04-14 09:54
haha thanks @daschw I must have misremembered or used it with `layout = 2`

**Comment by BeastyBlacksmith** [comment] 2020-04-28 18:46
duplicate of https://github.com/JuliaPlots/Plots.jl/issues/2129

**Comment by Gyoshi** [comment] 2020-06-16 07:34
I would find it much more intuitive if the methods were at least called `hlines` and `vlines` to indicate that they take an array of values. 

Well, maybe that is not the ideal solution, but when so many things "just work", it is honestly flabbergasting not to have something as straightforward as `hline!(3.1)` work.

**Comment by juliohm** [comment] 2020-08-01 17:40
Should this be closed as a duplicate?

**Closed** 2020-08-03 09:13 UTC
Labels: discussion, duplicate
