### ISSUE TITLE
Julia Plots: It's the difference between the numbers that is too small.

### ISSUE THREAD

**Issue by damonturney** [JuliaPlots/Plots.jl#2380] opened 2020-02-04 15:34 UTC
Quoting "It's the difference between the numbers that is too small" from @mkborregaard in https://github.com/JuliaPlots/Plots.jl/issues/1860#issuecomment-444826895_

plot([0; 1.0],  [ 0.12000000000; 0.12000000003] , ylims=(0.12000000000,0.12000000002) )
leads to the error:
GKS: Rectangle definition is invalid in routine SET_WINDOW
and the plot fails.  In other words, Plots can't plot a difference of 12 significant digits of precision.

but
plot([0; 1.0],  [ 0.1200000000; 0.1200000003] , ylims=(0.1200000000,0.1200000002) )
works fine. In other words, Plots can handle a difference of 11 significant digits of precision but cannot handle a difference of 12 significant digits of precision.

This bug isn't benign!  Many users need to plot "small differences".  Double precision computation gives us 15 significant digits and users rightfully want to be able to plot with all of these significant digits, not just the first 11 significant digits. Julia is supposed to be a "high performance computation" language, so I think Plots should be able to plot more than 11 significant digits of precision .

For example: Python's matplotlib has no problem plotting "small differences" down to the 15th significant digit of precision. So let's please fix Julia's Plots.

**Comment by timholy** [comment] 2020-02-04 16:01
What you're reporting is a bug, not an moral failure on the part of Plots developers. Keep it friendly!

**Comment by damonturney** [comment] 2020-02-04 16:26
Tim, very much agreed!  I'm very grateful for all of your work, and love Julia, but this bug has been known for about 3 years and the response to users when they reported it since 2018 has been [paraphrased] "don't try to plot small differences, case closed". 

So I'm just trying to push us past that philosophy.  I definitely didn't consider it a "moral failure"!! Best regards.

**Comment by SimonDanisch** [comment] 2020-02-04 16:31
Plots is maintained by a few volunteers with way too little time at their hands. The only way to really "push us past that" is doing the actual work, or paying someone for it ;)

**Comment by damonturney** [comment] 2020-02-04 16:37
I hear you.  Mea Culpa!  My bad.... I should have phrased a more friendly request.  True story.
Apologies.

**Comment by timholy** [comment] 2020-02-04 17:20
I've not done this myself, but if I were fixing it I'd start by running this in the Juno debugger and checking "Break on uncaught exception" and then work my way back up the stack to figure out where the problem originates from. Want to give it a try yourself and see if you can fix it? (`dev` the package first.)

**Comment by mkborregaard** [comment] 2020-02-04 17:20
I think this might be an issue with GR or with the GR Plots backend, as the code works with the plotly and pyplot backends (sort of, the y axis labels round away the difference). But in pure GR you get 
```
julia> plot([0; 1.0], [ 0.12000000000; 0.12000000003])
julia(19558,0x112c865c0) malloc: can't allocate region
*** mach_vm_map(size=18446744071562072064) failed (error code=3)
julia(19558,0x112c865c0) malloc: *** set a breakpoint in malloc_error_break to debug
GKS: can't re-allocate memory
```
cc @jheinen

**Comment by mkborregaard** [comment] 2020-02-04 17:21
I'm closing this as a duplicate of #1860. @damonturney you're welcome to transfer your comments there.

**Closed by mkborregaard** 2020-02-04 17:22 UTC
