### ISSUE TITLE
Finite value error with yscale=:log10

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPlots/Plots.jl#455] opened 2016-08-23 19:21 UTC
Example:

``` julia
using Plots
plot(rand(4),seriestype=:bar) # Works fine
plot(rand(4),seriestype=:bar,yscale=:log10) # crashes Julia
```

I just get the error `At least one finite value must be provided to formatter.` and Julia crashes. This happens at least on PyPlot and Plotly.

**Comment by tbreloff** [comment] 2016-09-06 13:36
- I don't get this crash, only the "finite value" error
- The "finite value" error could be solved either by changing your axis limits, or by changing where the bars are filled to:

```julia
using Plots
bar(rand(4),yscale=:log10, fillto=1e-2)
```

The problem is that the default fills to 0, which is -Inf in log space.  Note: `fillto` is an alias to `fillrange`

**Comment by mkborregaard** [comment] 2017-05-16 08:54
Fixed in https://github.com/JuliaPlots/Plots.jl/pull/800

**Closed by mkborregaard** 2017-05-16 08:54 UTC
Labels: bug
