### ISSUE TITLE
[BUG] failing tick calculation in narrow log-log plots

### ISSUE THREAD

**Issue by psanan** [JuliaPlots/Plots.jl#3790] opened 2021-09-02 14:13 UTC
## Details

In attempting to plot data on a log-log plot, with

```
x = [0.0625, 0.03125, 0.015625, 0.0078125, 0.00390625]
y = [0.08803057664711, 0.022532873837507062, 0.005666348468055831, 0.00141866249195611, 0.0003547954142212406]
gr()
plot(x, y, xaxis=:log, yaxis=:log)
```
the resulting plot has no x ticks and warnings are emitted:
```
 Warning: No strict ticks found
└ @ PlotUtils HOME_DIR_SCRUBBED/.julia/packages/PlotUtils/xCNES/src/ticks.jl:295
┌ Warning: No strict ticks found
└ @ PlotUtils HOME_DIR_SCRUBBED/.julia/packages/PlotUtils/xCNES/src/ticks.jl:295
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |     |     | x
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |  x   |     |
inspectdr    |     |     | x

### Versions

Plots.jl version: 1.21.2
Backend  version (`]st -m <backend(s)>`):
Output of `versioninfo()`:

```
Julia Version 1.6.2                                                                                                                      
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)                                                                                        
Platform Info:                                                                                                                           
  OS: Linux (x86_64-pc-linux-gnu)                                                                                                        
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz                                                                                           
  WORD_SIZE: 64                                                                                                                          
  LIBM: libopenlibm                                                                                                                      
  LLVM: libLLVM-11.0.1 (ORCJIT, haswell)                                                                                                 
Environment:                                                                                                                             
  JULIA_DIR = HOME_DIR_SCRUBBED/code/julia      
```

**Comment by psanan** [comment] 2021-09-03 06:17
I believe that I did not always see this warning, but unfortunately I don't have the exact version numbers for the working case (though I was using Julia 1.5.x).

**Comment by t-bltg** [comment] 2021-09-14 09:28
Duplicate of https://github.com/JuliaPlots/PlotUtils.jl/issues/116.

**Closed by t-bltg** 2021-09-14 09:28 UTC
Labels: bug, duplicate
