### ISSUE TITLE
Pkg.test("Plots") fails on fresh Julia 0.5 install on win x64

### ISSUE THREAD

**Issue by finmod** [JuliaPlots/Plots.jl#689] opened 2017-02-20 21:50 UTC
Pkg.test("Plots") fails on fresh Julia v0.5 install on win x64. Backends: GR, PlotlyJS, Gtk, PyPlot. 

l:26
 in facts(::PlotsTests.##13#18, ::String) at C:\Users\Denis\.julia\v0.5\FactCheck\src\FactCheck.jl:449
 in include_from_node1(::String) at .\loading.jl:488
 in process_options(::Base.JLOptions) at .\client.jl:262
 in _start() at .\client.jl:318
while loading C:\Users\Denis\.julia\v0.5\Plots\test\runtests.jl, in expression starting on line 118
Error encountered while loading "C:\Users\Denis\AppData\Local\Temp\jl_5DCD.tmp.png".
Fatal error:
WARNING: Image did not match reference image C:\Users\Denis\.julia\v0.5\PlotReferenceImages\Plots\pyplot\0.9.6\ref12.png. err: ErrorException("no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/504")
  Failure :: (line:272) :: fact was false
    Expression: image_comparison_tests(pkg,i,debug=debug,sigma=sigma,eps=eps) |> success --> true
      Expected: true
      Occurred: false
INFO: Testing plot: pyplot:13:Marker types
Error encountered while loading "C:\Users\Denis\AppData\Local\Temp\jl_6168.tmp.png".
Fatal error:
WARNING: Image did not match reference image C:\Users\Denis\.julia\v0.5\PlotReferenceImages\Plots\pyplot\0.9.6\ref13.png. err: ErrorException("no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/504")
  Failure :: (line:272) :: fact was false
    Expression: image_comparison_tests(pkg,i,debug=debug,sigma=sigma,eps=eps) |> success --> true
      Expected: true
      Occurred: false
INFO: Testing plot: pyplot:14:Bar
Error encountered while loading "C:\Users\Denis\AppData\Local\Temp\jl_6531.tmp.png".
Fatal error:
WARNING: Image did not match reference image C:\Users\Denis\.julia\v0.5\PlotReferenceImages\Plots\pyplot\0.9.6\ref14.png. err: ErrorException("no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/504")
  Failure :: (line:272) :: fact was false
    Expression: image_comparison_tests(pkg,i,debug=debug,sigma=sigma,eps=eps) |> success --> true
      Expected: true
      Occurred: false
INFO: Testing plot: pyplot:15:Histogram
Error encountered while loading "C:\Users\Denis\AppData\Local\Temp\jl_67F2.tmp.png".
Fatal error:
WARNING: Image did not match reference image C:\Users\Denis\.julia\v0.5\PlotReferenceImages\Plots\pyplot\0.9.6\ref15.png. err: ErrorException("no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/504")
  Failure :: (line:272) :: fact was false
    Expression: image_comparison_tests(pkg,i,debug=debug,sigma=sigma,eps=eps) |> success --> true
      Expected: true
      Occurred: false
INFO: Testing plot: pyplot:16:Subplots
Error encountered while loading "C:\Users\Denis\AppData\Local\Temp\jl_69D7.tmp.png".
Fatal error:
WARNING: Image did not match reference image C:\Users\Denis\.julia\v0.5\PlotReferenceImages\Plots\pyplot\0.9.6\ref16.png. err: ErrorException("no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/504")
  Failure :: (line:272) :: fact was false
    Expression: image_comparison_tests(pkg,i,debug=debug,sigma=sigma,eps=eps) |> success --> true
      Expected: true
      Occurred: false
INFO: Testing plot: pyplot:17:Adding to subplots
Error encountered while loading "C:\Users\Denis\AppData\Local\Temp\jl_6D53.tmp.png".
Fatal error:
WARNING: Image did not match reference image C:\Users\Denis\.julia\v0.5\PlotReferenceImages\Plots\pyplot\0.9.6\ref17.png. err: ErrorException("no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/504")
  Failure :: (line:272) :: fact was false
    Expression: image_comparison_tests(pkg,i,debug=debug,sigma=sigma,eps=eps) |> success --> true
      Expected: true
      Occurred: false
INFO: Testing plot: pyplot:18:
Error encountered while loading "C:\Users\Denis\AppData\Local\Temp\jl_6FF3.tmp.png".
Fatal error:
WARNING: Image did not match reference image C:\Users\Denis\.julia\v0.5\PlotReferenceImages\Plots\pyplot\0.9.6\ref18.png. err: ErrorException("no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/504")
  Failure :: (line:272) :: fact was false
    Expression: image_comparison_tests(pkg,i,debug=debug,sigma=sigma,eps=eps) |> success --> true
      Expected: true
      Occurred: false
INFO: Testing plot: pyplot:19:Open/High/Low/Close
Error encountered while loading "C:\Users\Denis\AppData\Local\Temp\jl_72F2.tmp.png".
Fatal error:
WARNING: Image did not match reference image C:\Users\Denis\.julia\v0.5\PlotReferenceImages\Plots\pyplot\0.9.6\ref19.png. err: ErrorException("no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/504")
  Failure :: (line:272) :: fact was false
    Expression: image_comparison_tests(pkg,i,debug=debug,sigma=sigma,eps=eps) |> success --> true
      Expected: true
      Occurred: false
INFO: Testing plot: pyplot:20:Annotations
C:\Users\Denis\.julia\v0.5\Conda\deps\usr\lib\site-packages\matplotlib\font_manager.py:1297: UserWarning: findfont: Font family [u'courier'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
Error encountered while loading "C:\Users\Denis\AppData\Local\Temp\jl_7593.tmp.png".
Fatal error:
WARNING: Image did not match reference image C:\Users\Denis\.julia\v0.5\PlotReferenceImages\Plots\pyplot\0.9.6\ref20.png. err: ErrorException("no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/504")
  Failure :: (line:272) :: fact was false
    Expression: image_comparison_tests(pkg,i,debug=debug,sigma=sigma,eps=eps) |> success --> true
      Expected: true
      Occurred: false
INFO: Testing plot: pyplot:21:Custom Markers
Error encountered while loading "C:\Users\Denis\AppData\Local\Temp\jl_7B31.tmp.png".
Fatal error:
WARNING: Image did not match reference image C:\Users\Denis\.julia\v0.5\PlotReferenceImages\Plots\pyplot\0.9.6\ref21.png. err: ErrorException("no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/504")
  Failure :: (line:272) :: fact was false
    Expression: image_comparison_tests(pkg,i,debug=debug,sigma=sigma,eps=eps) |> success --> true
      Expected: true
      Occurred: false
INFO: Testing plot: pyplot:22:Contours
Error encountered while loading "C:\Users\Denis\AppData\Local\Temp\jl_7EAD.tmp.png".
Fatal error:
WARNING: Image did not match reference image C:\Users\Denis\.julia\v0.5\PlotReferenceImages\Plots\pyplot\0.9.6\ref22.png. err: ErrorException("no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/504")
  Failure :: (line:272) :: fact was false
    Expression: image_comparison_tests(pkg,i,debug=debug,sigma=sigma,eps=eps) |> success --> true
      Expected: true
      Occurred: false
INFO: Testing plot: pyplot:23:Pie
Error encountered while loading "C:\Users\Denis\AppData\Local\Temp\jl_83BF.tmp.png".
Fatal error:
WARNING: Image did not match reference image C:\Users\Denis\.julia\v0.5\PlotReferenceImages\Plots\pyplot\0.9.6\ref23.png. err: ErrorException("no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/504")
  Failure :: (line:272) :: fact was false
    Expression: image_comparison_tests(pkg,i,debug=debug,sigma=sigma,eps=eps) |> success --> true
      Expected: true
      Occurred: false
INFO: Testing plot: pyplot:24:3D
Error encountered while loading "C:\Users\Denis\AppData\Local\Temp\jl_869E.tmp.png".
Fatal error:
WARNING: Image did not match reference image C:\Users\Denis\.julia\v0.5\PlotReferenceImages\Plots\pyplot\0.9.6\ref24.png. err: ErrorException("no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/504")
  Failure :: (line:272) :: fact was false
    Expression: image_comparison_tests(pkg,i,debug=debug,sigma=sigma,eps=eps) |> success --> true
      Expected: true
      Occurred: false
INFO: Testing plot: pyplot:26:Groups and Subplots
Error encountered while loading "C:\Users\Denis\AppData\Local\Temp\jl_896E.tmp.png".
Fatal error:
WARNING: Image did not match reference image C:\Users\Denis\.julia\v0.5\PlotReferenceImages\Plots\pyplot\0.9.6\ref26.png. err: ErrorException("no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/504")
  Failure :: (line:272) :: fact was false
    Expression: image_comparison_tests(pkg,i,debug=debug,sigma=sigma,eps=eps) |> success --> true
      Expected: true
      Occurred: false
INFO: Testing plot: pyplot:27:Polar Plots
Error encountered while loading "C:\Users\Denis\AppData\Local\Temp\jl_8CCA.tmp.png".
Fatal error:
WARNING: Image did not match reference image C:\Users\Denis\.julia\v0.5\PlotReferenceImages\Plots\pyplot\0.9.6\ref27.png. err: ErrorException("no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/504")
  Failure :: (line:272) :: fact was false
    Expression: image_comparison_tests(pkg,i,debug=debug,sigma=sigma,eps=eps) |> success --> true
      Expected: true
      Occurred: false
INFO: Testing plot: pyplot:28:Heatmap, categorical axes, and aspect_ratio
Error encountered while loading "C:\Users\Denis\AppData\Local\Temp\jl_8DF4.tmp.png".
Fatal error:
WARNING: Image did not match reference image C:\Users\Denis\.julia\v0.5\PlotReferenceImages\Plots\pyplot\0.9.6\ref28.png. err: ErrorException("no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/504")
  Failure :: (line:272) :: fact was false
    Expression: image_comparison_tests(pkg,i,debug=debug,sigma=sigma,eps=eps) |> success --> true
      Expected: true
      Occurred: false
INFO: Testing plot: pyplot:29:Layouts, margins, label rotation, title location
Error encountered while loading "C:\Users\Denis\AppData\Local\Temp\jl_9596.tmp.png".
Fatal error:
WARNING: Image did not match reference image C:\Users\Denis\.julia\v0.5\PlotReferenceImages\Plots\pyplot\0.9.6\ref29.png. err: ErrorException("no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/504")
  Failure :: (line:272) :: fact was false
    Expression: image_comparison_tests(pkg,i,debug=debug,sigma=sigma,eps=eps) |> success --> true
      Expected: true
      Occurred: false
Out of 30 total facts:
  Verified: 2
  Failed:   27
  Errored:  1
GR
2 facts verified.
Plotly
2 facts verified.
UnicodePlots
3 facts verified.
Axes
6 facts verified.
ERROR: LoadError: FactCheck finished with 28 non-successful tests.
 in exitstatus() at C:\Users\Denis\.julia\v0.5\FactCheck\src\FactCheck.jl:568
 in include_from_node1(::String) at .\loading.jl:488
 in process_options(::Base.JLOptions) at .\client.jl:262
 in _start() at .\client.jl:318
while loading C:\Users\Denis\.julia\v0.5\Plots\test\runtests.jl, in expression starting on line 130
================================[ ERROR: Plots ]================================

failed process: Process(`'C:\Users\Denis\AppData\Local\Julia-0.5.0\bin\julia' -Cx86-64 '-JC:\Users\Denis\AppData\Local\Julia-0.5.0\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes 'C:\Users\Denis\.julia\v0.5\Plots\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================
INFO: Removing AxisAlgorithms v0.1.6
INFO: Removing AxisArrays v0.0.3
INFO: Removing CatIndices v0.0.2
INFO: Removing ColorVectorSpace v0.4.0
INFO: Removing ComputationalResources v0.0.2
INFO: Removing CustomUnitRanges v0.0.4
INFO: Removing DataArrays v0.3.12
INFO: Removing DataFrames v0.8.5
INFO: Removing DualNumbers v0.2.3
INFO: Removing FFTViews v0.0.1
INFO: Removing FactCheck v0.4.3
INFO: Removing FileIO v0.3.0
INFO: Removing GZip v0.2.20
INFO: Removing Glob v1.1.0
INFO: Removing ImageAxes v0.1.0
INFO: Removing ImageCore v0.1.4
INFO: Removing ImageFiltering v0.1.2
INFO: Removing ImageMagick v0.2.1
INFO: Removing ImageMetadata v0.2.0
INFO: Removing Images v0.7.0
INFO: Removing IndirectArrays v0.1.1
INFO: Removing Interpolations v0.3.7
INFO: Removing IntervalSets v0.0.3
INFO: Removing KernelDensity v0.3.0
INFO: Removing MappedArrays v0.0.6
INFO: Removing OffsetArrays v0.2.14
INFO: Removing RData v0.0.4
INFO: Removing RDatasets v0.2.0
INFO: Removing RangeArrays v0.1.2
INFO: Removing Ratios v0.0.4
INFO: Removing SIUnits v0.1.0
INFO: Removing ShowItLikeYouBuildIt v0.0.1
INFO: Removing SortingAlgorithms v0.1.0
INFO: Removing StatPlots v0.2.1
INFO: Removing StaticArrays v0.2.1
INFO: Removing TexExtensions v0.0.3
INFO: Removing TiledIteration v0.0.1
INFO: Removing VisualRegressionTests v0.1.0
INFO: Removing WoodburyMatrices v0.2.2
ERROR: Plots had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at .\pkg\entry.jl:740
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at .\<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\pkg\dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258
 in test(::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258

julia>

**Comment by mkborregaard** [comment] 2017-02-22 10:06
This is due to matplotlib being updated to 2.0, so the PyPlot reference images are off. What is needed is to produce these plots, make sure they look and behave as expected, then save a new reference image. PR's doing that are very welcome!
BTW this is a duplicate of https://github.com/JuliaPlots/Plots.jl/issues/670

**Comment by mkborregaard** [comment] 2017-05-16 07:23
Closed as dup

**Closed by mkborregaard** 2017-05-16 07:23 UTC
