### ISSUE TITLE
Plots 0.13.1 linestyles do not work properly

### ISSUE THREAD

**Issue by valfaro** [JuliaPlots/Plots.jl#1139] opened 2017-10-06 15:50 UTC
Julia sample code:

using Plots; gr()
x = 0:0.01:3
y1 = sin(2π.*x).*exp.(-x)
y2 = 0.6*y1; y3 = 0.3*y1
plot([x x x], [y1 y2 y3], ls=[:dash :dashdot :dashdotdot], lw=2)

[sample.pdf](https://github.com/JuliaPlots/Plots.jl/files/1363204/sample.pdf)

**Comment by joshday** [comment] 2017-10-06 16:39
I can reproduce.  I think it's from a relatively recent change.

This:
<img width="919" alt="screen shot 2017-10-06 at 12 35 27 pm" src="https://user-images.githubusercontent.com/8075494/31288418-db01bee8-aa92-11e7-9063-2b3e01997f57.png">

Was this before my latest Pkg.update:
<img width="782" alt="screen shot 2017-10-06 at 12 36 05 pm" src="https://user-images.githubusercontent.com/8075494/31288445-f348313a-aa92-11e7-9ff7-c0b891ea7130.png">

**Comment by valfaro** [comment] 2017-10-06 17:26
Thats correct, change commes from latest update.

previos plot
[jlsc_Ident_pade01.pdf](https://github.com/JuliaPlots/Plots.jl/files/1363431/jlsc_Ident_pade01.pdf)

new plot
[jlsc_Ident_pade01.pdf](https://github.com/JuliaPlots/Plots.jl/files/1363435/jlsc_Ident_pade01.pdf)

if you print (b&w) the new plot you can not  know what lines is each one

**Comment by joshday** [comment] 2017-10-06 17:35
Also, this is specific to GR.  

@daschw I think I found the commit which introduced this:  https://github.com/JuliaPlots/Plots.jl/commit/5f8486536561746b73823065ac033896ed220082, but I'm not sure where to look to diagnose it further.

**Comment by daschw** [comment] 2017-10-06 18:12
Thanks a lot guys for reporting and investigating this!
This was indeed my fault. With the above commit each line segment is drawn individually (in order to be able to have differently colored line segments with the `line_z` attribute). Thus, the line styles get hidden if the segments are too short. That's why steeper parts work "better" than flat parts.
I will try to fix this tomorrow!

I'm not sure yet, if I should deactivate multi-colored lines for GR again or if we should accept this linestyle issue if `series[:line_z]` is a vector.

**Comment by piever** [comment] 2017-10-08 07:30
@daschw I strongly suspect the ribbon issue #1123 also is caused by this, I don't have computer access in the next few days but remember to also check fillrange and ribbon when fixing this.

**Comment by daschw** [comment] 2017-10-08 10:19
Nice, well spotted @piever! It's already fixed in #1139. I will close #1123 when I merge.

**Closed** 2017-10-08 11:50 UTC
