### ISSUE TITLE
annotation auto-locations don't work with `xlims`

### ISSUE THREAD

**Issue by ssfrr** [JuliaPlots/Plots.jl#2591] opened 2020-04-16 19:15 UTC
It seems that the annotation position is computed in data coordinates before `xlims` (and presumably `ylims`) are applied, so if you specify a location as `:bottomright` etc. the annotation may be off-plot.

This works:
```julia
plot(rand(20), ann=[(:bottomright, "foobar")], xlims=(0,20))
```
But this has the annotation going offscreen:

```julia
plot(rand(20), ann=[(:bottomright, "foobar")], xlims=(0,18))
```

**Comment by isentropic** [comment] 2020-04-24 03:12
Yeah, I can only suggest to filter up the data first (manually). Does this happen in all backends?

**Comment by ivan-boikov** [comment] 2023-04-11 19:08
Can't reproduce on current, GR works, PGFPlotsX crashes (but it will be fixed in a pull request I am about to submit).
![2591](https://user-images.githubusercontent.com/66747290/231264247-dbdba64b-fd41-4893-8206-61f8c50561fc.png)
@t-bltg or @BeastyBlacksmith could you please check and maybe close?

**Closed** 2023-04-12 08:25 UTC
Labels: bug
