### ISSUE TITLE
[BUG] Revise doesn't work with PyPlot

### ISSUE THREAD

**Issue by vavrines** [JuliaPlots/Plots.jl#3999] opened 2021-12-13 08:28 UTC
## Details

On Julia v1.7 Revise.jl causes the following error info.

```julia
julia> using Revise

julia> using Plots

julia> pyplot()
ERROR: UndefVarError: PyPlot not defined
Revise evaluation error at /home2/vavrines/.julia/packages/Plots/FCM0H/src/backends/pyplot.jl:12
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     |
pyplot       |   x  |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
unicodeplots |     |     |
inspectdr    |     |     |
gaston       |     |     |

### Versions

Plots.jl version: v1.25.2
Backend  version (`]st -m <backend(s)>`): PyPlot v2.10.0
Output of `versioninfo()`: 
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 9 3950X 16-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, znver2)

**Comment by t-bltg** [comment] 2021-12-13 14:25
Duplicate of https://github.com/timholy/Revise.jl/issues/658.

**Closed by t-bltg** 2021-12-13 14:25 UTC
Labels: bug
