### ISSUE TITLE
pie and theme(:ggplot2)

### ISSUE THREAD

**Issue by baggepinnen** [JuliaPlots/Plots.jl#2431] opened 2020-03-04 00:21 UTC
The `pie` recipe does not work with theme set to `ggplot2` but works with default theme. MWE below.
```julia
julia> theme(:ggplot2)

julia> using StatsBase

julia> pie(countmap(rand(1:5, 10)))
Error showing value of type Plots.Plot{Plots.GRBackend}:
ERROR: MethodError: no method matching getindex(::Nothing, ::Int64)
Stacktrace:
 [1] get_minor_ticks(::Plots.Subplot{Plots.GRBackend}, ::Plots.Axis, ::Nothing) at /home/fredrikb/.julia/packages/Plots/WwFyB/src/axes.jl:293
 [2] axis_drawing_info(::Plots.Subplot{Plots.GRBackend}) at /home/fredrikb/.julia/packages/Plots/WwFyB/src/axes.jl:623
 [3] _update_min_padding!(::Plots.Subplot{Plots.GRBackend}) at /home/fredrikb/.julia/packages/Plots/WwFyB/src/backends/gr.jl:781
 [4] iterate at ./generator.jl:47 [inlined]

```

**Comment by mkborregaard** [comment] 2020-03-04 10:54
This is a duplicate of https://github.com/JuliaPlots/Plots.jl/issues/723 (which I've just renamed to make that clearer)

**Closed by mkborregaard** 2020-03-04 10:54 UTC
