### ISSUE TITLE
Failed to precompile Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]

### ISSUE THREAD

**Issue by SuperGrobi** [JuliaPlots/Plots.jl#2888] opened 2020-08-03 20:03 UTC
Today I got (I would say out of nowhere) the following error when trying to precompile Plots 1.5.7:
```julia
`julia> using Plots`

results in:

[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x668b3d85 -- gc_mark_loop at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gc.c:2400
in expression starting at C:\Users\Henrik\.julia\packages\Plots\LWw1t\src\Plots.jl:15
gc_mark_loop at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gc.c:2399
_jl_gc_collect at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gc.c:2703
jl_gc_collect at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gc.c:2903
maybe_collect at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gc.c:781 [inlined]
jl_gc_big_alloc at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gc.c:837
jl_gc_alloc_ at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\julia_internal.h:238 [inlined]
jl_gc_alloc at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gc.c:2940
_new_array_ at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\array.c:100
_new_array at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\array.c:163 [inlined]
jl_alloc_array_1d at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\array.c:424
Array at .\boot.jl:404 [inlined]
Array at .\boot.jl:413 [inlined]
fill at .\array.jl:411 [inlined]
fill at .\array.jl:409 [inlined]
IncrementalCompact at .\compiler/ssair\ir.jl:493
compact! at .\compiler/ssair\ir.jl:1296
compact! at .\compiler/ssair\ir.jl:1296 [inlined]
run_passes at .\compiler/ssair\driver.jl:127
optimize at .\compiler\optimize.jl:169
typeinf at .\compiler\typeinfer.jl:33
abstract_call_method_with_const_args at .\compiler\abstractinterpretation.jl:243
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:116
abstract_call at .\compiler\abstractinterpretation.jl:850
abstract_call at .\compiler\abstractinterpretation.jl:636
abstract_eval_call at .\compiler\abstractinterpretation.jl:879
abstract_eval at .\compiler\abstractinterpretation.jl:949
typeinf_local at .\compiler\abstractinterpretation.jl:1208
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1264
typeinf at .\compiler\typeinfer.jl:12
typeinf_edge at .\compiler\typeinfer.jl:488
abstract_call_method at .\compiler\abstractinterpretation.jl:396
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:93
abstract_call at .\compiler\abstractinterpretation.jl:850
abstract_call at .\compiler\abstractinterpretation.jl:636
abstract_eval_call at .\compiler\abstractinterpretation.jl:879
abstract_eval at .\compiler\abstractinterpretation.jl:949
typeinf_local at .\compiler\abstractinterpretation.jl:1194
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1264
typeinf at .\compiler\typeinfer.jl:12
typeinf_edge at .\compiler\typeinfer.jl:488
abstract_call_method at .\compiler\abstractinterpretation.jl:396
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:93
abstract_call at .\compiler\abstractinterpretation.jl:850
abstract_call at .\compiler\abstractinterpretation.jl:636
abstract_eval_call at .\compiler\abstractinterpretation.jl:879
abstract_eval at .\compiler\abstractinterpretation.jl:949
typeinf_local at .\compiler\abstractinterpretation.jl:1208
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1264
typeinf at .\compiler\typeinfer.jl:12
typeinf_edge at .\compiler\typeinfer.jl:488
abstract_call_method at .\compiler\abstractinterpretation.jl:396
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:93
abstract_call at .\compiler\abstractinterpretation.jl:850
abstract_call at .\compiler\abstractinterpretation.jl:636
abstract_eval_call at .\compiler\abstractinterpretation.jl:879
abstract_eval at .\compiler\abstractinterpretation.jl:949
typeinf_local at .\compiler\abstractinterpretation.jl:1194
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1264
typeinf at .\compiler\typeinfer.jl:12
typeinf_edge at .\compiler\typeinfer.jl:488
abstract_call_method at .\compiler\abstractinterpretation.jl:396
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:93
abstract_call at .\compiler\abstractinterpretation.jl:850
abstract_call at .\compiler\abstractinterpretation.jl:636
abstract_eval_call at .\compiler\abstractinterpretation.jl:879
abstract_eval at .\compiler\abstractinterpretation.jl:949
typeinf_local at .\compiler\abstractinterpretation.jl:1208
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1264
typeinf at .\compiler\typeinfer.jl:12
typeinf_edge at .\compiler\typeinfer.jl:488
abstract_call_method at .\compiler\abstractinterpretation.jl:396
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:93
abstract_call at .\compiler\abstractinterpretation.jl:850
abstract_call at .\compiler\abstractinterpretation.jl:636
abstract_eval_call at .\compiler\abstractinterpretation.jl:879
abstract_eval at .\compiler\abstractinterpretation.jl:949
typeinf_local at .\compiler\abstractinterpretation.jl:1194
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1264
typeinf at .\compiler\typeinfer.jl:12
typeinf_edge at .\compiler\typeinfer.jl:488
abstract_call_method at .\compiler\abstractinterpretation.jl:396
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:93
abstract_call at .\compiler\abstractinterpretation.jl:850
abstract_call at .\compiler\abstractinterpretation.jl:636
abstract_eval_call at .\compiler\abstractinterpretation.jl:879
abstract_eval at .\compiler\abstractinterpretation.jl:949
typeinf_local at .\compiler\abstractinterpretation.jl:1208
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1264
typeinf at .\compiler\typeinfer.jl:12
typeinf_edge at .\compiler\typeinfer.jl:488
abstract_call_method at .\compiler\abstractinterpretation.jl:396
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:93
abstract_call at .\compiler\abstractinterpretation.jl:850
abstract_call at .\compiler\abstractinterpretation.jl:636
abstract_eval_call at .\compiler\abstractinterpretation.jl:879
abstract_eval at .\compiler\abstractinterpretation.jl:949
typeinf_local at .\compiler\abstractinterpretation.jl:1208
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1264
typeinf at .\compiler\typeinfer.jl:12
typeinf_ext at .\compiler\typeinfer.jl:574
typeinf_ext at .\compiler\typeinfer.jl:605
jfptr_typeinf_ext_1.clone_1 at C:\Users\Henrik\AppData\Local\Julia-1.3.0\lib\julia\sys.dll (unknown line)
jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2135 [inlined]
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1631 [inlined]
jl_type_infer at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:209
jl_compile_method_internal at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:1879
_jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2140 [inlined]
jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2305
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1631 [inlined]
jl_module_run_initializer at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:74
jl_init_restored_modules at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\dump.c:2477
_include_from_serialized at .\loading.jl:692
_require_search_from_serialized at .\loading.jl:776
_tryrequire_from_serialized at .\loading.jl:707
_require_search_from_serialized at .\loading.jl:765
_require at .\loading.jl:1001
require at .\loading.jl:922
require at .\loading.jl:917
_jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2135 [inlined]
jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2305
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1631 [inlined]
call_require at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:399 [inlined]
eval_import_path at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:436
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:656
jl_eval_module_expr at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:181
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:640
jl_parse_eval_all at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\ast.c:873
jl_load at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:878 [inlined]
jl_load_ at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:885
include at .\boot.jl:328 [inlined]
include_relative at .\loading.jl:1105
include at .\Base.jl:31
_jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2135 [inlined]
jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2305
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1631 [inlined]
do_call at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:328
eval_value at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:417
eval_stmt_value at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:368 [inlined]
eval_body at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:764
eval_body at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:705
jl_interpret_toplevel_thunk_callback at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:888
unknown function (ip: FFFFFFFFFFFFFFFE)
unknown function (ip: 0000000010680A8F)
unknown function (ip: 0000000000000002)
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:814
jl_toplevel_eval at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:823 [inlined]
jl_toplevel_eval_in at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:843
eval at .\boot.jl:330 [inlined]
eval at .\client.jl:425
_jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2135 [inlined]
jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2305
top-level scope at .\none:3
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:808
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:764
jl_toplevel_eval at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:823 [inlined]
jl_toplevel_eval_in at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:843
eval at .\boot.jl:330
_jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2135 [inlined]
jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2305
exec_options at .\client.jl:263
_start at .\client.jl:460
jfptr__start_2086.clone_1 at C:\Users\Henrik\AppData\Local\Julia-1.3.0\lib\julia\sys.dll (unknown line)
_jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2135 [inlined]
jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2305
unknown function (ip: 00000000004017DD)
unknown function (ip: 0000000000401BC5)
unknown function (ip: 00000000004013DE)
unknown function (ip: 000000000040151A)
BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
Allocations: 6348223 (Pool: 6347766; Big: 457); GC: 2
ERROR: Failed to precompile Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80] to C:\Users\Henrik\.julia\compiled\v1.3\Plots\ld3vC_fqMhb.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
```

I have no idea where this problem comes from or how to fix it. It first occurred after I restarted the REPL when working in Juno.
So far I tried to reinstall Plots, install an earlier version (1.5.6), as well as deleting the Plots files in the compiled directory, to no avail.

Do you have any insight into what is going on?

**Comment by daschw** [comment] 2020-08-03 21:11
duplicate of https://github.com/JuliaPlots/Plots.jl/issues/2881, also relevant https://github.com/JuliaPlots/Plots.jl/issues/2838

**Comment by alec-hoyland** [comment] 2020-08-03 21:41
What's your Julia version?

**Comment by alec-hoyland** [comment] 2020-08-03 21:45
Looks like you're using version 1.3... my precompile seg-fault issue (#2881) went away with a newer version of Julia. I think version 1.4.2 is the current stable release.

**Comment by daschw** [comment] 2020-08-03 22:50
1.5.0 is the current stable release https://julialang.org/downloads/.

**Closed** 2021-08-04 10:35 UTC
Labels: duplicate

**Comment by qllian** [comment] 2022-03-20 12:58
Uninstall and delete C:/user/.julia . and then,install julia agin ,it work to me

**Comment by animesh11** [comment] 2023-07-01 11:45
uninstall julia and move to some other language.
