### ISSUE TITLE
[FR] replace (`PyCall`, `PyPlot`) with (`PythonCall`, `PythonPlot`)

### ISSUE THREAD

**Issue by t-bltg** [JuliaPlots/Plots.jl#4471] opened 2022-10-21 13:08 UTC
[`PythonPlot`](https://github.com/stevengj/PythonPlot.jl) is not yet registered, but this will be the future.

[`PythonCall`](https://github.com/cjdoris/PythonCall.jl) is the `julia` - `python` overhead free interface.

I'm opening this issue in case someone is interested in working on the transition for the `pyplot` backend.

**Comment by BeastyBlacksmith** [comment] 2022-10-21 13:40
duplicate of #4181

**Closed** 2022-10-21 13:41 UTC
Labels: duplicate, help wanted, PyPlot, 2.0
